#!/usr/bin/env node
// Writes a baseline library seed from `src/library.ts` —
// REQ-DSG-026, DEC-128, DEC-148.
//
// ★ FORWARD-ONLY (DEC-149 §3). Its first output is promoted as
// `supabase/migrations/0098_certificate_library.sql`, and a migration is never
// regenerated. A later change to `library.ts` is written as a NEW proposed
// seed and promoted as a new migration:
//
//   npm run build -w @kareem/designer-runtime
//   node packages/designer-runtime/scripts/seed-sql.mjs > supabase/proposed/designer/NNNN_<what-changed>.sql
//
// Because the seed is idempotent by composition (below), the new file carries
// the whole library and adds only the versions the database does not have.
// Edit the header text below before handing it over — it names this seed.
//
// The library is the source and the SQL is a copy. `tests/unit/designer-
// library.test.ts` parses every `$json$…$json$` back out of the seed files and
// deep-equals it against the library, so a hand edit of the SQL — or a
// library change nobody reseeded — fails CI rather than diverging.
//
// Idempotent by COMPOSITION, never by id, so a re-run adds nothing:
//   · a poster family, or a certificate family's landscape composition, is
//     the platform DEFAULT of its (purpose, family) — the row 0061 seeded —
//     and gains the library's version when it does not have it yet;
//   · a certificate family's portrait composition is the non-default platform
//     row of that family whose versions carry a portrait master, created with
//     its version 1 when there is none.
// A version is ADDED, never edited: an artifact references a version, and a
// certificate issued against version 1 renders as version 1 forever
// (REQ-DSG-007, REQ-CRT-014).

import { BASELINE_LIBRARY, dynamicFieldsOf } from '../dist/index.js'

const lit = (s) => `'${String(s).replace(/'/g, "''")}'`

const out = []
out.push(`-- designer (wave 24, M26) — the baseline library REBUILT to «ساحة اللعب», and the superseded eleven superseded.
-- Follows 0192 (the platform palette) and supersedes 0061 + 0098's rows.
--
-- Serves:  REQ-DSG-033 (the designed poster families), REQ-CRT-016 (the
--          designed certificate families), REQ-DSG-034 (the superseded
--          baseline leaves the library), REQ-DSG-026 as DEC-242 amends it,
--          REQ-DSG-021 (tokens only), REQ-DSG-024 (locked regions),
--          REQ-CRT-010, REQ-CRT-014 (a pinned version still renders)
-- Cites:   DEC-242 §1 (the thumbnails are the specification), §2 (the palette
--          and the token vocabulary), §3 (delete where permitted, retire where
--          refused), §4; DEC-125 (posters dark), DEC-128, DEC-148
--
-- 03 §8.2 ROWS: see \`supersede_baseline_template()\`'s own file. This file
-- creates no policy and no grant — it inserts rows into two tables 0055
-- already policied, as the owner during migration.
--
-- GENERATED by packages/designer-runtime/scripts/seed-sql.mjs from
-- packages/designer-runtime/src/library.ts. Do not edit by hand:
-- tests/unit/designer-library.test.ts parses every \$json\$…\$json\$ back out and
-- deep-equals it against the library.
--
-- ★★ ELEVEN NEW ROWS, NOT NEW VERSIONS OF THE OLD ONES (REQ-DSG-034). Every
-- document in the library changed, so each composition ships as a new platform
-- template at version 1 and the superseded row is deleted — or RETIRED, where
-- \`on delete restrict\` refuses, because a certificate issued against a 2026
-- version must render as that version for ever (REQ-CRT-014). The migration
-- reports which went which way, per row.
--
-- ★ THE NEW ROW IS INSERTED BEFORE THE OLD ONE IS SUPERSEDED, and the order is
-- load-bearing: \`design_templates_single_default\` (0057) clears the previous
-- default in the same statement, so by the time the supersede step runs the old
-- row is already non-default — which means issuance and poster_render_context()
-- prefer the new row even before \`retired_at\` is set, and there is never a
-- window with no non-retired default of a purpose.
--
-- ★ IDEMPOTENT ON THE LIVE ROW, which is 0061's pattern with one necessary
-- third condition: \`retired_at is null\`. Without it a re-run finds the RETIRED
-- old row and skips the insert — and the portrait lookup, which asks for «the
-- non-default platform row of this family», would match a retired landscape row.

do $$
declare
  v_template uuid;
  -- The eleven rows this file seeds. Everything else in platform scope is
  -- superseded at the end, which is how the step stays id-free.
  v_kept     uuid[] := '{}';
  v_doc      jsonb;
  v_fields   jsonb;
  v_old      record;
  v_outcome  text;
  v_refused  text;
begin
`)

for (const t of BASELINE_LIBRARY) {
  const marker = t.purpose === 'poster' ? `${t.family}@v${t.version}` : `${t.family}@${t.orientation}@v${t.version}`
  const json = JSON.stringify(t.document, null, 2)
  const fields = JSON.stringify(dynamicFieldsOf(t.document))
  if (json.includes('$json$') || fields.includes('$fields$')) throw new Error(`${marker}: a dollar-quote tag appears inside the document`)

  // ★★ IDEMPOTENT ON THE DOCUMENT, not on `(scope, purpose, family)` — and this
  // is the one thing wave 24's seed does differently from every seed before it.
  //
  // 0061 and 0098 ADDED A VERSION to an existing row, so «the live default of
  // this (purpose, family)» was exactly the row to seed into. Wave 24 REPLACES
  // the row (REQ-DSG-034), and that key cannot tell the row being replaced from
  // the row replacing it: on the first run it matches the SUPERSEDED row, finds
  // version 1 already present, inserts nothing, and the document never changes.
  // Measured, not reasoned about — `tests/rls/templates-roster.test.ts` caught
  // it: 11 templates and 19 versions, the old documents still live.
  //
  // The row carrying THIS EXACT DOCUMENT is the honest key. `jsonb` equality is
  // structural and key-order independent, the literal is declared once into
  // `v_doc` rather than written twice, and a re-run finds the row it created and
  // does nothing.
  const seedOne = (lookup) => `v_template := null;
v_doc    := $json$${json}$json$::jsonb;
v_fields := $fields$${fields}$fields$::jsonb;

${lookup}

if v_template is null then
  -- RETURNING, never a second lookup: a select by (family, name) would match the
  -- SUPERSEDED row, which still carries this family and this name until the
  -- supersede step runs — and would then insert version 1 on a row that already
  -- has one. That is the duplicate key the roster suite raised.
  insert into public.design_templates (org_id, scope, purpose, family, name, is_default)
  values (null, 'platform', ${lit(t.purpose)}, ${lit(t.family)}, ${lit(t.name)}, ${t.isDefault})
  returning id into v_template;

  insert into public.design_template_versions (template_id, version, document, dynamic_fields, font_hashes, published_at)
  values (
    v_template, ${t.version}, v_doc, v_fields,
    -- No font hash is pinned on a platform version: the platform set is
    -- installed by hash in every image (REQ-DSG-016), as 0061 recorded.
    '{}',
    now()
  );
end if;
v_kept := v_kept || v_template;
`

  out.push(`-- @family ${marker}`)
  out.push(
    seedOne(`-- The platform row that already carries this document, if this seed has run before.
select t.id into v_template
  from public.design_templates t
  join public.design_template_versions v on v.template_id = t.id
 where t.scope = 'platform' and t.purpose = ${lit(t.purpose)} and t.family = ${lit(t.family)}
   and t.retired_at is null and v.document = v_doc
 order by t.created_at
 limit 1;`),
  )
}

out.push(`-- ★ The eleven are seeded. Everything else in platform scope is superseded.
`)

// ★★ THE SUPERSEDE STEP (REQ-DSG-034, DEC-242 §3). Every platform row that is
// NOT one of the eleven just seeded is superseded: deleted where the database
// permits, retired where `on delete restrict` refuses. Identified by exclusion
// rather than by a hard-coded id list, so the step is correct in an environment
// whose ids nobody here can know — and `retired_at is null` keeps a re-run from
// re-reporting a row it already retired.
out.push(`-- @supersede
for v_old in
  select t.id, t.purpose::text as purpose, t.family, t.name
    from public.design_templates t
   where t.scope = 'platform' and t.retired_at is null and t.id <> all(v_kept)
   order by t.purpose, t.family, t.created_at
loop
  select s.outcome, s.refused_by into v_outcome, v_refused
    from public.supersede_baseline_template(v_old.id) s;
  raise notice 'supersede % % % (%) -> % %',
    v_old.purpose, v_old.family, v_old.name, v_old.id, v_outcome, coalesce(v_refused, '');
end loop;

end $$;
`)
process.stdout.write(out.join('\n'))
