#!/usr/bin/env node
// Writes the baseline library's seed migration from `src/library.ts` —
// REQ-DSG-026, DEC-128, DEC-148.
//
//   npm run build -w @kareem/designer-runtime
//   node packages/designer-runtime/scripts/seed-sql.mjs > supabase/proposed/designer/0002_certificate_library.sql
//
// The library is the source and the SQL is a copy. `tests/unit/designer-
// library.test.ts` parses every `$json$…$json$` back out of the seed files and
// deep-equals it against the library, so a hand edit of the SQL — or a
// library change nobody reseeded — fails CI rather than diverging.
//
// Idempotent by COMPOSITION, never by id, so a re-run adds nothing:
//   · a poster family, or a certificate family's landscape composition, is
//     the platform DEFAULT of its (purpose, family) — the row 0061 seeded —
//     and gains the library's version when it does not have it yet;
//   · a certificate family's portrait composition is the non-default platform
//     row of that family whose versions carry a portrait master, created with
//     its version 1 when there is none.
// A version is ADDED, never edited: an artifact references a version, and a
// certificate issued against version 1 renders as version 1 forever
// (REQ-DSG-007, REQ-CRT-014).

import { BASELINE_LIBRARY, dynamicFieldsOf } from '../dist/index.js'

const lit = (s) => `'${String(s).replace(/'/g, "''")}'`

const out = []
out.push(`-- designer (wave 8) — the certificate library and the completed poster roster.
-- Follows the template guard (designer/0001) and 0061_baseline_library.
--
-- Serves:  REQ-DSG-026 (the seeded roster, counted), REQ-DSG-007 (versions,
--          never edits), REQ-DSG-008 (platform templates), REQ-DSG-021
--          (tokens only), REQ-DSG-024 (locked regions), REQ-CRT-010
-- Cites:   DEC-125 (posters dark), DEC-127 (the gradient), DEC-128 (the
--          certificate library), DEC-148 (a row is a composition; q4)
--
-- 03 §8.2 ROWS: none. No policy and no grant — rows into two tables 0055
-- already policied, as the owner during migration.
--
-- GENERATED by packages/designer-runtime/scripts/seed-sql.mjs from
-- packages/designer-runtime/src/library.ts. Do not edit by hand:
-- tests/unit/designer-library.test.ts deep-equals every document below
-- against the library.
--
-- WHAT IT DOES, per DEC-148's ruling that a baseline row is a COMPOSITION
-- (eleven platform templates; the scheme is never a row):
--   · the five poster families gain VERSION 2 — DEC-127's gradient, the
--     Knowledge Network rule on {{brand.edgeStrong}} (q4), and date and
--     venue lines tall enough for one line at their own size;
--   · the three landscape certificates gain VERSION 2 — every line frame at
--     least one line tall — and are renamed «… أفقية»;
--   · three PORTRAIT certificates are created, «… عمودية», version 1,
--     is_default = false (one platform default per family, 0055's index).
--
-- WHAT IT DOES NOT DO: re-render anything. A live poster takes version 2 at
-- its next regeneration; an org's own copy never receives it (REQ-DSG-008);
-- an issued certificate stays on its pinned version.

do $$
declare
  v_template uuid;
begin
`)

for (const t of BASELINE_LIBRARY) {
  const marker = t.purpose === 'poster' ? `${t.family}@v${t.version}` : `${t.family}@${t.orientation}@v${t.version}`
  const json = JSON.stringify(t.document, null, 2)
  const fields = JSON.stringify(dynamicFieldsOf(t.document))
  if (json.includes('$json$') || fields.includes('$fields$')) throw new Error(`${marker}: a dollar-quote tag appears inside the document`)
  const insertVersion = `  insert into public.design_template_versions (template_id, version, document, dynamic_fields, font_hashes, published_at)
  values (
    v_template, ${t.version},
    $json$${json}$json$::jsonb,
    $fields$${fields}$fields$::jsonb,
    -- No font hash is pinned on a platform version: the platform set is
    -- installed by hash in every image (REQ-DSG-016), as 0061 recorded.
    '{}',
    now()
  );`

  out.push(`-- @family ${marker}`)
  if (t.isDefault) {
    out.push(`v_template := null;
select t.id into v_template from public.design_templates t
 where t.scope = 'platform' and t.purpose = ${lit(t.purpose)} and t.family = ${lit(t.family)} and t.is_default
 limit 1;

if v_template is null then
  insert into public.design_templates (org_id, scope, purpose, family, name, is_default)
  values (null, 'platform', ${lit(t.purpose)}, ${lit(t.family)}, ${lit(t.name)}, true)
  returning id into v_template;
end if;
${
  t.purpose === 'certificate'
    ? `
-- The landscape composition's name says so now that a portrait one exists.
update public.design_templates set name = ${lit(t.name)}
 where id = v_template and name = ${lit(t.name.replace(/ أفقية$/, ''))};
`
    : ''
}
if not exists (select 1 from public.design_template_versions v where v.template_id = v_template and v.version = ${t.version}) then
${insertVersion}
end if;
`)
  } else {
    out.push(`v_template := null;
select t.id into v_template from public.design_templates t
 where t.scope = 'platform' and t.purpose = 'certificate' and t.family = ${lit(t.family)} and not t.is_default
   and exists (select 1 from public.design_template_versions v
                where v.template_id = t.id
                  and (v.document->'master'->>'width')::int < (v.document->'master'->>'height')::int)
 order by t.created_at
 limit 1;

if v_template is null then
  insert into public.design_templates (org_id, scope, purpose, family, name, is_default)
  values (null, 'platform', 'certificate', ${lit(t.family)}, ${lit(t.name)}, false)
  returning id into v_template;
end if;

if not exists (select 1 from public.design_template_versions v where v.template_id = v_template and v.version = ${t.version}) then
${insertVersion}
end if;
`)
  }
}

out.push(`end $$;
`)
process.stdout.write(out.join('\n'))
