#!/usr/bin/env node
// Writes a baseline library seed from `src/library.ts` —
// REQ-DSG-026, DEC-128, DEC-148.
//
// ★ FORWARD-ONLY (DEC-149 §3). Its first output is promoted as
// `supabase/migrations/0098_certificate_library.sql`, and a migration is never
// regenerated. A later change to `library.ts` is written as a NEW proposed
// seed and promoted as a new migration:
//
//   npm run build -w @kareem/designer-runtime
//   node packages/designer-runtime/scripts/seed-sql.mjs > supabase/proposed/designer/NNNN_<what-changed>.sql
//
// Because the seed is idempotent by composition (below), the new file carries
// the whole library and adds only the versions the database does not have.
// Edit the header text below before handing it over — it names this seed.
//
// The library is the source and the SQL is a copy. `tests/unit/designer-
// library.test.ts` parses every `$json$…$json$` back out of the seed files and
// deep-equals it against the library, so a hand edit of the SQL — or a
// library change nobody reseeded — fails CI rather than diverging.
//
// Idempotent by COMPOSITION, never by id, so a re-run adds nothing:
//   · a poster family, or a certificate family's landscape composition, is
//     the platform DEFAULT of its (purpose, family) — the row 0061 seeded —
//     and gains the library's version when it does not have it yet;
//   · a certificate family's portrait composition is the non-default platform
//     row of that family whose versions carry a portrait master, created with
//     its version 1 when there is none.
// A version is ADDED, never edited: an artifact references a version, and a
// certificate issued against version 1 renders as version 1 forever
// (REQ-DSG-007, REQ-CRT-014).

import { BASELINE_LIBRARY, dynamicFieldsOf } from '../dist/index.js'

const lit = (s) => `'${String(s).replace(/'/g, "''")}'`

const out = []
out.push(`-- designer (wave 24, the RE-COLOUR) — the baseline library's documents rebuilt
-- to what the artboards actually draw, as VERSION 2 of the eleven rows the
-- wave's first seed created. Follows 0193 and the guard that admits \`design.*\`.
--
-- Serves:  REQ-DSG-033 (the designed poster families), REQ-CRT-016 (the
--          designed certificate families), REQ-DSG-021 (bound colours only),
--          REQ-DSG-007 and REQ-CRT-014 (a version is ADDED, never edited),
--          REQ-DSG-026 (the roster, still five and three)
-- Cites:   DEC-242 §1 and §2 as the re-colour amends them
--
-- 03 §8.2 ROWS: none. This file inserts one version per existing platform row,
-- into two tables 0055 already policied, as the owner during migration. It
-- creates no policy, no grant and no function.
--
-- GENERATED by packages/designer-runtime/scripts/seed-sql.mjs from
-- packages/designer-runtime/src/library.ts. Do not edit by hand:
-- tests/unit/designer-library.test.ts parses every \$json\$…\$json\$ back out and
-- deep-equals it against the library.
--
-- ★★ A VERSION, NOT A ROW — and this is the one thing it does differently from
-- the seed before it. 0193 created eleven NEW rows because REQ-DSG-034 required
-- M6's baseline to LEAVE the library: there was something to remove, and it was
-- removed. Here there is not. The eleven rows are the right rows, with the
-- right families and the right names, carrying the wrong document — because
-- DEC-242 §1 declared «there is no artboard for a poster» and
-- AdminDesignerElements.dc.html is one. So nothing is superseded, deleted or
-- retired by this file, and \`supersede_baseline_template()\` is not called.
--
-- ★ WHY THE DOCUMENT CHANGED AGAIN. The artboard draws the poster at 640 × 360
-- on \`#FF9A2E\` with \`#0B0C12\` type; its <title> is «ساحة اللعب — لون الفريق»,
-- which is the NAME of the first card in the library artboard — the two files
-- were always one specification. The shipped documents instead took five brand
-- tokens as grounds, three of which (\`canvas\`, \`surface\`, \`canvasRaise\`)
-- resolve within 1.10:1, 1.22:1 and 1.11:1 of one another: three of the five
-- families were the same poster, measured. The colours now come from the
-- design's own namespace, which the guard migration beside this file admits.
--
-- ★ REQ-CRT-014 IS UNTOUCHED, and that is what makes this safe where a hard
-- delete was not: version 1 stays exactly where it is. A certificate issued
-- against it still renders as it, byte for byte, and its \`font_hashes\` and
-- \`recipient_name_snapshot\` are not read by this file at all. Issuance and
-- \`poster_render_context()\` resolve the LATEST version, so a new export is the
-- designed one and an old certificate is its own.
--
-- ★ IDEMPOTENT ON THE DOCUMENT, as 0193 is, and for the same measured reason: a
-- key of «(scope, purpose, family)» cannot tell a row that needs the new version
-- from one that already has it. The row carrying this exact document is the
-- honest key — jsonb equality is structural and key-order independent — so a
-- re-run inserts nothing. The version number is \`max(version) + 1\` on the row
-- rather than a literal, so the file is correct whatever the row has reached.
--
-- ★ \`main\`'S WORKER IN THE PUSH-BEFORE-MERGE WINDOW renders these documents
-- with the OLD runtime, which does not know the \`design\` namespace: \`isBinding()\`
-- returns false for \`{{design.tangerine}}\`, so \`resolveColour()\` returns the
-- moustache as a literal CSS colour and a poster exported in that window has no
-- ground and no type colour. ★★ SO THIS FILE IS PROMOTED AND PUSHED ONLY WITH
-- THE MERGE, never before it — the opposite of the wave's usual order, and the
-- reason is that it is the first seed whose documents need a runtime the old
-- code does not have. The guard migration beside it is safe to push early: it
-- only widens what an INSERT may carry.

do $$
declare
  v_template uuid;
  v_doc      jsonb;
  v_fields   jsonb;
begin
`)

for (const t of BASELINE_LIBRARY) {
  const marker = t.purpose === 'poster' ? `${t.family}@v${t.version}` : `${t.family}@${t.orientation}@v${t.version}`
  const json = JSON.stringify(t.document, null, 2)
  const fields = JSON.stringify(dynamicFieldsOf(t.document))
  if (json.includes('$json$') || fields.includes('$fields$')) throw new Error(`${marker}: a dollar-quote tag appears inside the document`)

  // ★★ IDEMPOTENT ON THE DOCUMENT, not on `(scope, purpose, family)` — and this
  // is the one thing wave 24's seed does differently from every seed before it.
  //
  // 0061 and 0098 ADDED A VERSION to an existing row, so «the live default of
  // this (purpose, family)» was exactly the row to seed into. Wave 24 REPLACES
  // the row (REQ-DSG-034), and that key cannot tell the row being replaced from
  // the row replacing it: on the first run it matches the SUPERSEDED row, finds
  // version 1 already present, inserts nothing, and the document never changes.
  // Measured, not reasoned about — `tests/rls/templates-roster.test.ts` caught
  // it: 11 templates and 19 versions, the old documents still live.
  //
  // The row carrying THIS EXACT DOCUMENT is the honest key. `jsonb` equality is
  // structural and key-order independent, the literal is declared once into
  // `v_doc` rather than written twice, and a re-run finds the row it created and
  // does nothing.
  // ★ The LIVE platform row of this composition, by its own name. After 0193 the
  // eleven names are distinct among non-retired platform rows — a poster's is its
  // family name, a certificate's its family plus its orientation — and any row
  // 0193 retired is excluded by `retired_at is null` rather than by hoping its
  // name differs.
  const seedOne = () => `v_template := null;
v_doc    := $json$${json}$json$::jsonb;
v_fields := $fields$${fields}$fields$::jsonb;

select t.id into v_template
  from public.design_templates t
 where t.scope = 'platform' and t.purpose = ${lit(t.purpose)} and t.family = ${lit(t.family)}
   and t.name = ${lit(t.name)} and t.retired_at is null
 order by t.created_at
 limit 1;

if v_template is null then
  -- Louder than a silent skip: the row this seed amends is 0193's, and if it is
  -- not there the library is not what this file was generated against.
  raise exception 'baseline row missing for % % (%)', ${lit(t.purpose)}, ${lit(t.family)}, ${lit(t.name)};
end if;

-- ADD the version unless this row already carries this exact document, which is
-- what makes a re-run a no-op. Never an UPDATE: a version is immutable
-- (REQ-DSG-007), and version 1 is what a certificate already issued renders as
-- (REQ-CRT-014).
if not exists (
  select 1 from public.design_template_versions v
   where v.template_id = v_template and v.document = v_doc
) then
  insert into public.design_template_versions (template_id, version, document, dynamic_fields, font_hashes, published_at)
  select
    v_template,
    coalesce(max(v.version), 0) + 1,
    v_doc, v_fields,
    -- No font hash is pinned on a platform version: the platform set is
    -- installed by hash in every image (REQ-DSG-016), as 0061 recorded.
    '{}',
    now()
  from public.design_template_versions v
  where v.template_id = v_template;
end if;
`

  out.push(`-- @family ${marker}`)
  out.push(seedOne())
}

out.push(`end $$;
`)

process.stdout.write(out.join('\n'))
