"use client";

import { useEffect, useMemo, useState, useTransition } from "react";
import { useTranslations } from "next-intl";
import { fontFaceCss, type BrandScheme, type DesignDocument } from "@kareem/designer-runtime";
import type { CertificateDesignData } from "@/lib/dal/certificates";
import { ChecksPanel, useCheckFindings } from "@/components/designer/checks-panel";
import { TemplatePreview } from "@/components/designer/template-preview";
import { formatNumber } from "@/components/sessions/numerals";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogClose, DialogContent } from "@/components/ui/dialog";
import { LockIcon } from "@/components/ui/icons";
import { Panel } from "@/components/ui/panel";
import { RadioGroup } from "@/components/ui/radio-group";
import { useToast } from "@/components/ui/toast";
import { applyDesignToHeld, saveCertificateDesign, type CertificateActionResult } from "@/app/[locale]/app/admin/sessions/[id]/certificates/actions";

// SCR-045's «التصميم» — REQ-DSG-031's first step, DEC-128, DEC-148, after
// `Certificate.dc.html`'s design step and `CertBuilder`'s preview.
//
// ★ THE THREE MEANINGS OF «شهادة» KEPT APART (REQ-DSG-031): this is the
// DESIGN — which composition, which colours. The MODE (whether, and whether a
// human releases) is the schedule's; the ACT is the issuance section.
//
// Chosen BEFORE completion, because automatic issuance has no human at issue
// time: `issue_certificate()` pins what is saved here. Once a certificate of a
// kind has reached a member its design is fixed — the certificate records
// what was printed (REQ-CRT-014) — and the panel says so instead of offering a
// control the database will refuse.
//
// The preview is the renderer's own output with this session's real data and
// this org's brand in the scheme being chosen; both palettes arrive together,
// so switching colours needs no round trip. It is a PREVIEW, not the artifact
// (DEC-017): the artifact is rendered by the worker's Chromium, checked by
// Tier A, and its result is on each certificate's row below.
//
// ★ THE PREFLIGHT MEASURES THE LONGEST NAME ON THE LIST, not the sample.
// A certificate's failure is the one attendee whose name does not fit, and
// a check against a short name passes exactly the case that breaks. It runs
// the studio's own checks — the safe area and auto-fit's floor and line
// limit — through the same measurer the worker calls, in this document, with
// the same faces by SHA-256 (REQ-DSG-016).

type Kind = CertificateDesignData["kinds"][number];
type Face = { family: string; weight: number; style: string; sha256: string };

export interface CertificateDesignProps {
  locale: string;
  sessionId: string;
  data: CertificateDesignData;
  /** The longest eligible name per kind, for the preflight. */
  longestName: Partial<Record<Kind["kind"], string>>;
  faces: Face[];
  origin: string;
  /** Once certificates exist the job is issuance: each kind folds to one line
   *  — what it was issued with — behind «غيّر التصميم». */
  collapsed?: boolean;
}

export function CertificateDesign({ locale, sessionId, data, longestName, faces, origin, collapsed = false }: CertificateDesignProps) {
  const fontsReady = useFacesReady(faces);
  // Generated by the runtime's own fontFaceCss() from the manifest; no user
  // input reaches it, and the family names are escaped there.
  const faceCss = useMemo(() => fontFaceCss(faces.map((f) => ({ ...f, url: `${origin}/api/fonts/${f.sha256}` }))), [faces, origin]);

  return (
    <div className="flex flex-col gap-6">
      <style dangerouslySetInnerHTML={{ __html: faceCss }} />
      {data.kinds.map((kind) => (
        <KindPanel
          key={kind.kind}
          locale={locale}
          sessionId={sessionId}
          kind={kind}
          brand={data.brand}
          sample={data.sample}
          canEdit={data.canEdit}
          longestName={longestName[kind.kind] ?? null}
          faces={faces}
          origin={origin}
          fontsReady={fontsReady}
          collapsed={collapsed}
        />
      ))}
    </div>
  );
}

function useFacesReady(faces: Face[]): boolean {
  const [ready, setReady] = useState(false);
  useEffect(() => {
    let cancelled = false;
    const families = [...new Set(faces.map((f) => f.family))];
    // `document.fonts.ready` alone resolves while a declared-but-unexercised
    // face is still unloaded (DEC-024), so each family is loaded explicitly.
    void Promise.all(families.map((family) => window.document.fonts.load(`400 40px "${family}"`)))
      .then(() => window.document.fonts.ready)
      .catch(() => undefined)
      .then(() => {
        if (!cancelled) setReady(true);
      });
    return () => {
      cancelled = true;
    };
  }, [faces]);
  return ready;
}

function KindPanel({
  locale,
  sessionId,
  kind,
  brand,
  sample,
  canEdit,
  longestName,
  faces,
  origin,
  fontsReady,
  collapsed,
}: {
  locale: string;
  sessionId: string;
  kind: Kind;
  brand: CertificateDesignData["brand"];
  sample: Record<string, string>;
  canEdit: boolean;
  longestName: string | null;
  faces: Face[];
  origin: string;
  fontsReady: boolean;
  collapsed: boolean;
}) {
  const t = useTranslations("certificates.session");
  const ui = useTranslations("ui");
  const toast = useToast();
  const [pending, start] = useTransition();
  const [templateId, setTemplateId] = useState(kind.effectiveTemplateId ?? kind.options[0]?.id ?? "");
  const [scheme, setScheme] = useState<BrandScheme>(kind.chosen?.scheme ?? "light");
  const [confirmOpen, setConfirmOpen] = useState(false);
  const [open, setOpen] = useState(!collapsed);

  const selected = kind.options.find((o) => o.id === templateId) ?? null;
  const editable = canEdit && !kind.locked;
  // Unsaved when nothing is stored yet — issuance would otherwise fall back
  // to the default in light, which is a choice nobody made.
  const dirty = kind.chosen === null || templateId !== kind.chosen.templateId || scheme !== kind.chosen.scheme;
  // The longest name on the list stands in for the recipient in the preview
  // AND the preflight: the admin approves the worst case, not the sample.
  const bindings = useMemo(
    () => ({
      ...brand[scheme],
      ...sample,
      ...(longestName ? { "recipient.name": longestName } : {}),
    }),
    [brand, scheme, sample, longestName],
  );
  const headingId = `design-${kind.kind}`;
  const bodyId = `${headingId}-body`;
  const bdi = (c: React.ReactNode) => <bdi>{c}</bdi>;

  const say = (result: CertificateActionResult, success: string) => {
    if (result.status === "ok") return toast.show({ tone: "success", title: success });
    toast.show({
      tone: "error",
      title: t(result.status === "locked" ? "locked" : result.status === "invalid" ? "invalid" : "notAuthorized"),
    });
  };

  const save = () =>
    start(async () => {
      const form = new FormData();
      form.set("templateId", templateId);
      form.set("scheme", scheme);
      say(await saveCertificateDesign(locale, sessionId, kind.kind, form), t("saved"));
    });

  const applyHeld = () =>
    start(async () => {
      const result = await applyDesignToHeld(locale, sessionId, kind.kind);
      const count = result.status === "ok" ? (result.count ?? 0) : 0;
      say(result, t("applyHeldDone", { count, value: formatNumber(count) }));
      if (result.status === "ok") setConfirmOpen(false);
    });

  return (
    <section aria-labelledby={headingId}>
      <Panel className="flex flex-col gap-4 md:p-6">
        <div className="flex flex-wrap items-center justify-between gap-2">
          <h3 id={headingId} className="text-h3 text-fg-heading">
            {t(`designKind.${kind.kind}`)}
          </h3>
          {kind.locked ? (
            <Badge size="sm" outline icon={<LockIcon />}>
              {t("lockedBadge")}
            </Badge>
          ) : kind.chosen === null && !kind.issuedWith ? (
            <Badge size="sm" outline>
              {t("notChosenBadge")}
            </Badge>
          ) : null}
        </div>

        {/* After issue, the line says what the certificates WERE issued with —
            never «no design chosen, so the default» over certificates that
            already exist. */}
        {kind.issuedWith ? (
          <p className="text-body-sm text-fg-body">
            {t.rich(kind.locked ? "issuedWithLocked" : "issuedWithHeld", {
              name: kind.issuedWith.templateName,
              scheme: t(`scheme.${kind.issuedWith.scheme}`),
              bdi,
            })}
          </p>
        ) : kind.locked ? (
          <p className="text-body-sm text-fg-muted">{t("locked")}</p>
        ) : kind.chosen === null ? (
          <p className="text-body-sm text-fg-muted">{t("notChosen")}</p>
        ) : collapsed && selected ? (
          <p className="text-body-sm text-fg-body">{t.rich("summary", { name: selected.name, scheme: t(`scheme.${scheme}`), bdi })}</p>
        ) : null}

        {collapsed ? (
          <Button type="button" variant="ghost" size="sm" className="self-start" aria-expanded={open} aria-controls={bodyId} onClick={() => setOpen((v) => !v)}>
            {open ? t("hideDesign") : editable ? t("changeDesign") : t("showDesign")}
          </Button>
        ) : null}

        {!open ? null : kind.options.length === 0 ? (
          <p id={bodyId} className="text-body-sm text-fg-muted">
            {t("noTemplates")}
          </p>
        ) : (
          <div id={bodyId} className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_minmax(0,1fr)]">
            <div className="flex min-w-0 flex-col gap-5">
              <RadioGroup
                name={`template-${kind.kind}`}
                legend={t("templateLegend")}
                value={templateId}
                onChange={editable ? setTemplateId : undefined}
                options={kind.options.map((o) => ({
                  value: o.id,
                  disabled: !editable,
                  label: (
                    <span className="flex flex-wrap items-center gap-1.5">
                      <bdi>{o.name}</bdi>
                      {o.name.endsWith(t(`orientation.${o.orientation}`)) ? null : (
                        <Badge size="sm" outline>
                          {t(`orientation.${o.orientation}`)}
                        </Badge>
                      )}
                    </span>
                  ),
                  hint: o.scope === "platform" ? t("platformTemplate") : t("orgTemplate"),
                }))}
              />
              <RadioGroup
                name={`scheme-${kind.kind}`}
                legend={t("schemeLegend")}
                value={scheme}
                onChange={editable ? (v) => setScheme(v === "dark" ? "dark" : "light") : undefined}
                options={(["light", "dark"] as const).map((value) => ({
                  value,
                  label: t(`scheme.${value}`),
                  disabled: !editable,
                }))}
              />
              {editable ? (
                <div className="flex flex-wrap gap-2">
                  <Button type="button" size="md" pending={pending} pendingLabel={t("saving")} disabled={!dirty || selected === null} onClick={save}>
                    {t("save")}
                  </Button>
                  {kind.heldCount > 0 && kind.chosen !== null && !dirty ? (
                    <Button type="button" variant="secondary" size="md" disabled={pending} onClick={() => setConfirmOpen(true)}>
                      {t("applyHeld")}
                    </Button>
                  ) : null}
                </div>
              ) : null}
            </div>

            {selected ? (
              <div className="flex min-w-0 flex-col gap-4">
                <figure className="flex flex-col gap-2">
                  <div
                    className={`relative w-full overflow-hidden rounded-card border border-edge ${selected.orientation === "portrait" ? "mx-auto aspect-[210/297] max-w-80" : "aspect-[297/210]"}`}
                  >
                    <TemplatePreview document={selected.document} bindings={bindings} faces={faces} origin={origin} title={t("previewTitle")} />
                  </div>
                  <figcaption className="text-caption text-fg-muted">{t("previewCaption")}</figcaption>
                </figure>
                <Preflight document={selected.document} bindings={bindings} longestName={longestName} fontsReady={fontsReady} />
              </div>
            ) : null}
          </div>
        )}

        {/* REQ-UIX-013: the confirm says what changes and what does not. The
          confirm button is a plain button, never a `DialogClose` around a
          pending transition (the real-build timeout `takedown-button.tsx`
          records). */}
        <Dialog open={confirmOpen} onOpenChange={setConfirmOpen}>
          <DialogContent
            title={t("applyHeldTitle", {
              count: kind.heldCount,
              value: formatNumber(kind.heldCount),
            })}
            description={t("applyHeldBody")}
            closeLabel={ui("dialog.close")}
          >
            <div className="flex flex-wrap gap-3">
              <Button type="button" size="md" pending={pending} onClick={applyHeld}>
                {t("applyHeldConfirm")}
              </Button>
              <DialogClose asChild>
                <Button type="button" variant="secondary" size="md" disabled={pending}>
                  {t("cancel")}
                </Button>
              </DialogClose>
            </div>
          </DialogContent>
        </Dialog>
      </Panel>
    </section>
  );
}

function Preflight({
  document: doc,
  bindings,
  longestName,
  fontsReady,
}: {
  document: DesignDocument;
  bindings: Record<string, string>;
  longestName: string | null;
  fontsReady: boolean;
}) {
  const t = useTranslations("certificates.session");
  const { findings, measuring } = useCheckFindings({
    document: doc,
    bindings,
    fontsReady,
    assetSizes: {},
  });
  const layerNames = useMemo(() => Object.fromEntries(doc.layers.map((l) => [l.id, l.name ?? l.id])), [doc.layers]);

  return (
    <Panel tone={measuring ? "neutral" : findings.length ? "error" : "success"}>
      <div className="flex flex-col gap-2">
        <h4 className="text-label text-fg-heading">{t("preflightHeading")}</h4>
        <p className="text-body-sm text-fg-body">
          {longestName
            ? t.rich("preflightLongest", {
                name: longestName,
                bdi: (c) => <bdi>{c}</bdi>,
              })
            : t("preflightSample")}
        </p>
        <ChecksPanel findings={findings} measuring={measuring} layerNames={layerNames} showIntro={false} />
        <p className="text-caption text-fg-muted">{t("preflightWorker")}</p>
      </div>
    </Panel>
  );
}
