-- designer (wave 8) — the certificate library and the completed poster roster.
-- Follows the template guard (designer/0001) and 0061_baseline_library.
--
-- Serves:  REQ-DSG-026 (the seeded roster, counted), REQ-DSG-007 (versions,
--          never edits), REQ-DSG-008 (platform templates), REQ-DSG-021
--          (tokens only), REQ-DSG-024 (locked regions), REQ-CRT-010
-- Cites:   DEC-125 (posters dark), DEC-127 (the gradient), DEC-128 (the
--          certificate library), DEC-148 (a row is a composition; q4)
--
-- 03 §8.2 ROWS: none. No policy and no grant — rows into two tables 0055
-- already policied, as the owner during migration.
--
-- GENERATED by packages/designer-runtime/scripts/seed-sql.mjs from
-- packages/designer-runtime/src/library.ts. Do not edit by hand:
-- tests/unit/designer-library.test.ts deep-equals every document below
-- against the library.
--
-- WHAT IT DOES, per DEC-148's ruling that a baseline row is a COMPOSITION
-- (eleven platform templates; the scheme is never a row):
--   · the five poster families gain VERSION 2 — DEC-127's gradient, the
--     Knowledge Network rule on {{brand.edgeStrong}} (q4), and date and
--     venue lines tall enough for one line at their own size;
--   · the three landscape certificates gain VERSION 2 — every line frame at
--     least one line tall — and are renamed «… أفقية»;
--   · three PORTRAIT certificates are created, «… عمودية», version 1,
--     is_default = false (one platform default per family, 0055's index).
--
-- WHAT IT DOES NOT DO: re-render anything. A live poster takes version 2 at
-- its next regeneration; an org's own copy never receives it (REQ-DSG-008);
-- an issued certificate stays on its pinned version.

do $$
declare
  v_template uuid;
begin

-- @family talk@v2
v_template := null;
select t.id into v_template from public.design_templates t
 where t.scope = 'platform' and t.purpose = 'poster' and t.family = 'talk' and t.is_default
 limit 1;

if v_template is null then
  insert into public.design_templates (org_id, scope, purpose, family, name, is_default)
  values (null, 'platform', 'poster', 'talk', 'جلسة', true)
  returning id into v_template;
end if;

if not exists (select 1 from public.design_template_versions v where v.template_id = v_template and v.version = 2) then
  insert into public.design_template_versions (template_id, version, document, dynamic_fields, font_hashes, published_at)
  values (
    v_template, 2,
    $json${
  "schemaVersion": 1,
  "purpose": "poster",
  "master": {
    "width": 1080,
    "height": 1350,
    "unit": "px",
    "dpi": 72
  },
  "direction": "rtl",
  "background": {
    "type": "gradient",
    "angle": 140,
    "stops": [
      {
        "color": "{{brand.surface}}"
      },
      {
        "color": "{{brand.canvasRaise}}"
      }
    ]
  },
  "layers": [
    {
      "id": "l_logo",
      "kind": "image",
      "name": "شعار المؤسسة",
      "image": {
        "binding": "brand.logoAssetId",
        "fit": "contain"
      },
      "frame": {
        "x": 80,
        "y": 80,
        "w": 160,
        "h": 160
      },
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_kicker",
      "kind": "text",
      "name": "نوع الجلسة",
      "frame": {
        "x": 80,
        "y": 280,
        "w": 920,
        "h": 60
      },
      "text": {
        "literal": "جلسة"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 40,
        "lineHeight": 1.4,
        "weight": 500
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_title",
      "kind": "text",
      "name": "عنوان الجلسة",
      "frame": {
        "x": 80,
        "y": 360,
        "w": 920,
        "h": 330
      },
      "text": {
        "binding": "session.title",
        "fallback": "عنوان الجلسة"
      },
      "font": {
        "family": "Reem Kufi",
        "size": 96,
        "minSize": 56,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 600
      },
      "color": "{{brand.fgHeading}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 3
      },
      "z": 10
    },
    {
      "id": "l_rule",
      "kind": "shape",
      "name": "خط الشبكة",
      "frame": {
        "x": 80,
        "y": 720,
        "w": 920,
        "h": 2
      },
      "shape": {
        "type": "rect",
        "fill": "{{brand.edgeStrong}}"
      },
      "z": 2
    },
    {
      "id": "l_rule-node-1",
      "kind": "shape",
      "name": "عقدة الشبكة",
      "frame": {
        "x": 115,
        "y": 716,
        "w": 10,
        "h": 10
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{brand.node}}"
      },
      "z": 3
    },
    {
      "id": "l_rule-node-2",
      "kind": "shape",
      "name": "عقدة الشبكة",
      "frame": {
        "x": 535,
        "y": 716,
        "w": 10,
        "h": 10
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{brand.node}}"
      },
      "z": 3
    },
    {
      "id": "l_rule-node-3",
      "kind": "shape",
      "name": "عقدة الشبكة",
      "frame": {
        "x": 955,
        "y": 716,
        "w": 10,
        "h": 10
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{brand.node}}"
      },
      "z": 3
    },
    {
      "id": "l_presenters",
      "kind": "dynamic_field",
      "name": "المقدِّمون",
      "frame": {
        "x": 80,
        "y": 770,
        "w": 920,
        "h": 80
      },
      "field": {
        "binding": "session.presenters",
        "fallback": "اسم المقدِّم"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 44,
        "minSize": 32,
        "lineHeight": 1.7,
        "weight": 500
      },
      "color": "{{brand.fgBody}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_when",
      "kind": "dynamic_field",
      "name": "الموعد",
      "frame": {
        "x": 80,
        "y": 870,
        "w": 920,
        "h": 70
      },
      "field": {
        "binding": "session.startsAt",
        "fallback": "التاريخ والوقت"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 40,
        "lineHeight": 1.7
      },
      "color": "{{brand.fgBody}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_where",
      "kind": "dynamic_field",
      "name": "المكان",
      "frame": {
        "x": 80,
        "y": 945,
        "w": 760,
        "h": 70
      },
      "field": {
        "binding": "session.venueName",
        "fallback": "المكان"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 40,
        "lineHeight": 1.7
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "hideAt": [
        "og"
      ],
      "z": 10
    },
    {
      "id": "l_qr",
      "kind": "qr",
      "name": "رمز الجلسة",
      "locked": true,
      "frame": {
        "x": 80,
        "y": 1130,
        "w": 140,
        "h": 140
      },
      "qr": {
        "binding": "session.eventUrl",
        "ecLevel": "M",
        "quietZoneModules": 4
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 10
    }
  ]
}$json$::jsonb,
    $fields$["brand.logoAssetId","session.title","session.presenters","session.startsAt","session.venueName","session.eventUrl"]$fields$::jsonb,
    -- No font hash is pinned on a platform version: the platform set is
    -- installed by hash in every image (REQ-DSG-016), as 0061 recorded.
    '{}',
    now()
  );
end if;

-- @family workshop@v2
v_template := null;
select t.id into v_template from public.design_templates t
 where t.scope = 'platform' and t.purpose = 'poster' and t.family = 'workshop' and t.is_default
 limit 1;

if v_template is null then
  insert into public.design_templates (org_id, scope, purpose, family, name, is_default)
  values (null, 'platform', 'poster', 'workshop', 'ورشة', true)
  returning id into v_template;
end if;

if not exists (select 1 from public.design_template_versions v where v.template_id = v_template and v.version = 2) then
  insert into public.design_template_versions (template_id, version, document, dynamic_fields, font_hashes, published_at)
  values (
    v_template, 2,
    $json${
  "schemaVersion": 1,
  "purpose": "poster",
  "master": {
    "width": 1080,
    "height": 1350,
    "unit": "px",
    "dpi": 72
  },
  "direction": "rtl",
  "background": {
    "type": "gradient",
    "angle": 140,
    "stops": [
      {
        "color": "{{brand.surface}}"
      },
      {
        "color": "{{brand.canvasRaise}}"
      }
    ]
  },
  "layers": [
    {
      "id": "l_logo",
      "kind": "image",
      "name": "شعار المؤسسة",
      "image": {
        "binding": "brand.logoAssetId",
        "fit": "contain"
      },
      "frame": {
        "x": 80,
        "y": 80,
        "w": 160,
        "h": 160
      },
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_kicker",
      "kind": "text",
      "name": "نوع الجلسة",
      "frame": {
        "x": 80,
        "y": 280,
        "w": 920,
        "h": 60
      },
      "text": {
        "literal": "ورشة"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 40,
        "lineHeight": 1.4,
        "weight": 500
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_title",
      "kind": "text",
      "name": "عنوان الجلسة",
      "frame": {
        "x": 80,
        "y": 360,
        "w": 920,
        "h": 330
      },
      "text": {
        "binding": "session.title",
        "fallback": "عنوان الجلسة"
      },
      "font": {
        "family": "Reem Kufi",
        "size": 96,
        "minSize": 56,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 600
      },
      "color": "{{brand.fgHeading}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 3
      },
      "z": 10
    },
    {
      "id": "l_rule",
      "kind": "shape",
      "name": "خط الشبكة",
      "frame": {
        "x": 80,
        "y": 720,
        "w": 920,
        "h": 2
      },
      "shape": {
        "type": "rect",
        "fill": "{{brand.edgeStrong}}"
      },
      "z": 2
    },
    {
      "id": "l_rule-node-1",
      "kind": "shape",
      "name": "عقدة الشبكة",
      "frame": {
        "x": 115,
        "y": 716,
        "w": 10,
        "h": 10
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{brand.node}}"
      },
      "z": 3
    },
    {
      "id": "l_rule-node-2",
      "kind": "shape",
      "name": "عقدة الشبكة",
      "frame": {
        "x": 535,
        "y": 716,
        "w": 10,
        "h": 10
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{brand.node}}"
      },
      "z": 3
    },
    {
      "id": "l_rule-node-3",
      "kind": "shape",
      "name": "عقدة الشبكة",
      "frame": {
        "x": 955,
        "y": 716,
        "w": 10,
        "h": 10
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{brand.node}}"
      },
      "z": 3
    },
    {
      "id": "l_presenters",
      "kind": "dynamic_field",
      "name": "المقدِّمون",
      "frame": {
        "x": 80,
        "y": 770,
        "w": 920,
        "h": 80
      },
      "field": {
        "binding": "session.presenters",
        "fallback": "اسم المقدِّم"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 44,
        "minSize": 32,
        "lineHeight": 1.7,
        "weight": 500
      },
      "color": "{{brand.fgBody}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_when",
      "kind": "dynamic_field",
      "name": "الموعد",
      "frame": {
        "x": 80,
        "y": 870,
        "w": 920,
        "h": 70
      },
      "field": {
        "binding": "session.startsAt",
        "fallback": "التاريخ والوقت"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 40,
        "lineHeight": 1.7
      },
      "color": "{{brand.fgBody}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_where",
      "kind": "dynamic_field",
      "name": "المكان",
      "frame": {
        "x": 80,
        "y": 945,
        "w": 760,
        "h": 70
      },
      "field": {
        "binding": "session.venueName",
        "fallback": "المكان"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 40,
        "lineHeight": 1.7
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "hideAt": [
        "og"
      ],
      "z": 10
    },
    {
      "id": "l_qr",
      "kind": "qr",
      "name": "رمز الجلسة",
      "locked": true,
      "frame": {
        "x": 80,
        "y": 1130,
        "w": 140,
        "h": 140
      },
      "qr": {
        "binding": "session.eventUrl",
        "ecLevel": "M",
        "quietZoneModules": 4
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 10
    },
    {
      "id": "l_tasks",
      "kind": "text",
      "name": "المهام التحضيرية",
      "frame": {
        "x": 260,
        "y": 1130,
        "w": 740,
        "h": 140
      },
      "text": {
        "literal": "لهذه الورشة مهام تحضيرية — راجعها قبل الحضور."
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 34,
        "minSize": 26,
        "lineHeight": 1.7
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 3
      },
      "hideAt": [
        "og",
        "square"
      ],
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "proportional"
        }
      },
      "z": 10
    }
  ]
}$json$::jsonb,
    $fields$["brand.logoAssetId","session.title","session.presenters","session.startsAt","session.venueName","session.eventUrl"]$fields$::jsonb,
    -- No font hash is pinned on a platform version: the platform set is
    -- installed by hash in every image (REQ-DSG-016), as 0061 recorded.
    '{}',
    now()
  );
end if;

-- @family panel@v2
v_template := null;
select t.id into v_template from public.design_templates t
 where t.scope = 'platform' and t.purpose = 'poster' and t.family = 'panel' and t.is_default
 limit 1;

if v_template is null then
  insert into public.design_templates (org_id, scope, purpose, family, name, is_default)
  values (null, 'platform', 'poster', 'panel', 'حوار', true)
  returning id into v_template;
end if;

if not exists (select 1 from public.design_template_versions v where v.template_id = v_template and v.version = 2) then
  insert into public.design_template_versions (template_id, version, document, dynamic_fields, font_hashes, published_at)
  values (
    v_template, 2,
    $json${
  "schemaVersion": 1,
  "purpose": "poster",
  "master": {
    "width": 1080,
    "height": 1350,
    "unit": "px",
    "dpi": 72
  },
  "direction": "rtl",
  "background": {
    "type": "gradient",
    "angle": 140,
    "stops": [
      {
        "color": "{{brand.surface}}"
      },
      {
        "color": "{{brand.canvasRaise}}"
      }
    ]
  },
  "layers": [
    {
      "id": "l_logo",
      "kind": "image",
      "name": "شعار المؤسسة",
      "image": {
        "binding": "brand.logoAssetId",
        "fit": "contain"
      },
      "frame": {
        "x": 80,
        "y": 80,
        "w": 160,
        "h": 160
      },
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_kicker",
      "kind": "text",
      "name": "نوع الجلسة",
      "frame": {
        "x": 80,
        "y": 280,
        "w": 920,
        "h": 60
      },
      "text": {
        "literal": "حوار"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 40,
        "lineHeight": 1.4,
        "weight": 500
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_title",
      "kind": "text",
      "name": "عنوان الجلسة",
      "frame": {
        "x": 80,
        "y": 360,
        "w": 920,
        "h": 330
      },
      "text": {
        "binding": "session.title",
        "fallback": "عنوان الجلسة"
      },
      "font": {
        "family": "Reem Kufi",
        "size": 96,
        "minSize": 56,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 600
      },
      "color": "{{brand.fgHeading}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 3
      },
      "z": 10
    },
    {
      "id": "l_rule",
      "kind": "shape",
      "name": "خط الشبكة",
      "frame": {
        "x": 80,
        "y": 720,
        "w": 920,
        "h": 2
      },
      "shape": {
        "type": "rect",
        "fill": "{{brand.edgeStrong}}"
      },
      "z": 2
    },
    {
      "id": "l_rule-node-1",
      "kind": "shape",
      "name": "عقدة الشبكة",
      "frame": {
        "x": 115,
        "y": 716,
        "w": 10,
        "h": 10
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{brand.node}}"
      },
      "z": 3
    },
    {
      "id": "l_rule-node-2",
      "kind": "shape",
      "name": "عقدة الشبكة",
      "frame": {
        "x": 535,
        "y": 716,
        "w": 10,
        "h": 10
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{brand.node}}"
      },
      "z": 3
    },
    {
      "id": "l_rule-node-3",
      "kind": "shape",
      "name": "عقدة الشبكة",
      "frame": {
        "x": 955,
        "y": 716,
        "w": 10,
        "h": 10
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{brand.node}}"
      },
      "z": 3
    },
    {
      "id": "l_presenters",
      "kind": "dynamic_field",
      "name": "المقدِّمون",
      "frame": {
        "x": 80,
        "y": 770,
        "w": 920,
        "h": 160
      },
      "field": {
        "binding": "session.presenters",
        "fallback": "اسم المقدِّم"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 44,
        "minSize": 32,
        "lineHeight": 1.7,
        "weight": 500
      },
      "color": "{{brand.fgBody}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_when",
      "kind": "dynamic_field",
      "name": "الموعد",
      "frame": {
        "x": 80,
        "y": 870,
        "w": 920,
        "h": 70
      },
      "field": {
        "binding": "session.startsAt",
        "fallback": "التاريخ والوقت"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 40,
        "lineHeight": 1.7
      },
      "color": "{{brand.fgBody}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_where",
      "kind": "dynamic_field",
      "name": "المكان",
      "frame": {
        "x": 80,
        "y": 945,
        "w": 760,
        "h": 70
      },
      "field": {
        "binding": "session.venueName",
        "fallback": "المكان"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 40,
        "lineHeight": 1.7
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "hideAt": [
        "og"
      ],
      "z": 10
    },
    {
      "id": "l_qr",
      "kind": "qr",
      "name": "رمز الجلسة",
      "locked": true,
      "frame": {
        "x": 80,
        "y": 1130,
        "w": 140,
        "h": 140
      },
      "qr": {
        "binding": "session.eventUrl",
        "ecLevel": "M",
        "quietZoneModules": 4
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 10
    }
  ]
}$json$::jsonb,
    $fields$["brand.logoAssetId","session.title","session.presenters","session.startsAt","session.venueName","session.eventUrl"]$fields$::jsonb,
    -- No font hash is pinned on a platform version: the platform set is
    -- installed by hash in every image (REQ-DSG-016), as 0061 recorded.
    '{}',
    now()
  );
end if;

-- @family meetup@v2
v_template := null;
select t.id into v_template from public.design_templates t
 where t.scope = 'platform' and t.purpose = 'poster' and t.family = 'meetup' and t.is_default
 limit 1;

if v_template is null then
  insert into public.design_templates (org_id, scope, purpose, family, name, is_default)
  values (null, 'platform', 'poster', 'meetup', 'لقاء', true)
  returning id into v_template;
end if;

if not exists (select 1 from public.design_template_versions v where v.template_id = v_template and v.version = 2) then
  insert into public.design_template_versions (template_id, version, document, dynamic_fields, font_hashes, published_at)
  values (
    v_template, 2,
    $json${
  "schemaVersion": 1,
  "purpose": "poster",
  "master": {
    "width": 1080,
    "height": 1350,
    "unit": "px",
    "dpi": 72
  },
  "direction": "rtl",
  "background": {
    "type": "gradient",
    "angle": 140,
    "stops": [
      {
        "color": "{{brand.surface}}"
      },
      {
        "color": "{{brand.canvasRaise}}"
      }
    ]
  },
  "layers": [
    {
      "id": "l_logo",
      "kind": "image",
      "name": "شعار المؤسسة",
      "image": {
        "binding": "brand.logoAssetId",
        "fit": "contain"
      },
      "frame": {
        "x": 80,
        "y": 80,
        "w": 160,
        "h": 160
      },
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_kicker",
      "kind": "text",
      "name": "نوع الجلسة",
      "frame": {
        "x": 80,
        "y": 280,
        "w": 920,
        "h": 60
      },
      "text": {
        "literal": "لقاء"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 40,
        "lineHeight": 1.4,
        "weight": 500
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_title",
      "kind": "text",
      "name": "عنوان الجلسة",
      "frame": {
        "x": 80,
        "y": 360,
        "w": 920,
        "h": 330
      },
      "text": {
        "binding": "session.title",
        "fallback": "عنوان الجلسة"
      },
      "font": {
        "family": "Reem Kufi",
        "size": 96,
        "minSize": 56,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 600
      },
      "color": "{{brand.fgHeading}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 3
      },
      "z": 10
    },
    {
      "id": "l_rule",
      "kind": "shape",
      "name": "خط الشبكة",
      "frame": {
        "x": 80,
        "y": 720,
        "w": 920,
        "h": 2
      },
      "shape": {
        "type": "rect",
        "fill": "{{brand.edgeStrong}}"
      },
      "z": 2
    },
    {
      "id": "l_rule-node-1",
      "kind": "shape",
      "name": "عقدة الشبكة",
      "frame": {
        "x": 115,
        "y": 716,
        "w": 10,
        "h": 10
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{brand.node}}"
      },
      "z": 3
    },
    {
      "id": "l_rule-node-2",
      "kind": "shape",
      "name": "عقدة الشبكة",
      "frame": {
        "x": 535,
        "y": 716,
        "w": 10,
        "h": 10
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{brand.node}}"
      },
      "z": 3
    },
    {
      "id": "l_rule-node-3",
      "kind": "shape",
      "name": "عقدة الشبكة",
      "frame": {
        "x": 955,
        "y": 716,
        "w": 10,
        "h": 10
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{brand.node}}"
      },
      "z": 3
    },
    {
      "id": "l_presenters",
      "kind": "dynamic_field",
      "name": "المقدِّمون",
      "frame": {
        "x": 80,
        "y": 770,
        "w": 920,
        "h": 80
      },
      "field": {
        "binding": "session.presenters",
        "fallback": "اسم المقدِّم"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 44,
        "minSize": 32,
        "lineHeight": 1.7,
        "weight": 500
      },
      "color": "{{brand.fgBody}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_when",
      "kind": "dynamic_field",
      "name": "الموعد",
      "frame": {
        "x": 80,
        "y": 870,
        "w": 920,
        "h": 70
      },
      "field": {
        "binding": "session.startsAt",
        "fallback": "التاريخ والوقت"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 40,
        "lineHeight": 1.7
      },
      "color": "{{brand.fgBody}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_where",
      "kind": "dynamic_field",
      "name": "المكان",
      "frame": {
        "x": 80,
        "y": 945,
        "w": 760,
        "h": 70
      },
      "field": {
        "binding": "session.venueName",
        "fallback": "المكان"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 40,
        "lineHeight": 1.7
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "hideAt": [
        "og"
      ],
      "z": 10
    },
    {
      "id": "l_qr",
      "kind": "qr",
      "name": "رمز الجلسة",
      "locked": true,
      "frame": {
        "x": 80,
        "y": 1130,
        "w": 140,
        "h": 140
      },
      "qr": {
        "binding": "session.eventUrl",
        "ecLevel": "M",
        "quietZoneModules": 4
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 10
    }
  ]
}$json$::jsonb,
    $fields$["brand.logoAssetId","session.title","session.presenters","session.startsAt","session.venueName","session.eventUrl"]$fields$::jsonb,
    -- No font hash is pinned on a platform version: the platform set is
    -- installed by hash in every image (REQ-DSG-016), as 0061 recorded.
    '{}',
    now()
  );
end if;

-- @family announcement@v2
v_template := null;
select t.id into v_template from public.design_templates t
 where t.scope = 'platform' and t.purpose = 'poster' and t.family = 'announcement' and t.is_default
 limit 1;

if v_template is null then
  insert into public.design_templates (org_id, scope, purpose, family, name, is_default)
  values (null, 'platform', 'poster', 'announcement', 'إعلان', true)
  returning id into v_template;
end if;

if not exists (select 1 from public.design_template_versions v where v.template_id = v_template and v.version = 2) then
  insert into public.design_template_versions (template_id, version, document, dynamic_fields, font_hashes, published_at)
  values (
    v_template, 2,
    $json${
  "schemaVersion": 1,
  "purpose": "poster",
  "master": {
    "width": 1080,
    "height": 1350,
    "unit": "px",
    "dpi": 72
  },
  "direction": "rtl",
  "background": {
    "type": "gradient",
    "angle": 140,
    "stops": [
      {
        "color": "{{brand.surface}}"
      },
      {
        "color": "{{brand.canvasRaise}}"
      }
    ]
  },
  "layers": [
    {
      "id": "l_logo",
      "kind": "image",
      "name": "شعار المؤسسة",
      "image": {
        "binding": "brand.logoAssetId",
        "fit": "contain"
      },
      "frame": {
        "x": 80,
        "y": 80,
        "w": 160,
        "h": 160
      },
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_kicker",
      "kind": "text",
      "name": "نوع الجلسة",
      "frame": {
        "x": 80,
        "y": 280,
        "w": 920,
        "h": 60
      },
      "text": {
        "literal": "إعلان"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 40,
        "lineHeight": 1.4,
        "weight": 500
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_title",
      "kind": "text",
      "name": "عنوان الجلسة",
      "frame": {
        "x": 80,
        "y": 360,
        "w": 920,
        "h": 330
      },
      "text": {
        "binding": "session.title",
        "fallback": "عنوان الجلسة"
      },
      "font": {
        "family": "Reem Kufi",
        "size": 96,
        "minSize": 56,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 600
      },
      "color": "{{brand.fgHeading}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 3
      },
      "z": 10
    },
    {
      "id": "l_rule",
      "kind": "shape",
      "name": "خط الشبكة",
      "frame": {
        "x": 80,
        "y": 720,
        "w": 920,
        "h": 2
      },
      "shape": {
        "type": "rect",
        "fill": "{{brand.edgeStrong}}"
      },
      "z": 2
    },
    {
      "id": "l_rule-node-1",
      "kind": "shape",
      "name": "عقدة الشبكة",
      "frame": {
        "x": 115,
        "y": 716,
        "w": 10,
        "h": 10
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{brand.node}}"
      },
      "z": 3
    },
    {
      "id": "l_rule-node-2",
      "kind": "shape",
      "name": "عقدة الشبكة",
      "frame": {
        "x": 535,
        "y": 716,
        "w": 10,
        "h": 10
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{brand.node}}"
      },
      "z": 3
    },
    {
      "id": "l_rule-node-3",
      "kind": "shape",
      "name": "عقدة الشبكة",
      "frame": {
        "x": 955,
        "y": 716,
        "w": 10,
        "h": 10
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{brand.node}}"
      },
      "z": 3
    },
    {
      "id": "l_presenters",
      "kind": "dynamic_field",
      "name": "المقدِّمون",
      "frame": {
        "x": 80,
        "y": 770,
        "w": 920,
        "h": 80
      },
      "field": {
        "binding": "session.presenters",
        "fallback": "اسم المقدِّم"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 44,
        "minSize": 32,
        "lineHeight": 1.7,
        "weight": 500
      },
      "color": "{{brand.fgBody}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_when",
      "kind": "dynamic_field",
      "name": "الموعد",
      "frame": {
        "x": 80,
        "y": 870,
        "w": 920,
        "h": 70
      },
      "field": {
        "binding": "session.startsAt",
        "fallback": "التاريخ والوقت"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 40,
        "lineHeight": 1.7
      },
      "color": "{{brand.fgBody}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_where",
      "kind": "dynamic_field",
      "name": "المكان",
      "frame": {
        "x": 80,
        "y": 945,
        "w": 760,
        "h": 70
      },
      "field": {
        "binding": "session.venueName",
        "fallback": "المكان"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 40,
        "lineHeight": 1.7
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "hideAt": [
        "og"
      ],
      "z": 10
    },
    {
      "id": "l_qr",
      "kind": "qr",
      "name": "رمز الجلسة",
      "locked": true,
      "frame": {
        "x": 80,
        "y": 1130,
        "w": 140,
        "h": 140
      },
      "qr": {
        "binding": "session.eventUrl",
        "ecLevel": "M",
        "quietZoneModules": 4
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 10
    }
  ]
}$json$::jsonb,
    $fields$["brand.logoAssetId","session.title","session.presenters","session.startsAt","session.venueName","session.eventUrl"]$fields$::jsonb,
    -- No font hash is pinned on a platform version: the platform set is
    -- installed by hash in every image (REQ-DSG-016), as 0061 recorded.
    '{}',
    now()
  );
end if;

-- @family attendance@landscape@v2
v_template := null;
select t.id into v_template from public.design_templates t
 where t.scope = 'platform' and t.purpose = 'certificate' and t.family = 'attendance' and t.is_default
 limit 1;

if v_template is null then
  insert into public.design_templates (org_id, scope, purpose, family, name, is_default)
  values (null, 'platform', 'certificate', 'attendance', 'شهادة حضور أفقية', true)
  returning id into v_template;
end if;

-- The landscape composition's name says so now that a portrait one exists.
update public.design_templates set name = 'شهادة حضور أفقية'
 where id = v_template and name = 'شهادة حضور';

if not exists (select 1 from public.design_template_versions v where v.template_id = v_template and v.version = 2) then
  insert into public.design_template_versions (template_id, version, document, dynamic_fields, font_hashes, published_at)
  values (
    v_template, 2,
    $json${
  "schemaVersion": 1,
  "purpose": "certificate",
  "master": {
    "width": 3508,
    "height": 2480,
    "unit": "px",
    "dpi": 300
  },
  "direction": "rtl",
  "background": {
    "type": "solid",
    "color": "{{brand.canvas}}"
  },
  "layers": [
    {
      "id": "l_logo",
      "kind": "image",
      "name": "شعار المؤسسة",
      "image": {
        "binding": "brand.logoAssetId",
        "fit": "contain"
      },
      "frame": {
        "x": 1644,
        "y": 240,
        "w": 220,
        "h": 220
      },
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_org",
      "kind": "dynamic_field",
      "name": "اسم المؤسسة",
      "frame": {
        "x": 300,
        "y": 500,
        "w": 2908,
        "h": 80
      },
      "field": {
        "binding": "org.name",
        "fallback": "اسم المؤسسة"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.4,
        "weight": 500
      },
      "color": "{{brand.fgMuted}}",
      "align": "center",
      "z": 10
    },
    {
      "id": "l_kind",
      "kind": "text",
      "name": "نوع الشهادة",
      "frame": {
        "x": 300,
        "y": 620,
        "w": 2908,
        "h": 180
      },
      "text": {
        "literal": "شهادة حضور"
      },
      "font": {
        "family": "Amiri",
        "size": 128,
        "minSize": 88,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 600
      },
      "color": "{{brand.fgHeading}}",
      "align": "center",
      "z": 10
    },
    {
      "id": "l_rule",
      "kind": "shape",
      "name": "خط الشبكة",
      "frame": {
        "x": 300,
        "y": 830,
        "w": 2908,
        "h": 2
      },
      "shape": {
        "type": "rect",
        "fill": "{{brand.spine}}"
      },
      "z": 2
    },
    {
      "id": "l_rule-node-1",
      "kind": "shape",
      "name": "عقدة الشبكة",
      "frame": {
        "x": 335,
        "y": 826,
        "w": 10,
        "h": 10
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{brand.node}}"
      },
      "z": 3
    },
    {
      "id": "l_rule-node-2",
      "kind": "shape",
      "name": "عقدة الشبكة",
      "frame": {
        "x": 1749,
        "y": 826,
        "w": 10,
        "h": 10
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{brand.node}}"
      },
      "z": 3
    },
    {
      "id": "l_rule-node-3",
      "kind": "shape",
      "name": "عقدة الشبكة",
      "frame": {
        "x": 3163,
        "y": 826,
        "w": 10,
        "h": 10
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{brand.node}}"
      },
      "z": 3
    },
    {
      "id": "l_recipient",
      "kind": "dynamic_field",
      "name": "اسم المستفيد",
      "frame": {
        "x": 300,
        "y": 920,
        "w": 2908,
        "h": 220
      },
      "field": {
        "binding": "recipient.name",
        "fallback": "اسم المستفيد"
      },
      "font": {
        "family": "Amiri",
        "size": 150,
        "minSize": 90,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 600
      },
      "color": "{{brand.fgHeading}}",
      "align": "center",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_reason",
      "kind": "dynamic_field",
      "name": "عن الجلسة",
      "frame": {
        "x": 300,
        "y": 1180,
        "w": 2908,
        "h": 220
      },
      "field": {
        "binding": "session.title",
        "fallback": "عنوان الجلسة"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 64,
        "minSize": 44,
        "lineHeight": 1.7
      },
      "color": "{{brand.fgBody}}",
      "align": "center",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_issued",
      "kind": "dynamic_field",
      "name": "تاريخ الإصدار",
      "frame": {
        "x": 300,
        "y": 1420,
        "w": 2908,
        "h": 82
      },
      "field": {
        "binding": "certificate.issuedAt",
        "fallback": "تاريخ الإصدار"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 48,
        "lineHeight": 1.7
      },
      "color": "{{brand.fgMuted}}",
      "align": "center",
      "z": 10
    },
    {
      "id": "l_qr",
      "kind": "qr",
      "name": "رمز التحقّق",
      "locked": true,
      "frame": {
        "x": 300,
        "y": 1860,
        "w": 320,
        "h": 320
      },
      "qr": {
        "binding": "certificate.verifyUrl",
        "ecLevel": "Q",
        "quietZoneModules": 4
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_serial",
      "kind": "dynamic_field",
      "name": "الرقم التسلسلي",
      "locked": true,
      "frame": {
        "x": 660,
        "y": 1880,
        "w": 900,
        "h": 75
      },
      "field": {
        "binding": "certificate.serial",
        "fallback": "الرقم التسلسلي"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 44,
        "lineHeight": 1.7
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_code",
      "kind": "dynamic_field",
      "name": "رمز التحقّق النصّي",
      "locked": true,
      "frame": {
        "x": 660,
        "y": 1965,
        "w": 900,
        "h": 75
      },
      "field": {
        "binding": "certificate.verificationCode",
        "fallback": "رمز التحقّق"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 44,
        "lineHeight": 1.7
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_signature",
      "kind": "shape",
      "name": "موضع التوقيع",
      "locked": true,
      "frame": {
        "x": 2608,
        "y": 2000,
        "w": 600,
        "h": 2
      },
      "shape": {
        "type": "rect",
        "fill": "{{brand.edgeStrong}}"
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    }
  ]
}$json$::jsonb,
    $fields$["brand.logoAssetId","org.name","recipient.name","session.title","certificate.issuedAt","certificate.verifyUrl","certificate.serial","certificate.verificationCode"]$fields$::jsonb,
    -- No font hash is pinned on a platform version: the platform set is
    -- installed by hash in every image (REQ-DSG-016), as 0061 recorded.
    '{}',
    now()
  );
end if;

-- @family attendance@portrait@v1
v_template := null;
select t.id into v_template from public.design_templates t
 where t.scope = 'platform' and t.purpose = 'certificate' and t.family = 'attendance' and not t.is_default
   and exists (select 1 from public.design_template_versions v
                where v.template_id = t.id
                  and (v.document->'master'->>'width')::int < (v.document->'master'->>'height')::int)
 order by t.created_at
 limit 1;

if v_template is null then
  insert into public.design_templates (org_id, scope, purpose, family, name, is_default)
  values (null, 'platform', 'certificate', 'attendance', 'شهادة حضور عمودية', false)
  returning id into v_template;
end if;

if not exists (select 1 from public.design_template_versions v where v.template_id = v_template and v.version = 1) then
  insert into public.design_template_versions (template_id, version, document, dynamic_fields, font_hashes, published_at)
  values (
    v_template, 1,
    $json${
  "schemaVersion": 1,
  "purpose": "certificate",
  "master": {
    "width": 2480,
    "height": 3508,
    "unit": "px",
    "dpi": 300
  },
  "direction": "rtl",
  "background": {
    "type": "solid",
    "color": "{{brand.canvas}}"
  },
  "layers": [
    {
      "id": "l_logo",
      "kind": "image",
      "name": "شعار المؤسسة",
      "image": {
        "binding": "brand.logoAssetId",
        "fit": "contain"
      },
      "frame": {
        "x": 1130,
        "y": 300,
        "w": 220,
        "h": 220
      },
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_org",
      "kind": "dynamic_field",
      "name": "اسم المؤسسة",
      "frame": {
        "x": 240,
        "y": 580,
        "w": 2000,
        "h": 80
      },
      "field": {
        "binding": "org.name",
        "fallback": "اسم المؤسسة"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.4,
        "weight": 500
      },
      "color": "{{brand.fgMuted}}",
      "align": "center",
      "z": 10
    },
    {
      "id": "l_kind",
      "kind": "text",
      "name": "نوع الشهادة",
      "frame": {
        "x": 240,
        "y": 700,
        "w": 2000,
        "h": 180
      },
      "text": {
        "literal": "شهادة حضور"
      },
      "font": {
        "family": "Amiri",
        "size": 128,
        "minSize": 88,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 600
      },
      "color": "{{brand.fgHeading}}",
      "align": "center",
      "z": 10
    },
    {
      "id": "l_rule",
      "kind": "shape",
      "name": "خط الشبكة",
      "frame": {
        "x": 240,
        "y": 930,
        "w": 2000,
        "h": 2
      },
      "shape": {
        "type": "rect",
        "fill": "{{brand.spine}}"
      },
      "z": 2
    },
    {
      "id": "l_rule-node-1",
      "kind": "shape",
      "name": "عقدة الشبكة",
      "frame": {
        "x": 275,
        "y": 926,
        "w": 10,
        "h": 10
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{brand.node}}"
      },
      "z": 3
    },
    {
      "id": "l_rule-node-2",
      "kind": "shape",
      "name": "عقدة الشبكة",
      "frame": {
        "x": 1235,
        "y": 926,
        "w": 10,
        "h": 10
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{brand.node}}"
      },
      "z": 3
    },
    {
      "id": "l_rule-node-3",
      "kind": "shape",
      "name": "عقدة الشبكة",
      "frame": {
        "x": 2195,
        "y": 926,
        "w": 10,
        "h": 10
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{brand.node}}"
      },
      "z": 3
    },
    {
      "id": "l_recipient",
      "kind": "dynamic_field",
      "name": "اسم المستفيد",
      "frame": {
        "x": 240,
        "y": 1040,
        "w": 2000,
        "h": 440
      },
      "field": {
        "binding": "recipient.name",
        "fallback": "اسم المستفيد"
      },
      "font": {
        "family": "Amiri",
        "size": 150,
        "minSize": 90,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 600
      },
      "color": "{{brand.fgHeading}}",
      "align": "center",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_reason",
      "kind": "dynamic_field",
      "name": "عن الجلسة",
      "frame": {
        "x": 240,
        "y": 1540,
        "w": 2000,
        "h": 230
      },
      "field": {
        "binding": "session.title",
        "fallback": "عنوان الجلسة"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 64,
        "minSize": 44,
        "lineHeight": 1.7
      },
      "color": "{{brand.fgBody}}",
      "align": "center",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_issued",
      "kind": "dynamic_field",
      "name": "تاريخ الإصدار",
      "frame": {
        "x": 240,
        "y": 1820,
        "w": 2000,
        "h": 82
      },
      "field": {
        "binding": "certificate.issuedAt",
        "fallback": "تاريخ الإصدار"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 48,
        "lineHeight": 1.7
      },
      "color": "{{brand.fgMuted}}",
      "align": "center",
      "z": 10
    },
    {
      "id": "l_qr",
      "kind": "qr",
      "name": "رمز التحقّق",
      "locked": true,
      "frame": {
        "x": 240,
        "y": 2600,
        "w": 320,
        "h": 320
      },
      "qr": {
        "binding": "certificate.verifyUrl",
        "ecLevel": "Q",
        "quietZoneModules": 4
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_serial",
      "kind": "dynamic_field",
      "name": "الرقم التسلسلي",
      "locked": true,
      "frame": {
        "x": 600,
        "y": 2620,
        "w": 1000,
        "h": 75
      },
      "field": {
        "binding": "certificate.serial",
        "fallback": "الرقم التسلسلي"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 44,
        "lineHeight": 1.7
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_code",
      "kind": "dynamic_field",
      "name": "رمز التحقّق النصّي",
      "locked": true,
      "frame": {
        "x": 600,
        "y": 2705,
        "w": 1000,
        "h": 75
      },
      "field": {
        "binding": "certificate.verificationCode",
        "fallback": "رمز التحقّق"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 44,
        "lineHeight": 1.7
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_signature",
      "kind": "shape",
      "name": "موضع التوقيع",
      "locked": true,
      "frame": {
        "x": 1640,
        "y": 2860,
        "w": 600,
        "h": 2
      },
      "shape": {
        "type": "rect",
        "fill": "{{brand.edgeStrong}}"
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    }
  ]
}$json$::jsonb,
    $fields$["brand.logoAssetId","org.name","recipient.name","session.title","certificate.issuedAt","certificate.verifyUrl","certificate.serial","certificate.verificationCode"]$fields$::jsonb,
    -- No font hash is pinned on a platform version: the platform set is
    -- installed by hash in every image (REQ-DSG-016), as 0061 recorded.
    '{}',
    now()
  );
end if;

-- @family presenter@landscape@v2
v_template := null;
select t.id into v_template from public.design_templates t
 where t.scope = 'platform' and t.purpose = 'certificate' and t.family = 'presenter' and t.is_default
 limit 1;

if v_template is null then
  insert into public.design_templates (org_id, scope, purpose, family, name, is_default)
  values (null, 'platform', 'certificate', 'presenter', 'شهادة تقديم أفقية', true)
  returning id into v_template;
end if;

-- The landscape composition's name says so now that a portrait one exists.
update public.design_templates set name = 'شهادة تقديم أفقية'
 where id = v_template and name = 'شهادة تقديم';

if not exists (select 1 from public.design_template_versions v where v.template_id = v_template and v.version = 2) then
  insert into public.design_template_versions (template_id, version, document, dynamic_fields, font_hashes, published_at)
  values (
    v_template, 2,
    $json${
  "schemaVersion": 1,
  "purpose": "certificate",
  "master": {
    "width": 3508,
    "height": 2480,
    "unit": "px",
    "dpi": 300
  },
  "direction": "rtl",
  "background": {
    "type": "solid",
    "color": "{{brand.canvas}}"
  },
  "layers": [
    {
      "id": "l_logo",
      "kind": "image",
      "name": "شعار المؤسسة",
      "image": {
        "binding": "brand.logoAssetId",
        "fit": "contain"
      },
      "frame": {
        "x": 1644,
        "y": 240,
        "w": 220,
        "h": 220
      },
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_org",
      "kind": "dynamic_field",
      "name": "اسم المؤسسة",
      "frame": {
        "x": 300,
        "y": 500,
        "w": 2908,
        "h": 80
      },
      "field": {
        "binding": "org.name",
        "fallback": "اسم المؤسسة"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.4,
        "weight": 500
      },
      "color": "{{brand.fgMuted}}",
      "align": "center",
      "z": 10
    },
    {
      "id": "l_kind",
      "kind": "text",
      "name": "نوع الشهادة",
      "frame": {
        "x": 300,
        "y": 620,
        "w": 2908,
        "h": 180
      },
      "text": {
        "literal": "شهادة تقديم"
      },
      "font": {
        "family": "Amiri",
        "size": 128,
        "minSize": 88,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 600
      },
      "color": "{{brand.fgHeading}}",
      "align": "center",
      "z": 10
    },
    {
      "id": "l_rule",
      "kind": "shape",
      "name": "خط الشبكة",
      "frame": {
        "x": 300,
        "y": 830,
        "w": 2908,
        "h": 2
      },
      "shape": {
        "type": "rect",
        "fill": "{{brand.spine}}"
      },
      "z": 2
    },
    {
      "id": "l_rule-node-1",
      "kind": "shape",
      "name": "عقدة الشبكة",
      "frame": {
        "x": 335,
        "y": 826,
        "w": 10,
        "h": 10
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{brand.node}}"
      },
      "z": 3
    },
    {
      "id": "l_rule-node-2",
      "kind": "shape",
      "name": "عقدة الشبكة",
      "frame": {
        "x": 1749,
        "y": 826,
        "w": 10,
        "h": 10
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{brand.node}}"
      },
      "z": 3
    },
    {
      "id": "l_rule-node-3",
      "kind": "shape",
      "name": "عقدة الشبكة",
      "frame": {
        "x": 3163,
        "y": 826,
        "w": 10,
        "h": 10
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{brand.node}}"
      },
      "z": 3
    },
    {
      "id": "l_recipient",
      "kind": "dynamic_field",
      "name": "اسم المستفيد",
      "frame": {
        "x": 300,
        "y": 920,
        "w": 2908,
        "h": 220
      },
      "field": {
        "binding": "recipient.name",
        "fallback": "اسم المستفيد"
      },
      "font": {
        "family": "Amiri",
        "size": 150,
        "minSize": 90,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 600
      },
      "color": "{{brand.fgHeading}}",
      "align": "center",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_reason",
      "kind": "dynamic_field",
      "name": "عن الجلسة",
      "frame": {
        "x": 300,
        "y": 1180,
        "w": 2908,
        "h": 220
      },
      "field": {
        "binding": "session.title",
        "fallback": "عنوان الجلسة"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 64,
        "minSize": 44,
        "lineHeight": 1.7
      },
      "color": "{{brand.fgBody}}",
      "align": "center",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_issued",
      "kind": "dynamic_field",
      "name": "تاريخ الإصدار",
      "frame": {
        "x": 300,
        "y": 1420,
        "w": 2908,
        "h": 82
      },
      "field": {
        "binding": "certificate.issuedAt",
        "fallback": "تاريخ الإصدار"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 48,
        "lineHeight": 1.7
      },
      "color": "{{brand.fgMuted}}",
      "align": "center",
      "z": 10
    },
    {
      "id": "l_qr",
      "kind": "qr",
      "name": "رمز التحقّق",
      "locked": true,
      "frame": {
        "x": 300,
        "y": 1860,
        "w": 320,
        "h": 320
      },
      "qr": {
        "binding": "certificate.verifyUrl",
        "ecLevel": "Q",
        "quietZoneModules": 4
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_serial",
      "kind": "dynamic_field",
      "name": "الرقم التسلسلي",
      "locked": true,
      "frame": {
        "x": 660,
        "y": 1880,
        "w": 900,
        "h": 75
      },
      "field": {
        "binding": "certificate.serial",
        "fallback": "الرقم التسلسلي"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 44,
        "lineHeight": 1.7
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_code",
      "kind": "dynamic_field",
      "name": "رمز التحقّق النصّي",
      "locked": true,
      "frame": {
        "x": 660,
        "y": 1965,
        "w": 900,
        "h": 75
      },
      "field": {
        "binding": "certificate.verificationCode",
        "fallback": "رمز التحقّق"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 44,
        "lineHeight": 1.7
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_signature",
      "kind": "shape",
      "name": "موضع التوقيع",
      "locked": true,
      "frame": {
        "x": 2608,
        "y": 2000,
        "w": 600,
        "h": 2
      },
      "shape": {
        "type": "rect",
        "fill": "{{brand.edgeStrong}}"
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    }
  ]
}$json$::jsonb,
    $fields$["brand.logoAssetId","org.name","recipient.name","session.title","certificate.issuedAt","certificate.verifyUrl","certificate.serial","certificate.verificationCode"]$fields$::jsonb,
    -- No font hash is pinned on a platform version: the platform set is
    -- installed by hash in every image (REQ-DSG-016), as 0061 recorded.
    '{}',
    now()
  );
end if;

-- @family presenter@portrait@v1
v_template := null;
select t.id into v_template from public.design_templates t
 where t.scope = 'platform' and t.purpose = 'certificate' and t.family = 'presenter' and not t.is_default
   and exists (select 1 from public.design_template_versions v
                where v.template_id = t.id
                  and (v.document->'master'->>'width')::int < (v.document->'master'->>'height')::int)
 order by t.created_at
 limit 1;

if v_template is null then
  insert into public.design_templates (org_id, scope, purpose, family, name, is_default)
  values (null, 'platform', 'certificate', 'presenter', 'شهادة تقديم عمودية', false)
  returning id into v_template;
end if;

if not exists (select 1 from public.design_template_versions v where v.template_id = v_template and v.version = 1) then
  insert into public.design_template_versions (template_id, version, document, dynamic_fields, font_hashes, published_at)
  values (
    v_template, 1,
    $json${
  "schemaVersion": 1,
  "purpose": "certificate",
  "master": {
    "width": 2480,
    "height": 3508,
    "unit": "px",
    "dpi": 300
  },
  "direction": "rtl",
  "background": {
    "type": "solid",
    "color": "{{brand.canvas}}"
  },
  "layers": [
    {
      "id": "l_logo",
      "kind": "image",
      "name": "شعار المؤسسة",
      "image": {
        "binding": "brand.logoAssetId",
        "fit": "contain"
      },
      "frame": {
        "x": 1130,
        "y": 300,
        "w": 220,
        "h": 220
      },
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_org",
      "kind": "dynamic_field",
      "name": "اسم المؤسسة",
      "frame": {
        "x": 240,
        "y": 580,
        "w": 2000,
        "h": 80
      },
      "field": {
        "binding": "org.name",
        "fallback": "اسم المؤسسة"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.4,
        "weight": 500
      },
      "color": "{{brand.fgMuted}}",
      "align": "center",
      "z": 10
    },
    {
      "id": "l_kind",
      "kind": "text",
      "name": "نوع الشهادة",
      "frame": {
        "x": 240,
        "y": 700,
        "w": 2000,
        "h": 180
      },
      "text": {
        "literal": "شهادة تقديم"
      },
      "font": {
        "family": "Amiri",
        "size": 128,
        "minSize": 88,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 600
      },
      "color": "{{brand.fgHeading}}",
      "align": "center",
      "z": 10
    },
    {
      "id": "l_rule",
      "kind": "shape",
      "name": "خط الشبكة",
      "frame": {
        "x": 240,
        "y": 930,
        "w": 2000,
        "h": 2
      },
      "shape": {
        "type": "rect",
        "fill": "{{brand.spine}}"
      },
      "z": 2
    },
    {
      "id": "l_rule-node-1",
      "kind": "shape",
      "name": "عقدة الشبكة",
      "frame": {
        "x": 275,
        "y": 926,
        "w": 10,
        "h": 10
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{brand.node}}"
      },
      "z": 3
    },
    {
      "id": "l_rule-node-2",
      "kind": "shape",
      "name": "عقدة الشبكة",
      "frame": {
        "x": 1235,
        "y": 926,
        "w": 10,
        "h": 10
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{brand.node}}"
      },
      "z": 3
    },
    {
      "id": "l_rule-node-3",
      "kind": "shape",
      "name": "عقدة الشبكة",
      "frame": {
        "x": 2195,
        "y": 926,
        "w": 10,
        "h": 10
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{brand.node}}"
      },
      "z": 3
    },
    {
      "id": "l_recipient",
      "kind": "dynamic_field",
      "name": "اسم المستفيد",
      "frame": {
        "x": 240,
        "y": 1040,
        "w": 2000,
        "h": 440
      },
      "field": {
        "binding": "recipient.name",
        "fallback": "اسم المستفيد"
      },
      "font": {
        "family": "Amiri",
        "size": 150,
        "minSize": 90,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 600
      },
      "color": "{{brand.fgHeading}}",
      "align": "center",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_reason",
      "kind": "dynamic_field",
      "name": "عن الجلسة",
      "frame": {
        "x": 240,
        "y": 1540,
        "w": 2000,
        "h": 230
      },
      "field": {
        "binding": "session.title",
        "fallback": "عنوان الجلسة"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 64,
        "minSize": 44,
        "lineHeight": 1.7
      },
      "color": "{{brand.fgBody}}",
      "align": "center",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_issued",
      "kind": "dynamic_field",
      "name": "تاريخ الإصدار",
      "frame": {
        "x": 240,
        "y": 1820,
        "w": 2000,
        "h": 82
      },
      "field": {
        "binding": "certificate.issuedAt",
        "fallback": "تاريخ الإصدار"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 48,
        "lineHeight": 1.7
      },
      "color": "{{brand.fgMuted}}",
      "align": "center",
      "z": 10
    },
    {
      "id": "l_qr",
      "kind": "qr",
      "name": "رمز التحقّق",
      "locked": true,
      "frame": {
        "x": 240,
        "y": 2600,
        "w": 320,
        "h": 320
      },
      "qr": {
        "binding": "certificate.verifyUrl",
        "ecLevel": "Q",
        "quietZoneModules": 4
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_serial",
      "kind": "dynamic_field",
      "name": "الرقم التسلسلي",
      "locked": true,
      "frame": {
        "x": 600,
        "y": 2620,
        "w": 1000,
        "h": 75
      },
      "field": {
        "binding": "certificate.serial",
        "fallback": "الرقم التسلسلي"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 44,
        "lineHeight": 1.7
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_code",
      "kind": "dynamic_field",
      "name": "رمز التحقّق النصّي",
      "locked": true,
      "frame": {
        "x": 600,
        "y": 2705,
        "w": 1000,
        "h": 75
      },
      "field": {
        "binding": "certificate.verificationCode",
        "fallback": "رمز التحقّق"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 44,
        "lineHeight": 1.7
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_signature",
      "kind": "shape",
      "name": "موضع التوقيع",
      "locked": true,
      "frame": {
        "x": 1640,
        "y": 2860,
        "w": 600,
        "h": 2
      },
      "shape": {
        "type": "rect",
        "fill": "{{brand.edgeStrong}}"
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    }
  ]
}$json$::jsonb,
    $fields$["brand.logoAssetId","org.name","recipient.name","session.title","certificate.issuedAt","certificate.verifyUrl","certificate.serial","certificate.verificationCode"]$fields$::jsonb,
    -- No font hash is pinned on a platform version: the platform set is
    -- installed by hash in every image (REQ-DSG-016), as 0061 recorded.
    '{}',
    now()
  );
end if;

-- @family achievement@landscape@v2
v_template := null;
select t.id into v_template from public.design_templates t
 where t.scope = 'platform' and t.purpose = 'certificate' and t.family = 'achievement' and t.is_default
 limit 1;

if v_template is null then
  insert into public.design_templates (org_id, scope, purpose, family, name, is_default)
  values (null, 'platform', 'certificate', 'achievement', 'شهادة إنجاز أفقية', true)
  returning id into v_template;
end if;

-- The landscape composition's name says so now that a portrait one exists.
update public.design_templates set name = 'شهادة إنجاز أفقية'
 where id = v_template and name = 'شهادة إنجاز';

if not exists (select 1 from public.design_template_versions v where v.template_id = v_template and v.version = 2) then
  insert into public.design_template_versions (template_id, version, document, dynamic_fields, font_hashes, published_at)
  values (
    v_template, 2,
    $json${
  "schemaVersion": 1,
  "purpose": "certificate",
  "master": {
    "width": 3508,
    "height": 2480,
    "unit": "px",
    "dpi": 300
  },
  "direction": "rtl",
  "background": {
    "type": "solid",
    "color": "{{brand.canvas}}"
  },
  "layers": [
    {
      "id": "l_logo",
      "kind": "image",
      "name": "شعار المؤسسة",
      "image": {
        "binding": "brand.logoAssetId",
        "fit": "contain"
      },
      "frame": {
        "x": 1644,
        "y": 240,
        "w": 220,
        "h": 220
      },
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_org",
      "kind": "dynamic_field",
      "name": "اسم المؤسسة",
      "frame": {
        "x": 300,
        "y": 500,
        "w": 2908,
        "h": 80
      },
      "field": {
        "binding": "org.name",
        "fallback": "اسم المؤسسة"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.4,
        "weight": 500
      },
      "color": "{{brand.fgMuted}}",
      "align": "center",
      "z": 10
    },
    {
      "id": "l_kind",
      "kind": "text",
      "name": "نوع الشهادة",
      "frame": {
        "x": 300,
        "y": 620,
        "w": 2908,
        "h": 180
      },
      "text": {
        "literal": "شهادة إنجاز"
      },
      "font": {
        "family": "Amiri",
        "size": 128,
        "minSize": 88,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 600
      },
      "color": "{{brand.fgHeading}}",
      "align": "center",
      "z": 10
    },
    {
      "id": "l_rule",
      "kind": "shape",
      "name": "خط الشبكة",
      "frame": {
        "x": 300,
        "y": 830,
        "w": 2908,
        "h": 2
      },
      "shape": {
        "type": "rect",
        "fill": "{{brand.spine}}"
      },
      "z": 2
    },
    {
      "id": "l_rule-node-1",
      "kind": "shape",
      "name": "عقدة الشبكة",
      "frame": {
        "x": 335,
        "y": 826,
        "w": 10,
        "h": 10
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{brand.node}}"
      },
      "z": 3
    },
    {
      "id": "l_rule-node-2",
      "kind": "shape",
      "name": "عقدة الشبكة",
      "frame": {
        "x": 1749,
        "y": 826,
        "w": 10,
        "h": 10
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{brand.node}}"
      },
      "z": 3
    },
    {
      "id": "l_rule-node-3",
      "kind": "shape",
      "name": "عقدة الشبكة",
      "frame": {
        "x": 3163,
        "y": 826,
        "w": 10,
        "h": 10
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{brand.node}}"
      },
      "z": 3
    },
    {
      "id": "l_recipient",
      "kind": "dynamic_field",
      "name": "اسم المستفيد",
      "frame": {
        "x": 300,
        "y": 920,
        "w": 2908,
        "h": 220
      },
      "field": {
        "binding": "recipient.name",
        "fallback": "اسم المستفيد"
      },
      "font": {
        "family": "Amiri",
        "size": 150,
        "minSize": 90,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 600
      },
      "color": "{{brand.fgHeading}}",
      "align": "center",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_reason",
      "kind": "dynamic_field",
      "name": "عن الجلسة",
      "frame": {
        "x": 300,
        "y": 1180,
        "w": 2908,
        "h": 220
      },
      "field": {
        "binding": "certificate.achievementName",
        "fallback": "اسم الإنجاز"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 64,
        "minSize": 44,
        "lineHeight": 1.7
      },
      "color": "{{brand.fgBody}}",
      "align": "center",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_issued",
      "kind": "dynamic_field",
      "name": "تاريخ الإصدار",
      "frame": {
        "x": 300,
        "y": 1420,
        "w": 2908,
        "h": 82
      },
      "field": {
        "binding": "certificate.issuedAt",
        "fallback": "تاريخ الإصدار"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 48,
        "lineHeight": 1.7
      },
      "color": "{{brand.fgMuted}}",
      "align": "center",
      "z": 10
    },
    {
      "id": "l_qr",
      "kind": "qr",
      "name": "رمز التحقّق",
      "locked": true,
      "frame": {
        "x": 300,
        "y": 1860,
        "w": 320,
        "h": 320
      },
      "qr": {
        "binding": "certificate.verifyUrl",
        "ecLevel": "Q",
        "quietZoneModules": 4
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_serial",
      "kind": "dynamic_field",
      "name": "الرقم التسلسلي",
      "locked": true,
      "frame": {
        "x": 660,
        "y": 1880,
        "w": 900,
        "h": 75
      },
      "field": {
        "binding": "certificate.serial",
        "fallback": "الرقم التسلسلي"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 44,
        "lineHeight": 1.7
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_code",
      "kind": "dynamic_field",
      "name": "رمز التحقّق النصّي",
      "locked": true,
      "frame": {
        "x": 660,
        "y": 1965,
        "w": 900,
        "h": 75
      },
      "field": {
        "binding": "certificate.verificationCode",
        "fallback": "رمز التحقّق"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 44,
        "lineHeight": 1.7
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_signature",
      "kind": "shape",
      "name": "موضع التوقيع",
      "locked": true,
      "frame": {
        "x": 2608,
        "y": 2000,
        "w": 600,
        "h": 2
      },
      "shape": {
        "type": "rect",
        "fill": "{{brand.edgeStrong}}"
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    }
  ]
}$json$::jsonb,
    $fields$["brand.logoAssetId","org.name","recipient.name","certificate.achievementName","certificate.issuedAt","certificate.verifyUrl","certificate.serial","certificate.verificationCode"]$fields$::jsonb,
    -- No font hash is pinned on a platform version: the platform set is
    -- installed by hash in every image (REQ-DSG-016), as 0061 recorded.
    '{}',
    now()
  );
end if;

-- @family achievement@portrait@v1
v_template := null;
select t.id into v_template from public.design_templates t
 where t.scope = 'platform' and t.purpose = 'certificate' and t.family = 'achievement' and not t.is_default
   and exists (select 1 from public.design_template_versions v
                where v.template_id = t.id
                  and (v.document->'master'->>'width')::int < (v.document->'master'->>'height')::int)
 order by t.created_at
 limit 1;

if v_template is null then
  insert into public.design_templates (org_id, scope, purpose, family, name, is_default)
  values (null, 'platform', 'certificate', 'achievement', 'شهادة إنجاز عمودية', false)
  returning id into v_template;
end if;

if not exists (select 1 from public.design_template_versions v where v.template_id = v_template and v.version = 1) then
  insert into public.design_template_versions (template_id, version, document, dynamic_fields, font_hashes, published_at)
  values (
    v_template, 1,
    $json${
  "schemaVersion": 1,
  "purpose": "certificate",
  "master": {
    "width": 2480,
    "height": 3508,
    "unit": "px",
    "dpi": 300
  },
  "direction": "rtl",
  "background": {
    "type": "solid",
    "color": "{{brand.canvas}}"
  },
  "layers": [
    {
      "id": "l_logo",
      "kind": "image",
      "name": "شعار المؤسسة",
      "image": {
        "binding": "brand.logoAssetId",
        "fit": "contain"
      },
      "frame": {
        "x": 1130,
        "y": 300,
        "w": 220,
        "h": 220
      },
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_org",
      "kind": "dynamic_field",
      "name": "اسم المؤسسة",
      "frame": {
        "x": 240,
        "y": 580,
        "w": 2000,
        "h": 80
      },
      "field": {
        "binding": "org.name",
        "fallback": "اسم المؤسسة"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.4,
        "weight": 500
      },
      "color": "{{brand.fgMuted}}",
      "align": "center",
      "z": 10
    },
    {
      "id": "l_kind",
      "kind": "text",
      "name": "نوع الشهادة",
      "frame": {
        "x": 240,
        "y": 700,
        "w": 2000,
        "h": 180
      },
      "text": {
        "literal": "شهادة إنجاز"
      },
      "font": {
        "family": "Amiri",
        "size": 128,
        "minSize": 88,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 600
      },
      "color": "{{brand.fgHeading}}",
      "align": "center",
      "z": 10
    },
    {
      "id": "l_rule",
      "kind": "shape",
      "name": "خط الشبكة",
      "frame": {
        "x": 240,
        "y": 930,
        "w": 2000,
        "h": 2
      },
      "shape": {
        "type": "rect",
        "fill": "{{brand.spine}}"
      },
      "z": 2
    },
    {
      "id": "l_rule-node-1",
      "kind": "shape",
      "name": "عقدة الشبكة",
      "frame": {
        "x": 275,
        "y": 926,
        "w": 10,
        "h": 10
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{brand.node}}"
      },
      "z": 3
    },
    {
      "id": "l_rule-node-2",
      "kind": "shape",
      "name": "عقدة الشبكة",
      "frame": {
        "x": 1235,
        "y": 926,
        "w": 10,
        "h": 10
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{brand.node}}"
      },
      "z": 3
    },
    {
      "id": "l_rule-node-3",
      "kind": "shape",
      "name": "عقدة الشبكة",
      "frame": {
        "x": 2195,
        "y": 926,
        "w": 10,
        "h": 10
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{brand.node}}"
      },
      "z": 3
    },
    {
      "id": "l_recipient",
      "kind": "dynamic_field",
      "name": "اسم المستفيد",
      "frame": {
        "x": 240,
        "y": 1040,
        "w": 2000,
        "h": 440
      },
      "field": {
        "binding": "recipient.name",
        "fallback": "اسم المستفيد"
      },
      "font": {
        "family": "Amiri",
        "size": 150,
        "minSize": 90,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 600
      },
      "color": "{{brand.fgHeading}}",
      "align": "center",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_reason",
      "kind": "dynamic_field",
      "name": "عن الجلسة",
      "frame": {
        "x": 240,
        "y": 1540,
        "w": 2000,
        "h": 230
      },
      "field": {
        "binding": "certificate.achievementName",
        "fallback": "اسم الإنجاز"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 64,
        "minSize": 44,
        "lineHeight": 1.7
      },
      "color": "{{brand.fgBody}}",
      "align": "center",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_issued",
      "kind": "dynamic_field",
      "name": "تاريخ الإصدار",
      "frame": {
        "x": 240,
        "y": 1820,
        "w": 2000,
        "h": 82
      },
      "field": {
        "binding": "certificate.issuedAt",
        "fallback": "تاريخ الإصدار"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 48,
        "lineHeight": 1.7
      },
      "color": "{{brand.fgMuted}}",
      "align": "center",
      "z": 10
    },
    {
      "id": "l_qr",
      "kind": "qr",
      "name": "رمز التحقّق",
      "locked": true,
      "frame": {
        "x": 240,
        "y": 2600,
        "w": 320,
        "h": 320
      },
      "qr": {
        "binding": "certificate.verifyUrl",
        "ecLevel": "Q",
        "quietZoneModules": 4
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_serial",
      "kind": "dynamic_field",
      "name": "الرقم التسلسلي",
      "locked": true,
      "frame": {
        "x": 600,
        "y": 2620,
        "w": 1000,
        "h": 75
      },
      "field": {
        "binding": "certificate.serial",
        "fallback": "الرقم التسلسلي"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 44,
        "lineHeight": 1.7
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_code",
      "kind": "dynamic_field",
      "name": "رمز التحقّق النصّي",
      "locked": true,
      "frame": {
        "x": 600,
        "y": 2705,
        "w": 1000,
        "h": 75
      },
      "field": {
        "binding": "certificate.verificationCode",
        "fallback": "رمز التحقّق"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 44,
        "lineHeight": 1.7
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_signature",
      "kind": "shape",
      "name": "موضع التوقيع",
      "locked": true,
      "frame": {
        "x": 1640,
        "y": 2860,
        "w": 600,
        "h": 2
      },
      "shape": {
        "type": "rect",
        "fill": "{{brand.edgeStrong}}"
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    }
  ]
}$json$::jsonb,
    $fields$["brand.logoAssetId","org.name","recipient.name","certificate.achievementName","certificate.issuedAt","certificate.verifyUrl","certificate.serial","certificate.verificationCode"]$fields$::jsonb,
    -- No font hash is pinned on a platform version: the platform set is
    -- installed by hash in every image (REQ-DSG-016), as 0061 recorded.
    '{}',
    now()
  );
end if;

end $$;
