-- designer (wave 24, the RE-COLOUR) — the baseline library's documents rebuilt
-- to what the artboards actually draw, as VERSION 2 of the eleven rows the
-- wave's first seed created. Follows 0193 and the guard that admits `design.*`.
--
-- Serves:  REQ-DSG-033 (the designed poster families), REQ-CRT-016 (the
--          designed certificate families), REQ-DSG-021 (bound colours only),
--          REQ-DSG-007 and REQ-CRT-014 (a version is ADDED, never edited),
--          REQ-DSG-026 (the roster, still five and three)
-- Cites:   DEC-242 §1 and §2 as the re-colour amends them
--
-- 03 §8.2 ROWS: none. This file inserts one version per existing platform row,
-- into two tables 0055 already policied, as the owner during migration. It
-- creates no policy, no grant and no function.
--
-- GENERATED by packages/designer-runtime/scripts/seed-sql.mjs from
-- packages/designer-runtime/src/library.ts. Do not edit by hand:
-- tests/unit/designer-library.test.ts parses every $json$…$json$ back out and
-- deep-equals it against the library.
--
-- ★★ A VERSION, NOT A ROW — and this is the one thing it does differently from
-- the seed before it. 0193 created eleven NEW rows because REQ-DSG-034 required
-- M6's baseline to LEAVE the library: there was something to remove, and it was
-- removed. Here there is not. The eleven rows are the right rows, with the
-- right families and the right names, carrying the wrong document — because
-- DEC-242 §1 declared «there is no artboard for a poster» and
-- AdminDesignerElements.dc.html is one. So nothing is superseded, deleted or
-- retired by this file, and `supersede_baseline_template()` is not called.
--
-- ★ WHY THE DOCUMENT CHANGED AGAIN. The artboard draws the poster at 640 × 360
-- on `#FF9A2E` with `#0B0C12` type; its <title> is «ساحة اللعب — لون الفريق»,
-- which is the NAME of the first card in the library artboard — the two files
-- were always one specification. The shipped documents instead took five brand
-- tokens as grounds, three of which (`canvas`, `surface`, `canvasRaise`)
-- resolve within 1.10:1, 1.22:1 and 1.11:1 of one another: three of the five
-- families were the same poster, measured. The colours now come from the
-- design's own namespace, which the guard migration beside this file admits.
--
-- ★ REQ-CRT-014 IS UNTOUCHED, and that is what makes this safe where a hard
-- delete was not: version 1 stays exactly where it is. A certificate issued
-- against it still renders as it, byte for byte, and its `font_hashes` and
-- `recipient_name_snapshot` are not read by this file at all. Issuance and
-- `poster_render_context()` resolve the LATEST version, so a new export is the
-- designed one and an old certificate is its own.
--
-- ★ IDEMPOTENT ON THE DOCUMENT, as 0193 is, and for the same measured reason: a
-- key of «(scope, purpose, family)» cannot tell a row that needs the new version
-- from one that already has it. The row carrying this exact document is the
-- honest key — jsonb equality is structural and key-order independent — so a
-- re-run inserts nothing. The version number is `max(version) + 1` on the row
-- rather than a literal, so the file is correct whatever the row has reached.
--
-- ★ `main`'S WORKER IN THE PUSH-BEFORE-MERGE WINDOW renders these documents
-- with the OLD runtime, which does not know the `design` namespace: `isBinding()`
-- returns false for `{{design.tangerine}}`, so `resolveColour()` returns the
-- moustache as a literal CSS colour and a poster exported in that window has no
-- ground and no type colour. ★★ SO THIS FILE IS PROMOTED AND PUSHED ONLY WITH
-- THE MERGE, never before it — the opposite of the wave's usual order, and the
-- reason is that it is the first seed whose documents need a runtime the old
-- code does not have. The guard migration beside it is safe to push early: it
-- only widens what an INSERT may carry.

do $$
declare
  v_template uuid;
  v_doc      jsonb;
  v_fields   jsonb;
begin

-- @family talk@v2
v_template := null;
v_doc    := $json${
  "schemaVersion": 1,
  "purpose": "poster",
  "master": {
    "width": 1080,
    "height": 1350,
    "unit": "px",
    "dpi": 72
  },
  "direction": "rtl",
  "background": {
    "type": "solid",
    "color": "{{design.tangerine}}"
  },
  "layers": [
    {
      "id": "l_logo",
      "kind": "image",
      "name": "شعار المؤسسة",
      "image": {
        "binding": "brand.logoAssetId",
        "fit": "contain"
      },
      "frame": {
        "x": 880,
        "y": 80,
        "w": 120,
        "h": 120
      },
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "name": "خلفية التصنيف",
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 2,
      "id": "l_pill_start",
      "kind": "shape",
      "frame": {
        "x": 80,
        "y": 80,
        "w": 72,
        "h": 72
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{design.ink}}"
      }
    },
    {
      "name": "خلفية التصنيف",
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 2,
      "id": "l_pill_body",
      "kind": "shape",
      "frame": {
        "x": 116,
        "y": 80,
        "w": 228,
        "h": 72
      },
      "shape": {
        "type": "rect",
        "fill": "{{design.ink}}"
      }
    },
    {
      "name": "خلفية التصنيف",
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 2,
      "id": "l_pill_end",
      "kind": "shape",
      "frame": {
        "x": 308,
        "y": 80,
        "w": 72,
        "h": 72
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{design.ink}}"
      }
    },
    {
      "id": "l_category",
      "kind": "text",
      "name": "التصنيف",
      "frame": {
        "x": 80,
        "y": 80,
        "w": 300,
        "h": 72
      },
      "text": {
        "literal": "جلسة"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 40,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{design.tangerine}}",
      "align": "center",
      "z": 10
    },
    {
      "id": "l_title",
      "kind": "text",
      "name": "عنوان الجلسة",
      "frame": {
        "x": 80,
        "y": 300,
        "w": 920,
        "h": 430
      },
      "text": {
        "binding": "session.title",
        "fallback": "عنوان الجلسة"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 96,
        "minSize": 56,
        "lineHeight": 1.12,
        "letterSpacing": 0,
        "weight": 800
      },
      "color": "{{design.ink}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 3
      },
      "z": 10
    },
    {
      "id": "l_presenters",
      "kind": "dynamic_field",
      "name": "المقدِّمون",
      "frame": {
        "x": 80,
        "y": 1010,
        "w": 640,
        "h": 130
      },
      "field": {
        "binding": "session.presenters",
        "fallback": "اسم المقدِّم"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 44,
        "minSize": 32,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{design.ink}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_when",
      "kind": "dynamic_field",
      "name": "الموعد",
      "frame": {
        "x": 80,
        "y": 1150,
        "w": 640,
        "h": 62
      },
      "field": {
        "binding": "session.startsAt",
        "fallback": "التاريخ والوقت"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 40,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{design.ink}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_qr",
      "kind": "qr",
      "name": "رمز الجلسة",
      "locked": true,
      "frame": {
        "x": 860,
        "y": 1130,
        "w": 140,
        "h": 140
      },
      "qr": {
        "binding": "session.eventUrl",
        "ecLevel": "M",
        "quietZoneModules": 4
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "proportional"
        }
      },
      "z": 10
    }
  ]
}$json$::jsonb;
v_fields := $fields$["brand.logoAssetId","session.title","session.presenters","session.startsAt","session.eventUrl"]$fields$::jsonb;

select t.id into v_template
  from public.design_templates t
 where t.scope = 'platform' and t.purpose = 'poster' and t.family = 'talk'
   and t.name = 'جلسة' and t.retired_at is null
 order by t.created_at
 limit 1;

if v_template is null then
  -- Louder than a silent skip: the row this seed amends is 0193's, and if it is
  -- not there the library is not what this file was generated against.
  raise exception 'baseline row missing for % % (%)', 'poster', 'talk', 'جلسة';
end if;

-- ADD the version unless this row already carries this exact document, which is
-- what makes a re-run a no-op. Never an UPDATE: a version is immutable
-- (REQ-DSG-007), and version 1 is what a certificate already issued renders as
-- (REQ-CRT-014).
if not exists (
  select 1 from public.design_template_versions v
   where v.template_id = v_template and v.document = v_doc
) then
  insert into public.design_template_versions (template_id, version, document, dynamic_fields, font_hashes, published_at)
  select
    v_template,
    coalesce(max(v.version), 0) + 1,
    v_doc, v_fields,
    -- No font hash is pinned on a platform version: the platform set is
    -- installed by hash in every image (REQ-DSG-016), as 0061 recorded.
    '{}',
    now()
  from public.design_template_versions v
  where v.template_id = v_template;
end if;

-- @family workshop@v2
v_template := null;
v_doc    := $json${
  "schemaVersion": 1,
  "purpose": "poster",
  "master": {
    "width": 1080,
    "height": 1350,
    "unit": "px",
    "dpi": 72
  },
  "direction": "rtl",
  "background": {
    "type": "solid",
    "color": "{{design.lime}}"
  },
  "layers": [
    {
      "id": "l_logo",
      "kind": "image",
      "name": "شعار المؤسسة",
      "image": {
        "binding": "brand.logoAssetId",
        "fit": "contain"
      },
      "frame": {
        "x": 880,
        "y": 80,
        "w": 120,
        "h": 120
      },
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "name": "خلفية التصنيف",
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 2,
      "id": "l_pill_start",
      "kind": "shape",
      "frame": {
        "x": 80,
        "y": 80,
        "w": 72,
        "h": 72
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{design.ink}}"
      }
    },
    {
      "name": "خلفية التصنيف",
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 2,
      "id": "l_pill_body",
      "kind": "shape",
      "frame": {
        "x": 116,
        "y": 80,
        "w": 228,
        "h": 72
      },
      "shape": {
        "type": "rect",
        "fill": "{{design.ink}}"
      }
    },
    {
      "name": "خلفية التصنيف",
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 2,
      "id": "l_pill_end",
      "kind": "shape",
      "frame": {
        "x": 308,
        "y": 80,
        "w": 72,
        "h": 72
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{design.ink}}"
      }
    },
    {
      "id": "l_category",
      "kind": "text",
      "name": "التصنيف",
      "frame": {
        "x": 80,
        "y": 80,
        "w": 300,
        "h": 72
      },
      "text": {
        "literal": "ورشة"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 40,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{design.lime}}",
      "align": "center",
      "z": 10
    },
    {
      "id": "l_title",
      "kind": "text",
      "name": "عنوان الجلسة",
      "frame": {
        "x": 80,
        "y": 300,
        "w": 920,
        "h": 430
      },
      "text": {
        "binding": "session.title",
        "fallback": "عنوان الجلسة"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 96,
        "minSize": 56,
        "lineHeight": 1.12,
        "letterSpacing": 0,
        "weight": 800
      },
      "color": "{{design.ink}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 3
      },
      "z": 10
    },
    {
      "id": "l_presenters",
      "kind": "dynamic_field",
      "name": "المقدِّمون",
      "frame": {
        "x": 80,
        "y": 1010,
        "w": 640,
        "h": 130
      },
      "field": {
        "binding": "session.presenters",
        "fallback": "اسم المقدِّم"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 44,
        "minSize": 32,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{design.ink}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_when",
      "kind": "dynamic_field",
      "name": "الموعد",
      "frame": {
        "x": 80,
        "y": 1150,
        "w": 640,
        "h": 62
      },
      "field": {
        "binding": "session.startsAt",
        "fallback": "التاريخ والوقت"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 40,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{design.ink}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_qr",
      "kind": "qr",
      "name": "رمز الجلسة",
      "locked": true,
      "frame": {
        "x": 860,
        "y": 1130,
        "w": 140,
        "h": 140
      },
      "qr": {
        "binding": "session.eventUrl",
        "ecLevel": "M",
        "quietZoneModules": 4
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "proportional"
        }
      },
      "z": 10
    }
  ]
}$json$::jsonb;
v_fields := $fields$["brand.logoAssetId","session.title","session.presenters","session.startsAt","session.eventUrl"]$fields$::jsonb;

select t.id into v_template
  from public.design_templates t
 where t.scope = 'platform' and t.purpose = 'poster' and t.family = 'workshop'
   and t.name = 'ورشة' and t.retired_at is null
 order by t.created_at
 limit 1;

if v_template is null then
  -- Louder than a silent skip: the row this seed amends is 0193's, and if it is
  -- not there the library is not what this file was generated against.
  raise exception 'baseline row missing for % % (%)', 'poster', 'workshop', 'ورشة';
end if;

-- ADD the version unless this row already carries this exact document, which is
-- what makes a re-run a no-op. Never an UPDATE: a version is immutable
-- (REQ-DSG-007), and version 1 is what a certificate already issued renders as
-- (REQ-CRT-014).
if not exists (
  select 1 from public.design_template_versions v
   where v.template_id = v_template and v.document = v_doc
) then
  insert into public.design_template_versions (template_id, version, document, dynamic_fields, font_hashes, published_at)
  select
    v_template,
    coalesce(max(v.version), 0) + 1,
    v_doc, v_fields,
    -- No font hash is pinned on a platform version: the platform set is
    -- installed by hash in every image (REQ-DSG-016), as 0061 recorded.
    '{}',
    now()
  from public.design_template_versions v
  where v.template_id = v_template;
end if;

-- @family panel@v2
v_template := null;
v_doc    := $json${
  "schemaVersion": 1,
  "purpose": "poster",
  "master": {
    "width": 1080,
    "height": 1350,
    "unit": "px",
    "dpi": 72
  },
  "direction": "rtl",
  "background": {
    "type": "solid",
    "color": "{{design.coral}}"
  },
  "layers": [
    {
      "id": "l_logo",
      "kind": "image",
      "name": "شعار المؤسسة",
      "image": {
        "binding": "brand.logoAssetId",
        "fit": "contain"
      },
      "frame": {
        "x": 880,
        "y": 80,
        "w": 120,
        "h": 120
      },
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "name": "خلفية التصنيف",
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 2,
      "id": "l_pill_start",
      "kind": "shape",
      "frame": {
        "x": 80,
        "y": 80,
        "w": 72,
        "h": 72
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{design.ink}}"
      }
    },
    {
      "name": "خلفية التصنيف",
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 2,
      "id": "l_pill_body",
      "kind": "shape",
      "frame": {
        "x": 116,
        "y": 80,
        "w": 228,
        "h": 72
      },
      "shape": {
        "type": "rect",
        "fill": "{{design.ink}}"
      }
    },
    {
      "name": "خلفية التصنيف",
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 2,
      "id": "l_pill_end",
      "kind": "shape",
      "frame": {
        "x": 308,
        "y": 80,
        "w": 72,
        "h": 72
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{design.ink}}"
      }
    },
    {
      "id": "l_category",
      "kind": "text",
      "name": "التصنيف",
      "frame": {
        "x": 80,
        "y": 80,
        "w": 300,
        "h": 72
      },
      "text": {
        "literal": "حوار"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 40,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{design.coral}}",
      "align": "center",
      "z": 10
    },
    {
      "id": "l_title",
      "kind": "text",
      "name": "عنوان الجلسة",
      "frame": {
        "x": 80,
        "y": 300,
        "w": 920,
        "h": 430
      },
      "text": {
        "binding": "session.title",
        "fallback": "عنوان الجلسة"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 96,
        "minSize": 56,
        "lineHeight": 1.12,
        "letterSpacing": 0,
        "weight": 800
      },
      "color": "{{design.ink}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 3
      },
      "z": 10
    },
    {
      "id": "l_presenters",
      "kind": "dynamic_field",
      "name": "المقدِّمون",
      "frame": {
        "x": 80,
        "y": 1010,
        "w": 640,
        "h": 130
      },
      "field": {
        "binding": "session.presenters",
        "fallback": "اسم المقدِّم"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 44,
        "minSize": 32,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{design.ink}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_when",
      "kind": "dynamic_field",
      "name": "الموعد",
      "frame": {
        "x": 80,
        "y": 1150,
        "w": 640,
        "h": 62
      },
      "field": {
        "binding": "session.startsAt",
        "fallback": "التاريخ والوقت"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 40,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{design.ink}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_qr",
      "kind": "qr",
      "name": "رمز الجلسة",
      "locked": true,
      "frame": {
        "x": 860,
        "y": 1130,
        "w": 140,
        "h": 140
      },
      "qr": {
        "binding": "session.eventUrl",
        "ecLevel": "M",
        "quietZoneModules": 4
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "proportional"
        }
      },
      "z": 10
    }
  ]
}$json$::jsonb;
v_fields := $fields$["brand.logoAssetId","session.title","session.presenters","session.startsAt","session.eventUrl"]$fields$::jsonb;

select t.id into v_template
  from public.design_templates t
 where t.scope = 'platform' and t.purpose = 'poster' and t.family = 'panel'
   and t.name = 'حوار' and t.retired_at is null
 order by t.created_at
 limit 1;

if v_template is null then
  -- Louder than a silent skip: the row this seed amends is 0193's, and if it is
  -- not there the library is not what this file was generated against.
  raise exception 'baseline row missing for % % (%)', 'poster', 'panel', 'حوار';
end if;

-- ADD the version unless this row already carries this exact document, which is
-- what makes a re-run a no-op. Never an UPDATE: a version is immutable
-- (REQ-DSG-007), and version 1 is what a certificate already issued renders as
-- (REQ-CRT-014).
if not exists (
  select 1 from public.design_template_versions v
   where v.template_id = v_template and v.document = v_doc
) then
  insert into public.design_template_versions (template_id, version, document, dynamic_fields, font_hashes, published_at)
  select
    v_template,
    coalesce(max(v.version), 0) + 1,
    v_doc, v_fields,
    -- No font hash is pinned on a platform version: the platform set is
    -- installed by hash in every image (REQ-DSG-016), as 0061 recorded.
    '{}',
    now()
  from public.design_template_versions v
  where v.template_id = v_template;
end if;

-- @family meetup@v2
v_template := null;
v_doc    := $json${
  "schemaVersion": 1,
  "purpose": "poster",
  "master": {
    "width": 1080,
    "height": 1350,
    "unit": "px",
    "dpi": 72
  },
  "direction": "rtl",
  "background": {
    "type": "solid",
    "color": "{{design.cyan}}"
  },
  "layers": [
    {
      "id": "l_logo",
      "kind": "image",
      "name": "شعار المؤسسة",
      "image": {
        "binding": "brand.logoAssetId",
        "fit": "contain"
      },
      "frame": {
        "x": 880,
        "y": 80,
        "w": 120,
        "h": 120
      },
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "name": "خلفية التصنيف",
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 2,
      "id": "l_pill_start",
      "kind": "shape",
      "frame": {
        "x": 80,
        "y": 80,
        "w": 72,
        "h": 72
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{design.ink}}"
      }
    },
    {
      "name": "خلفية التصنيف",
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 2,
      "id": "l_pill_body",
      "kind": "shape",
      "frame": {
        "x": 116,
        "y": 80,
        "w": 228,
        "h": 72
      },
      "shape": {
        "type": "rect",
        "fill": "{{design.ink}}"
      }
    },
    {
      "name": "خلفية التصنيف",
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 2,
      "id": "l_pill_end",
      "kind": "shape",
      "frame": {
        "x": 308,
        "y": 80,
        "w": 72,
        "h": 72
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{design.ink}}"
      }
    },
    {
      "id": "l_category",
      "kind": "text",
      "name": "التصنيف",
      "frame": {
        "x": 80,
        "y": 80,
        "w": 300,
        "h": 72
      },
      "text": {
        "literal": "لقاء"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 40,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{design.cyan}}",
      "align": "center",
      "z": 10
    },
    {
      "id": "l_title",
      "kind": "text",
      "name": "عنوان الجلسة",
      "frame": {
        "x": 80,
        "y": 300,
        "w": 920,
        "h": 430
      },
      "text": {
        "binding": "session.title",
        "fallback": "عنوان الجلسة"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 96,
        "minSize": 56,
        "lineHeight": 1.12,
        "letterSpacing": 0,
        "weight": 800
      },
      "color": "{{design.ink}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 3
      },
      "z": 10
    },
    {
      "id": "l_presenters",
      "kind": "dynamic_field",
      "name": "المقدِّمون",
      "frame": {
        "x": 80,
        "y": 1010,
        "w": 640,
        "h": 130
      },
      "field": {
        "binding": "session.presenters",
        "fallback": "اسم المقدِّم"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 44,
        "minSize": 32,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{design.ink}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_when",
      "kind": "dynamic_field",
      "name": "الموعد",
      "frame": {
        "x": 80,
        "y": 1150,
        "w": 640,
        "h": 62
      },
      "field": {
        "binding": "session.startsAt",
        "fallback": "التاريخ والوقت"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 40,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{design.ink}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_qr",
      "kind": "qr",
      "name": "رمز الجلسة",
      "locked": true,
      "frame": {
        "x": 860,
        "y": 1130,
        "w": 140,
        "h": 140
      },
      "qr": {
        "binding": "session.eventUrl",
        "ecLevel": "M",
        "quietZoneModules": 4
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "proportional"
        }
      },
      "z": 10
    }
  ]
}$json$::jsonb;
v_fields := $fields$["brand.logoAssetId","session.title","session.presenters","session.startsAt","session.eventUrl"]$fields$::jsonb;

select t.id into v_template
  from public.design_templates t
 where t.scope = 'platform' and t.purpose = 'poster' and t.family = 'meetup'
   and t.name = 'لقاء' and t.retired_at is null
 order by t.created_at
 limit 1;

if v_template is null then
  -- Louder than a silent skip: the row this seed amends is 0193's, and if it is
  -- not there the library is not what this file was generated against.
  raise exception 'baseline row missing for % % (%)', 'poster', 'meetup', 'لقاء';
end if;

-- ADD the version unless this row already carries this exact document, which is
-- what makes a re-run a no-op. Never an UPDATE: a version is immutable
-- (REQ-DSG-007), and version 1 is what a certificate already issued renders as
-- (REQ-CRT-014).
if not exists (
  select 1 from public.design_template_versions v
   where v.template_id = v_template and v.document = v_doc
) then
  insert into public.design_template_versions (template_id, version, document, dynamic_fields, font_hashes, published_at)
  select
    v_template,
    coalesce(max(v.version), 0) + 1,
    v_doc, v_fields,
    -- No font hash is pinned on a platform version: the platform set is
    -- installed by hash in every image (REQ-DSG-016), as 0061 recorded.
    '{}',
    now()
  from public.design_template_versions v
  where v.template_id = v_template;
end if;

-- @family announcement@v2
v_template := null;
v_doc    := $json${
  "schemaVersion": 1,
  "purpose": "poster",
  "master": {
    "width": 1080,
    "height": 1350,
    "unit": "px",
    "dpi": 72
  },
  "direction": "rtl",
  "background": {
    "type": "solid",
    "color": "{{design.violet}}"
  },
  "layers": [
    {
      "id": "l_logo",
      "kind": "image",
      "name": "شعار المؤسسة",
      "image": {
        "binding": "brand.logoAssetId",
        "fit": "contain"
      },
      "frame": {
        "x": 880,
        "y": 80,
        "w": 120,
        "h": 120
      },
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "name": "خلفية التصنيف",
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 2,
      "id": "l_pill_start",
      "kind": "shape",
      "frame": {
        "x": 80,
        "y": 80,
        "w": 72,
        "h": 72
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{design.ink}}"
      }
    },
    {
      "name": "خلفية التصنيف",
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 2,
      "id": "l_pill_body",
      "kind": "shape",
      "frame": {
        "x": 116,
        "y": 80,
        "w": 228,
        "h": 72
      },
      "shape": {
        "type": "rect",
        "fill": "{{design.ink}}"
      }
    },
    {
      "name": "خلفية التصنيف",
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 2,
      "id": "l_pill_end",
      "kind": "shape",
      "frame": {
        "x": 308,
        "y": 80,
        "w": 72,
        "h": 72
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{design.ink}}"
      }
    },
    {
      "id": "l_category",
      "kind": "text",
      "name": "التصنيف",
      "frame": {
        "x": 80,
        "y": 80,
        "w": 300,
        "h": 72
      },
      "text": {
        "literal": "إعلان"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 40,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{design.violet}}",
      "align": "center",
      "z": 10
    },
    {
      "id": "l_title",
      "kind": "text",
      "name": "عنوان الجلسة",
      "frame": {
        "x": 80,
        "y": 300,
        "w": 920,
        "h": 430
      },
      "text": {
        "binding": "session.title",
        "fallback": "عنوان الجلسة"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 96,
        "minSize": 56,
        "lineHeight": 1.12,
        "letterSpacing": 0,
        "weight": 800
      },
      "color": "{{design.ink}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 3
      },
      "z": 10
    },
    {
      "id": "l_presenters",
      "kind": "dynamic_field",
      "name": "المقدِّمون",
      "frame": {
        "x": 80,
        "y": 1010,
        "w": 640,
        "h": 130
      },
      "field": {
        "binding": "session.presenters",
        "fallback": "اسم المقدِّم"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 44,
        "minSize": 32,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{design.ink}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_when",
      "kind": "dynamic_field",
      "name": "الموعد",
      "frame": {
        "x": 80,
        "y": 1150,
        "w": 640,
        "h": 62
      },
      "field": {
        "binding": "session.startsAt",
        "fallback": "التاريخ والوقت"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 40,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{design.ink}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_qr",
      "kind": "qr",
      "name": "رمز الجلسة",
      "locked": true,
      "frame": {
        "x": 860,
        "y": 1130,
        "w": 140,
        "h": 140
      },
      "qr": {
        "binding": "session.eventUrl",
        "ecLevel": "M",
        "quietZoneModules": 4
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "proportional"
        }
      },
      "z": 10
    }
  ]
}$json$::jsonb;
v_fields := $fields$["brand.logoAssetId","session.title","session.presenters","session.startsAt","session.eventUrl"]$fields$::jsonb;

select t.id into v_template
  from public.design_templates t
 where t.scope = 'platform' and t.purpose = 'poster' and t.family = 'announcement'
   and t.name = 'إعلان' and t.retired_at is null
 order by t.created_at
 limit 1;

if v_template is null then
  -- Louder than a silent skip: the row this seed amends is 0193's, and if it is
  -- not there the library is not what this file was generated against.
  raise exception 'baseline row missing for % % (%)', 'poster', 'announcement', 'إعلان';
end if;

-- ADD the version unless this row already carries this exact document, which is
-- what makes a re-run a no-op. Never an UPDATE: a version is immutable
-- (REQ-DSG-007), and version 1 is what a certificate already issued renders as
-- (REQ-CRT-014).
if not exists (
  select 1 from public.design_template_versions v
   where v.template_id = v_template and v.document = v_doc
) then
  insert into public.design_template_versions (template_id, version, document, dynamic_fields, font_hashes, published_at)
  select
    v_template,
    coalesce(max(v.version), 0) + 1,
    v_doc, v_fields,
    -- No font hash is pinned on a platform version: the platform set is
    -- installed by hash in every image (REQ-DSG-016), as 0061 recorded.
    '{}',
    now()
  from public.design_template_versions v
  where v.template_id = v_template;
end if;

-- @family attendance@landscape@v2
v_template := null;
v_doc    := $json${
  "schemaVersion": 1,
  "purpose": "certificate",
  "master": {
    "width": 3508,
    "height": 2480,
    "unit": "px",
    "dpi": 300
  },
  "direction": "rtl",
  "background": {
    "type": "solid",
    "color": "{{brand.canvas}}"
  },
  "layers": [
    {
      "id": "l_logo",
      "kind": "image",
      "name": "شعار المؤسسة",
      "image": {
        "binding": "brand.logoAssetId",
        "fit": "contain"
      },
      "frame": {
        "x": 240,
        "y": 240,
        "w": 220,
        "h": 220
      },
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_org",
      "kind": "dynamic_field",
      "name": "اسم المؤسسة",
      "frame": {
        "x": 512,
        "y": 265,
        "w": 1928,
        "h": 170
      },
      "field": {
        "binding": "org.name",
        "fallback": "اسم المؤسسة"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 120,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.fgHeading}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_kind",
      "kind": "text",
      "name": "نوع الشهادة",
      "frame": {
        "x": 240,
        "y": 430,
        "w": 2200,
        "h": 120
      },
      "text": {
        "literal": "شهادة حضور"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 84,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_recipient",
      "kind": "dynamic_field",
      "name": "اسم المستفيد",
      "frame": {
        "x": 240,
        "y": 640,
        "w": 3028,
        "h": 850
      },
      "field": {
        "binding": "recipient.name",
        "fallback": "اسم المستفيد"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 300,
        "minSize": 150,
        "lineHeight": 1.12,
        "letterSpacing": 0,
        "weight": 800
      },
      "color": "{{brand.fgHeading}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_reason",
      "kind": "dynamic_field",
      "name": "عن الجلسة",
      "frame": {
        "x": 240,
        "y": 1540,
        "w": 3028,
        "h": 260
      },
      "field": {
        "binding": "session.title",
        "fallback": "عنوان الجلسة"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 72,
        "minSize": 48,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgBody}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_issued",
      "kind": "dynamic_field",
      "name": "تاريخ الإصدار",
      "frame": {
        "x": 240,
        "y": 1840,
        "w": 1400,
        "h": 100
      },
      "field": {
        "binding": "certificate.issuedAt",
        "fallback": "تاريخ الإصدار"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_qr",
      "kind": "qr",
      "name": "رمز التحقّق",
      "locked": true,
      "frame": {
        "x": 2948,
        "y": 1920,
        "w": 320,
        "h": 320
      },
      "qr": {
        "binding": "certificate.verifyUrl",
        "ecLevel": "Q",
        "quietZoneModules": 4
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_serial",
      "kind": "dynamic_field",
      "name": "الرقم التسلسلي",
      "locked": true,
      "frame": {
        "x": 240,
        "y": 2020,
        "w": 1400,
        "h": 100
      },
      "field": {
        "binding": "certificate.serial",
        "fallback": "الرقم التسلسلي"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_code",
      "kind": "dynamic_field",
      "name": "رمز التحقّق النصّي",
      "locked": true,
      "frame": {
        "x": 240,
        "y": 2130,
        "w": 1400,
        "h": 100
      },
      "field": {
        "binding": "certificate.verificationCode",
        "fallback": "رمز التحقّق"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_signature",
      "kind": "shape",
      "name": "موضع التوقيع",
      "locked": true,
      "frame": {
        "x": 1900,
        "y": 2120,
        "w": 800,
        "h": 2
      },
      "shape": {
        "type": "rect",
        "fill": "{{brand.edge}}"
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_signature_label",
      "kind": "text",
      "name": "تسمية التوقيع",
      "frame": {
        "x": 1900,
        "y": 2144,
        "w": 800,
        "h": 96
      },
      "text": {
        "literal": "التوقيع"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "letterSpacing": 0,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    }
  ]
}$json$::jsonb;
v_fields := $fields$["brand.logoAssetId","org.name","recipient.name","session.title","certificate.issuedAt","certificate.verifyUrl","certificate.serial","certificate.verificationCode"]$fields$::jsonb;

select t.id into v_template
  from public.design_templates t
 where t.scope = 'platform' and t.purpose = 'certificate' and t.family = 'attendance'
   and t.name = 'شهادة حضور أفقية' and t.retired_at is null
 order by t.created_at
 limit 1;

if v_template is null then
  -- Louder than a silent skip: the row this seed amends is 0193's, and if it is
  -- not there the library is not what this file was generated against.
  raise exception 'baseline row missing for % % (%)', 'certificate', 'attendance', 'شهادة حضور أفقية';
end if;

-- ADD the version unless this row already carries this exact document, which is
-- what makes a re-run a no-op. Never an UPDATE: a version is immutable
-- (REQ-DSG-007), and version 1 is what a certificate already issued renders as
-- (REQ-CRT-014).
if not exists (
  select 1 from public.design_template_versions v
   where v.template_id = v_template and v.document = v_doc
) then
  insert into public.design_template_versions (template_id, version, document, dynamic_fields, font_hashes, published_at)
  select
    v_template,
    coalesce(max(v.version), 0) + 1,
    v_doc, v_fields,
    -- No font hash is pinned on a platform version: the platform set is
    -- installed by hash in every image (REQ-DSG-016), as 0061 recorded.
    '{}',
    now()
  from public.design_template_versions v
  where v.template_id = v_template;
end if;

-- @family attendance@portrait@v2
v_template := null;
v_doc    := $json${
  "schemaVersion": 1,
  "purpose": "certificate",
  "master": {
    "width": 2480,
    "height": 3508,
    "unit": "px",
    "dpi": 300
  },
  "direction": "rtl",
  "background": {
    "type": "solid",
    "color": "{{brand.canvas}}"
  },
  "layers": [
    {
      "id": "l_logo",
      "kind": "image",
      "name": "شعار المؤسسة",
      "image": {
        "binding": "brand.logoAssetId",
        "fit": "contain"
      },
      "frame": {
        "x": 240,
        "y": 240,
        "w": 220,
        "h": 220
      },
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_org",
      "kind": "dynamic_field",
      "name": "اسم المؤسسة",
      "frame": {
        "x": 512,
        "y": 265,
        "w": 1428,
        "h": 170
      },
      "field": {
        "binding": "org.name",
        "fallback": "اسم المؤسسة"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 120,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.fgHeading}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_kind",
      "kind": "text",
      "name": "نوع الشهادة",
      "frame": {
        "x": 240,
        "y": 430,
        "w": 1700,
        "h": 120
      },
      "text": {
        "literal": "شهادة حضور"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 84,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_recipient",
      "kind": "dynamic_field",
      "name": "اسم المستفيد",
      "frame": {
        "x": 240,
        "y": 700,
        "w": 2000,
        "h": 1000
      },
      "field": {
        "binding": "recipient.name",
        "fallback": "اسم المستفيد"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 300,
        "minSize": 150,
        "lineHeight": 1.12,
        "letterSpacing": 0,
        "weight": 800
      },
      "color": "{{brand.fgHeading}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_reason",
      "kind": "dynamic_field",
      "name": "عن الجلسة",
      "frame": {
        "x": 240,
        "y": 1780,
        "w": 2000,
        "h": 260
      },
      "field": {
        "binding": "session.title",
        "fallback": "عنوان الجلسة"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 72,
        "minSize": 48,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgBody}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_issued",
      "kind": "dynamic_field",
      "name": "تاريخ الإصدار",
      "frame": {
        "x": 240,
        "y": 2100,
        "w": 1300,
        "h": 100
      },
      "field": {
        "binding": "certificate.issuedAt",
        "fallback": "تاريخ الإصدار"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_qr",
      "kind": "qr",
      "name": "رمز التحقّق",
      "locked": true,
      "frame": {
        "x": 1920,
        "y": 2948,
        "w": 320,
        "h": 320
      },
      "qr": {
        "binding": "certificate.verifyUrl",
        "ecLevel": "Q",
        "quietZoneModules": 4
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_serial",
      "kind": "dynamic_field",
      "name": "الرقم التسلسلي",
      "locked": true,
      "frame": {
        "x": 240,
        "y": 2980,
        "w": 1300,
        "h": 100
      },
      "field": {
        "binding": "certificate.serial",
        "fallback": "الرقم التسلسلي"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_code",
      "kind": "dynamic_field",
      "name": "رمز التحقّق النصّي",
      "locked": true,
      "frame": {
        "x": 240,
        "y": 3090,
        "w": 1300,
        "h": 100
      },
      "field": {
        "binding": "certificate.verificationCode",
        "fallback": "رمز التحقّق"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_signature",
      "kind": "shape",
      "name": "موضع التوقيع",
      "locked": true,
      "frame": {
        "x": 1440,
        "y": 2900,
        "w": 800,
        "h": 2
      },
      "shape": {
        "type": "rect",
        "fill": "{{brand.edge}}"
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_signature_label",
      "kind": "text",
      "name": "تسمية التوقيع",
      "frame": {
        "x": 1440,
        "y": 2931,
        "w": 440,
        "h": 96
      },
      "text": {
        "literal": "التوقيع"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "letterSpacing": 0,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    }
  ]
}$json$::jsonb;
v_fields := $fields$["brand.logoAssetId","org.name","recipient.name","session.title","certificate.issuedAt","certificate.verifyUrl","certificate.serial","certificate.verificationCode"]$fields$::jsonb;

select t.id into v_template
  from public.design_templates t
 where t.scope = 'platform' and t.purpose = 'certificate' and t.family = 'attendance'
   and t.name = 'شهادة حضور عمودية' and t.retired_at is null
 order by t.created_at
 limit 1;

if v_template is null then
  -- Louder than a silent skip: the row this seed amends is 0193's, and if it is
  -- not there the library is not what this file was generated against.
  raise exception 'baseline row missing for % % (%)', 'certificate', 'attendance', 'شهادة حضور عمودية';
end if;

-- ADD the version unless this row already carries this exact document, which is
-- what makes a re-run a no-op. Never an UPDATE: a version is immutable
-- (REQ-DSG-007), and version 1 is what a certificate already issued renders as
-- (REQ-CRT-014).
if not exists (
  select 1 from public.design_template_versions v
   where v.template_id = v_template and v.document = v_doc
) then
  insert into public.design_template_versions (template_id, version, document, dynamic_fields, font_hashes, published_at)
  select
    v_template,
    coalesce(max(v.version), 0) + 1,
    v_doc, v_fields,
    -- No font hash is pinned on a platform version: the platform set is
    -- installed by hash in every image (REQ-DSG-016), as 0061 recorded.
    '{}',
    now()
  from public.design_template_versions v
  where v.template_id = v_template;
end if;

-- @family presenter@landscape@v2
v_template := null;
v_doc    := $json${
  "schemaVersion": 1,
  "purpose": "certificate",
  "master": {
    "width": 3508,
    "height": 2480,
    "unit": "px",
    "dpi": 300
  },
  "direction": "rtl",
  "background": {
    "type": "solid",
    "color": "{{brand.canvas}}"
  },
  "layers": [
    {
      "id": "l_logo",
      "kind": "image",
      "name": "شعار المؤسسة",
      "image": {
        "binding": "brand.logoAssetId",
        "fit": "contain"
      },
      "frame": {
        "x": 240,
        "y": 240,
        "w": 220,
        "h": 220
      },
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_org",
      "kind": "dynamic_field",
      "name": "اسم المؤسسة",
      "frame": {
        "x": 512,
        "y": 265,
        "w": 1928,
        "h": 170
      },
      "field": {
        "binding": "org.name",
        "fallback": "اسم المؤسسة"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 120,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.fgHeading}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_kind",
      "kind": "text",
      "name": "نوع الشهادة",
      "frame": {
        "x": 240,
        "y": 430,
        "w": 2200,
        "h": 120
      },
      "text": {
        "literal": "شهادة تقديم"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 84,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_recipient",
      "kind": "dynamic_field",
      "name": "اسم المستفيد",
      "frame": {
        "x": 240,
        "y": 640,
        "w": 3028,
        "h": 850
      },
      "field": {
        "binding": "recipient.name",
        "fallback": "اسم المستفيد"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 300,
        "minSize": 150,
        "lineHeight": 1.12,
        "letterSpacing": 0,
        "weight": 800
      },
      "color": "{{brand.fgHeading}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_reason",
      "kind": "dynamic_field",
      "name": "عن الجلسة",
      "frame": {
        "x": 240,
        "y": 1540,
        "w": 3028,
        "h": 260
      },
      "field": {
        "binding": "session.title",
        "fallback": "عنوان الجلسة"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 72,
        "minSize": 48,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgBody}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_issued",
      "kind": "dynamic_field",
      "name": "تاريخ الإصدار",
      "frame": {
        "x": 240,
        "y": 1840,
        "w": 1400,
        "h": 100
      },
      "field": {
        "binding": "certificate.issuedAt",
        "fallback": "تاريخ الإصدار"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_qr",
      "kind": "qr",
      "name": "رمز التحقّق",
      "locked": true,
      "frame": {
        "x": 2948,
        "y": 1920,
        "w": 320,
        "h": 320
      },
      "qr": {
        "binding": "certificate.verifyUrl",
        "ecLevel": "Q",
        "quietZoneModules": 4
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_serial",
      "kind": "dynamic_field",
      "name": "الرقم التسلسلي",
      "locked": true,
      "frame": {
        "x": 240,
        "y": 2020,
        "w": 1400,
        "h": 100
      },
      "field": {
        "binding": "certificate.serial",
        "fallback": "الرقم التسلسلي"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_code",
      "kind": "dynamic_field",
      "name": "رمز التحقّق النصّي",
      "locked": true,
      "frame": {
        "x": 240,
        "y": 2130,
        "w": 1400,
        "h": 100
      },
      "field": {
        "binding": "certificate.verificationCode",
        "fallback": "رمز التحقّق"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_signature",
      "kind": "shape",
      "name": "موضع التوقيع",
      "locked": true,
      "frame": {
        "x": 1900,
        "y": 2120,
        "w": 800,
        "h": 2
      },
      "shape": {
        "type": "rect",
        "fill": "{{brand.edge}}"
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_signature_label",
      "kind": "text",
      "name": "تسمية التوقيع",
      "frame": {
        "x": 1900,
        "y": 2144,
        "w": 800,
        "h": 96
      },
      "text": {
        "literal": "التوقيع"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "letterSpacing": 0,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    }
  ]
}$json$::jsonb;
v_fields := $fields$["brand.logoAssetId","org.name","recipient.name","session.title","certificate.issuedAt","certificate.verifyUrl","certificate.serial","certificate.verificationCode"]$fields$::jsonb;

select t.id into v_template
  from public.design_templates t
 where t.scope = 'platform' and t.purpose = 'certificate' and t.family = 'presenter'
   and t.name = 'شهادة تقديم أفقية' and t.retired_at is null
 order by t.created_at
 limit 1;

if v_template is null then
  -- Louder than a silent skip: the row this seed amends is 0193's, and if it is
  -- not there the library is not what this file was generated against.
  raise exception 'baseline row missing for % % (%)', 'certificate', 'presenter', 'شهادة تقديم أفقية';
end if;

-- ADD the version unless this row already carries this exact document, which is
-- what makes a re-run a no-op. Never an UPDATE: a version is immutable
-- (REQ-DSG-007), and version 1 is what a certificate already issued renders as
-- (REQ-CRT-014).
if not exists (
  select 1 from public.design_template_versions v
   where v.template_id = v_template and v.document = v_doc
) then
  insert into public.design_template_versions (template_id, version, document, dynamic_fields, font_hashes, published_at)
  select
    v_template,
    coalesce(max(v.version), 0) + 1,
    v_doc, v_fields,
    -- No font hash is pinned on a platform version: the platform set is
    -- installed by hash in every image (REQ-DSG-016), as 0061 recorded.
    '{}',
    now()
  from public.design_template_versions v
  where v.template_id = v_template;
end if;

-- @family presenter@portrait@v2
v_template := null;
v_doc    := $json${
  "schemaVersion": 1,
  "purpose": "certificate",
  "master": {
    "width": 2480,
    "height": 3508,
    "unit": "px",
    "dpi": 300
  },
  "direction": "rtl",
  "background": {
    "type": "solid",
    "color": "{{brand.canvas}}"
  },
  "layers": [
    {
      "id": "l_logo",
      "kind": "image",
      "name": "شعار المؤسسة",
      "image": {
        "binding": "brand.logoAssetId",
        "fit": "contain"
      },
      "frame": {
        "x": 240,
        "y": 240,
        "w": 220,
        "h": 220
      },
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_org",
      "kind": "dynamic_field",
      "name": "اسم المؤسسة",
      "frame": {
        "x": 512,
        "y": 265,
        "w": 1428,
        "h": 170
      },
      "field": {
        "binding": "org.name",
        "fallback": "اسم المؤسسة"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 120,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.fgHeading}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_kind",
      "kind": "text",
      "name": "نوع الشهادة",
      "frame": {
        "x": 240,
        "y": 430,
        "w": 1700,
        "h": 120
      },
      "text": {
        "literal": "شهادة تقديم"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 84,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_recipient",
      "kind": "dynamic_field",
      "name": "اسم المستفيد",
      "frame": {
        "x": 240,
        "y": 700,
        "w": 2000,
        "h": 1000
      },
      "field": {
        "binding": "recipient.name",
        "fallback": "اسم المستفيد"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 300,
        "minSize": 150,
        "lineHeight": 1.12,
        "letterSpacing": 0,
        "weight": 800
      },
      "color": "{{brand.fgHeading}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_reason",
      "kind": "dynamic_field",
      "name": "عن الجلسة",
      "frame": {
        "x": 240,
        "y": 1780,
        "w": 2000,
        "h": 260
      },
      "field": {
        "binding": "session.title",
        "fallback": "عنوان الجلسة"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 72,
        "minSize": 48,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgBody}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_issued",
      "kind": "dynamic_field",
      "name": "تاريخ الإصدار",
      "frame": {
        "x": 240,
        "y": 2100,
        "w": 1300,
        "h": 100
      },
      "field": {
        "binding": "certificate.issuedAt",
        "fallback": "تاريخ الإصدار"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_qr",
      "kind": "qr",
      "name": "رمز التحقّق",
      "locked": true,
      "frame": {
        "x": 1920,
        "y": 2948,
        "w": 320,
        "h": 320
      },
      "qr": {
        "binding": "certificate.verifyUrl",
        "ecLevel": "Q",
        "quietZoneModules": 4
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_serial",
      "kind": "dynamic_field",
      "name": "الرقم التسلسلي",
      "locked": true,
      "frame": {
        "x": 240,
        "y": 2980,
        "w": 1300,
        "h": 100
      },
      "field": {
        "binding": "certificate.serial",
        "fallback": "الرقم التسلسلي"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_code",
      "kind": "dynamic_field",
      "name": "رمز التحقّق النصّي",
      "locked": true,
      "frame": {
        "x": 240,
        "y": 3090,
        "w": 1300,
        "h": 100
      },
      "field": {
        "binding": "certificate.verificationCode",
        "fallback": "رمز التحقّق"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_signature",
      "kind": "shape",
      "name": "موضع التوقيع",
      "locked": true,
      "frame": {
        "x": 1440,
        "y": 2900,
        "w": 800,
        "h": 2
      },
      "shape": {
        "type": "rect",
        "fill": "{{brand.edge}}"
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_signature_label",
      "kind": "text",
      "name": "تسمية التوقيع",
      "frame": {
        "x": 1440,
        "y": 2931,
        "w": 440,
        "h": 96
      },
      "text": {
        "literal": "التوقيع"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "letterSpacing": 0,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    }
  ]
}$json$::jsonb;
v_fields := $fields$["brand.logoAssetId","org.name","recipient.name","session.title","certificate.issuedAt","certificate.verifyUrl","certificate.serial","certificate.verificationCode"]$fields$::jsonb;

select t.id into v_template
  from public.design_templates t
 where t.scope = 'platform' and t.purpose = 'certificate' and t.family = 'presenter'
   and t.name = 'شهادة تقديم عمودية' and t.retired_at is null
 order by t.created_at
 limit 1;

if v_template is null then
  -- Louder than a silent skip: the row this seed amends is 0193's, and if it is
  -- not there the library is not what this file was generated against.
  raise exception 'baseline row missing for % % (%)', 'certificate', 'presenter', 'شهادة تقديم عمودية';
end if;

-- ADD the version unless this row already carries this exact document, which is
-- what makes a re-run a no-op. Never an UPDATE: a version is immutable
-- (REQ-DSG-007), and version 1 is what a certificate already issued renders as
-- (REQ-CRT-014).
if not exists (
  select 1 from public.design_template_versions v
   where v.template_id = v_template and v.document = v_doc
) then
  insert into public.design_template_versions (template_id, version, document, dynamic_fields, font_hashes, published_at)
  select
    v_template,
    coalesce(max(v.version), 0) + 1,
    v_doc, v_fields,
    -- No font hash is pinned on a platform version: the platform set is
    -- installed by hash in every image (REQ-DSG-016), as 0061 recorded.
    '{}',
    now()
  from public.design_template_versions v
  where v.template_id = v_template;
end if;

-- @family achievement@landscape@v2
v_template := null;
v_doc    := $json${
  "schemaVersion": 1,
  "purpose": "certificate",
  "master": {
    "width": 3508,
    "height": 2480,
    "unit": "px",
    "dpi": 300
  },
  "direction": "rtl",
  "background": {
    "type": "solid",
    "color": "{{brand.canvas}}"
  },
  "layers": [
    {
      "id": "l_logo",
      "kind": "image",
      "name": "شعار المؤسسة",
      "image": {
        "binding": "brand.logoAssetId",
        "fit": "contain"
      },
      "frame": {
        "x": 240,
        "y": 240,
        "w": 220,
        "h": 220
      },
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_org",
      "kind": "dynamic_field",
      "name": "اسم المؤسسة",
      "frame": {
        "x": 512,
        "y": 265,
        "w": 1928,
        "h": 170
      },
      "field": {
        "binding": "org.name",
        "fallback": "اسم المؤسسة"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 120,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.fgHeading}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_kind",
      "kind": "text",
      "name": "نوع الشهادة",
      "frame": {
        "x": 240,
        "y": 430,
        "w": 2200,
        "h": 120
      },
      "text": {
        "literal": "شهادة إنجاز"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 84,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_recipient",
      "kind": "dynamic_field",
      "name": "اسم المستفيد",
      "frame": {
        "x": 240,
        "y": 640,
        "w": 3028,
        "h": 850
      },
      "field": {
        "binding": "recipient.name",
        "fallback": "اسم المستفيد"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 300,
        "minSize": 150,
        "lineHeight": 1.12,
        "letterSpacing": 0,
        "weight": 800
      },
      "color": "{{brand.fgHeading}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_reason",
      "kind": "dynamic_field",
      "name": "عن الجلسة",
      "frame": {
        "x": 240,
        "y": 1540,
        "w": 3028,
        "h": 260
      },
      "field": {
        "binding": "certificate.achievementName",
        "fallback": "اسم الإنجاز"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 72,
        "minSize": 48,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgBody}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_issued",
      "kind": "dynamic_field",
      "name": "تاريخ الإصدار",
      "frame": {
        "x": 240,
        "y": 1840,
        "w": 1400,
        "h": 100
      },
      "field": {
        "binding": "certificate.issuedAt",
        "fallback": "تاريخ الإصدار"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_qr",
      "kind": "qr",
      "name": "رمز التحقّق",
      "locked": true,
      "frame": {
        "x": 2948,
        "y": 1920,
        "w": 320,
        "h": 320
      },
      "qr": {
        "binding": "certificate.verifyUrl",
        "ecLevel": "Q",
        "quietZoneModules": 4
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_serial",
      "kind": "dynamic_field",
      "name": "الرقم التسلسلي",
      "locked": true,
      "frame": {
        "x": 240,
        "y": 2020,
        "w": 1400,
        "h": 100
      },
      "field": {
        "binding": "certificate.serial",
        "fallback": "الرقم التسلسلي"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_code",
      "kind": "dynamic_field",
      "name": "رمز التحقّق النصّي",
      "locked": true,
      "frame": {
        "x": 240,
        "y": 2130,
        "w": 1400,
        "h": 100
      },
      "field": {
        "binding": "certificate.verificationCode",
        "fallback": "رمز التحقّق"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_signature",
      "kind": "shape",
      "name": "موضع التوقيع",
      "locked": true,
      "frame": {
        "x": 1900,
        "y": 2120,
        "w": 800,
        "h": 2
      },
      "shape": {
        "type": "rect",
        "fill": "{{brand.edge}}"
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_signature_label",
      "kind": "text",
      "name": "تسمية التوقيع",
      "frame": {
        "x": 1900,
        "y": 2144,
        "w": 800,
        "h": 96
      },
      "text": {
        "literal": "التوقيع"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "letterSpacing": 0,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    }
  ]
}$json$::jsonb;
v_fields := $fields$["brand.logoAssetId","org.name","recipient.name","certificate.achievementName","certificate.issuedAt","certificate.verifyUrl","certificate.serial","certificate.verificationCode"]$fields$::jsonb;

select t.id into v_template
  from public.design_templates t
 where t.scope = 'platform' and t.purpose = 'certificate' and t.family = 'achievement'
   and t.name = 'شهادة إنجاز أفقية' and t.retired_at is null
 order by t.created_at
 limit 1;

if v_template is null then
  -- Louder than a silent skip: the row this seed amends is 0193's, and if it is
  -- not there the library is not what this file was generated against.
  raise exception 'baseline row missing for % % (%)', 'certificate', 'achievement', 'شهادة إنجاز أفقية';
end if;

-- ADD the version unless this row already carries this exact document, which is
-- what makes a re-run a no-op. Never an UPDATE: a version is immutable
-- (REQ-DSG-007), and version 1 is what a certificate already issued renders as
-- (REQ-CRT-014).
if not exists (
  select 1 from public.design_template_versions v
   where v.template_id = v_template and v.document = v_doc
) then
  insert into public.design_template_versions (template_id, version, document, dynamic_fields, font_hashes, published_at)
  select
    v_template,
    coalesce(max(v.version), 0) + 1,
    v_doc, v_fields,
    -- No font hash is pinned on a platform version: the platform set is
    -- installed by hash in every image (REQ-DSG-016), as 0061 recorded.
    '{}',
    now()
  from public.design_template_versions v
  where v.template_id = v_template;
end if;

-- @family achievement@portrait@v2
v_template := null;
v_doc    := $json${
  "schemaVersion": 1,
  "purpose": "certificate",
  "master": {
    "width": 2480,
    "height": 3508,
    "unit": "px",
    "dpi": 300
  },
  "direction": "rtl",
  "background": {
    "type": "solid",
    "color": "{{brand.canvas}}"
  },
  "layers": [
    {
      "id": "l_logo",
      "kind": "image",
      "name": "شعار المؤسسة",
      "image": {
        "binding": "brand.logoAssetId",
        "fit": "contain"
      },
      "frame": {
        "x": 240,
        "y": 240,
        "w": 220,
        "h": 220
      },
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_org",
      "kind": "dynamic_field",
      "name": "اسم المؤسسة",
      "frame": {
        "x": 512,
        "y": 265,
        "w": 1428,
        "h": 170
      },
      "field": {
        "binding": "org.name",
        "fallback": "اسم المؤسسة"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 120,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.fgHeading}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_kind",
      "kind": "text",
      "name": "نوع الشهادة",
      "frame": {
        "x": 240,
        "y": 430,
        "w": 1700,
        "h": 120
      },
      "text": {
        "literal": "شهادة إنجاز"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 84,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_recipient",
      "kind": "dynamic_field",
      "name": "اسم المستفيد",
      "frame": {
        "x": 240,
        "y": 700,
        "w": 2000,
        "h": 1000
      },
      "field": {
        "binding": "recipient.name",
        "fallback": "اسم المستفيد"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 300,
        "minSize": 150,
        "lineHeight": 1.12,
        "letterSpacing": 0,
        "weight": 800
      },
      "color": "{{brand.fgHeading}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_reason",
      "kind": "dynamic_field",
      "name": "عن الجلسة",
      "frame": {
        "x": 240,
        "y": 1780,
        "w": 2000,
        "h": 260
      },
      "field": {
        "binding": "certificate.achievementName",
        "fallback": "اسم الإنجاز"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 72,
        "minSize": 48,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgBody}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_issued",
      "kind": "dynamic_field",
      "name": "تاريخ الإصدار",
      "frame": {
        "x": 240,
        "y": 2100,
        "w": 1300,
        "h": 100
      },
      "field": {
        "binding": "certificate.issuedAt",
        "fallback": "تاريخ الإصدار"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_qr",
      "kind": "qr",
      "name": "رمز التحقّق",
      "locked": true,
      "frame": {
        "x": 1920,
        "y": 2948,
        "w": 320,
        "h": 320
      },
      "qr": {
        "binding": "certificate.verifyUrl",
        "ecLevel": "Q",
        "quietZoneModules": 4
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_serial",
      "kind": "dynamic_field",
      "name": "الرقم التسلسلي",
      "locked": true,
      "frame": {
        "x": 240,
        "y": 2980,
        "w": 1300,
        "h": 100
      },
      "field": {
        "binding": "certificate.serial",
        "fallback": "الرقم التسلسلي"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_code",
      "kind": "dynamic_field",
      "name": "رمز التحقّق النصّي",
      "locked": true,
      "frame": {
        "x": 240,
        "y": 3090,
        "w": 1300,
        "h": 100
      },
      "field": {
        "binding": "certificate.verificationCode",
        "fallback": "رمز التحقّق"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_signature",
      "kind": "shape",
      "name": "موضع التوقيع",
      "locked": true,
      "frame": {
        "x": 1440,
        "y": 2900,
        "w": 800,
        "h": 2
      },
      "shape": {
        "type": "rect",
        "fill": "{{brand.edge}}"
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_signature_label",
      "kind": "text",
      "name": "تسمية التوقيع",
      "frame": {
        "x": 1440,
        "y": 2931,
        "w": 440,
        "h": 96
      },
      "text": {
        "literal": "التوقيع"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "letterSpacing": 0,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    }
  ]
}$json$::jsonb;
v_fields := $fields$["brand.logoAssetId","org.name","recipient.name","certificate.achievementName","certificate.issuedAt","certificate.verifyUrl","certificate.serial","certificate.verificationCode"]$fields$::jsonb;

select t.id into v_template
  from public.design_templates t
 where t.scope = 'platform' and t.purpose = 'certificate' and t.family = 'achievement'
   and t.name = 'شهادة إنجاز عمودية' and t.retired_at is null
 order by t.created_at
 limit 1;

if v_template is null then
  -- Louder than a silent skip: the row this seed amends is 0193's, and if it is
  -- not there the library is not what this file was generated against.
  raise exception 'baseline row missing for % % (%)', 'certificate', 'achievement', 'شهادة إنجاز عمودية';
end if;

-- ADD the version unless this row already carries this exact document, which is
-- what makes a re-run a no-op. Never an UPDATE: a version is immutable
-- (REQ-DSG-007), and version 1 is what a certificate already issued renders as
-- (REQ-CRT-014).
if not exists (
  select 1 from public.design_template_versions v
   where v.template_id = v_template and v.document = v_doc
) then
  insert into public.design_template_versions (template_id, version, document, dynamic_fields, font_hashes, published_at)
  select
    v_template,
    coalesce(max(v.version), 0) + 1,
    v_doc, v_fields,
    -- No font hash is pinned on a platform version: the platform set is
    -- installed by hash in every image (REQ-DSG-016), as 0061 recorded.
    '{}',
    now()
  from public.design_template_versions v
  where v.template_id = v_template;
end if;

end $$;
