-- designer (wave 24, M26) — the baseline library REBUILT to «ساحة اللعب», and the superseded eleven superseded.
-- Follows 0192 (the platform palette) and supersedes 0061 + 0098's rows.
--
-- Serves:  REQ-DSG-033 (the designed poster families), REQ-CRT-016 (the
--          designed certificate families), REQ-DSG-034 (the superseded
--          baseline leaves the library), REQ-DSG-026 as DEC-242 amends it,
--          REQ-DSG-021 (tokens only), REQ-DSG-024 (locked regions),
--          REQ-CRT-010, REQ-CRT-014 (a pinned version still renders)
-- Cites:   DEC-242 §1 (the thumbnails are the specification), §2 (the palette
--          and the token vocabulary), §3 (delete where permitted, retire where
--          refused), §4; DEC-125 (posters dark), DEC-128, DEC-148
--
-- 03 §8.2 ROWS: see `supersede_baseline_template()`'s own file. This file
-- creates no policy and no grant — it inserts rows into two tables 0055
-- already policied, as the owner during migration.
--
-- GENERATED by packages/designer-runtime/scripts/seed-sql.mjs from
-- packages/designer-runtime/src/library.ts. Do not edit by hand:
-- tests/unit/designer-library.test.ts parses every $json$…$json$ back out and
-- deep-equals it against the library.
--
-- ★★ ELEVEN NEW ROWS, NOT NEW VERSIONS OF THE OLD ONES (REQ-DSG-034). Every
-- document in the library changed, so each composition ships as a new platform
-- template at version 1 and the superseded row is deleted — or RETIRED, where
-- `on delete restrict` refuses, because a certificate issued against a 2026
-- version must render as that version for ever (REQ-CRT-014). The migration
-- reports which went which way, per row.
--
-- ★ THE NEW ROW IS INSERTED BEFORE THE OLD ONE IS SUPERSEDED, and the order is
-- load-bearing: `design_templates_single_default` (0057) clears the previous
-- default in the same statement, so by the time the supersede step runs the old
-- row is already non-default — which means issuance and poster_render_context()
-- prefer the new row even before `retired_at` is set, and there is never a
-- window with no non-retired default of a purpose.
--
-- ★ IDEMPOTENT ON THE LIVE ROW, which is 0061's pattern with one necessary
-- third condition: `retired_at is null`. Without it a re-run finds the RETIRED
-- old row and skips the insert — and the portrait lookup, which asks for «the
-- non-default platform row of this family», would match a retired landscape row.

do $$
declare
  v_template uuid;
  -- The eleven rows this file seeds. Everything else in platform scope is
  -- superseded at the end, which is how the step stays id-free.
  v_kept     uuid[] := '{}';
  v_doc      jsonb;
  v_fields   jsonb;
  v_old      record;
  v_outcome  text;
  v_refused  text;
begin

-- @family talk@v1
v_template := null;
v_doc    := $json${
  "schemaVersion": 1,
  "purpose": "poster",
  "master": {
    "width": 1080,
    "height": 1350,
    "unit": "px",
    "dpi": 72
  },
  "direction": "rtl",
  "background": {
    "type": "solid",
    "color": "{{brand.canvas}}"
  },
  "layers": [
    {
      "id": "l_logo",
      "kind": "image",
      "name": "شعار المؤسسة",
      "image": {
        "binding": "brand.logoAssetId",
        "fit": "contain"
      },
      "frame": {
        "x": 880,
        "y": 80,
        "w": 120,
        "h": 120
      },
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "name": "خلفية التصنيف",
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 2,
      "id": "l_pill_start",
      "kind": "shape",
      "frame": {
        "x": 80,
        "y": 80,
        "w": 72,
        "h": 72
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{brand.node}}"
      }
    },
    {
      "name": "خلفية التصنيف",
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 2,
      "id": "l_pill_body",
      "kind": "shape",
      "frame": {
        "x": 116,
        "y": 80,
        "w": 228,
        "h": 72
      },
      "shape": {
        "type": "rect",
        "fill": "{{brand.node}}"
      }
    },
    {
      "name": "خلفية التصنيف",
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 2,
      "id": "l_pill_end",
      "kind": "shape",
      "frame": {
        "x": 308,
        "y": 80,
        "w": 72,
        "h": 72
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{brand.node}}"
      }
    },
    {
      "id": "l_category",
      "kind": "text",
      "name": "التصنيف",
      "frame": {
        "x": 80,
        "y": 80,
        "w": 300,
        "h": 72
      },
      "text": {
        "literal": "جلسة"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 40,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.canvas}}",
      "align": "center",
      "z": 10
    },
    {
      "id": "l_title",
      "kind": "text",
      "name": "عنوان الجلسة",
      "frame": {
        "x": 80,
        "y": 300,
        "w": 920,
        "h": 430
      },
      "text": {
        "binding": "session.title",
        "fallback": "عنوان الجلسة"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 96,
        "minSize": 56,
        "lineHeight": 1.12,
        "letterSpacing": 0,
        "weight": 800
      },
      "color": "{{brand.fgHeading}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 3
      },
      "z": 10
    },
    {
      "id": "l_presenters",
      "kind": "dynamic_field",
      "name": "المقدِّمون",
      "frame": {
        "x": 80,
        "y": 1010,
        "w": 640,
        "h": 130
      },
      "field": {
        "binding": "session.presenters",
        "fallback": "اسم المقدِّم"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 44,
        "minSize": 32,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.fgHeading}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_when",
      "kind": "dynamic_field",
      "name": "الموعد",
      "frame": {
        "x": 80,
        "y": 1150,
        "w": 640,
        "h": 62
      },
      "field": {
        "binding": "session.startsAt",
        "fallback": "التاريخ والوقت"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 40,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.fgHeading}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_qr",
      "kind": "qr",
      "name": "رمز الجلسة",
      "locked": true,
      "frame": {
        "x": 860,
        "y": 1130,
        "w": 140,
        "h": 140
      },
      "qr": {
        "binding": "session.eventUrl",
        "ecLevel": "M",
        "quietZoneModules": 4
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 10
    }
  ]
}$json$::jsonb;
v_fields := $fields$["brand.logoAssetId","session.title","session.presenters","session.startsAt","session.eventUrl"]$fields$::jsonb;

-- The platform row that already carries this document, if this seed has run before.
select t.id into v_template
  from public.design_templates t
  join public.design_template_versions v on v.template_id = t.id
 where t.scope = 'platform' and t.purpose = 'poster' and t.family = 'talk'
   and t.retired_at is null and v.document = v_doc
 order by t.created_at
 limit 1;

if v_template is null then
  -- RETURNING, never a second lookup: a select by (family, name) would match the
  -- SUPERSEDED row, which still carries this family and this name until the
  -- supersede step runs — and would then insert version 1 on a row that already
  -- has one. That is the duplicate key the roster suite raised.
  insert into public.design_templates (org_id, scope, purpose, family, name, is_default)
  values (null, 'platform', 'poster', 'talk', 'جلسة', true)
  returning id into v_template;

  insert into public.design_template_versions (template_id, version, document, dynamic_fields, font_hashes, published_at)
  values (
    v_template, 1, v_doc, v_fields,
    -- No font hash is pinned on a platform version: the platform set is
    -- installed by hash in every image (REQ-DSG-016), as 0061 recorded.
    '{}',
    now()
  );
end if;
v_kept := v_kept || v_template;

-- @family workshop@v1
v_template := null;
v_doc    := $json${
  "schemaVersion": 1,
  "purpose": "poster",
  "master": {
    "width": 1080,
    "height": 1350,
    "unit": "px",
    "dpi": 72
  },
  "direction": "rtl",
  "background": {
    "type": "solid",
    "color": "{{brand.fgHeading}}"
  },
  "layers": [
    {
      "id": "l_logo",
      "kind": "image",
      "name": "شعار المؤسسة",
      "image": {
        "binding": "brand.logoAssetId",
        "fit": "contain"
      },
      "frame": {
        "x": 880,
        "y": 80,
        "w": 120,
        "h": 120
      },
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "name": "خلفية التصنيف",
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 2,
      "id": "l_pill_start",
      "kind": "shape",
      "frame": {
        "x": 80,
        "y": 80,
        "w": 72,
        "h": 72
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{brand.canvas}}"
      }
    },
    {
      "name": "خلفية التصنيف",
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 2,
      "id": "l_pill_body",
      "kind": "shape",
      "frame": {
        "x": 116,
        "y": 80,
        "w": 228,
        "h": 72
      },
      "shape": {
        "type": "rect",
        "fill": "{{brand.canvas}}"
      }
    },
    {
      "name": "خلفية التصنيف",
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 2,
      "id": "l_pill_end",
      "kind": "shape",
      "frame": {
        "x": 308,
        "y": 80,
        "w": 72,
        "h": 72
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{brand.canvas}}"
      }
    },
    {
      "id": "l_category",
      "kind": "text",
      "name": "التصنيف",
      "frame": {
        "x": 80,
        "y": 80,
        "w": 300,
        "h": 72
      },
      "text": {
        "literal": "ورشة"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 40,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.fgHeading}}",
      "align": "center",
      "z": 10
    },
    {
      "id": "l_title",
      "kind": "text",
      "name": "عنوان الجلسة",
      "frame": {
        "x": 80,
        "y": 300,
        "w": 920,
        "h": 430
      },
      "text": {
        "binding": "session.title",
        "fallback": "عنوان الجلسة"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 96,
        "minSize": 56,
        "lineHeight": 1.12,
        "letterSpacing": 0,
        "weight": 800
      },
      "color": "{{brand.canvas}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 3
      },
      "z": 10
    },
    {
      "id": "l_presenters",
      "kind": "dynamic_field",
      "name": "المقدِّمون",
      "frame": {
        "x": 80,
        "y": 1010,
        "w": 640,
        "h": 130
      },
      "field": {
        "binding": "session.presenters",
        "fallback": "اسم المقدِّم"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 44,
        "minSize": 32,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.canvas}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_when",
      "kind": "dynamic_field",
      "name": "الموعد",
      "frame": {
        "x": 80,
        "y": 1150,
        "w": 640,
        "h": 62
      },
      "field": {
        "binding": "session.startsAt",
        "fallback": "التاريخ والوقت"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 40,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.canvas}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_qr",
      "kind": "qr",
      "name": "رمز الجلسة",
      "locked": true,
      "frame": {
        "x": 860,
        "y": 1130,
        "w": 140,
        "h": 140
      },
      "qr": {
        "binding": "session.eventUrl",
        "ecLevel": "M",
        "quietZoneModules": 4
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 10
    }
  ]
}$json$::jsonb;
v_fields := $fields$["brand.logoAssetId","session.title","session.presenters","session.startsAt","session.eventUrl"]$fields$::jsonb;

-- The platform row that already carries this document, if this seed has run before.
select t.id into v_template
  from public.design_templates t
  join public.design_template_versions v on v.template_id = t.id
 where t.scope = 'platform' and t.purpose = 'poster' and t.family = 'workshop'
   and t.retired_at is null and v.document = v_doc
 order by t.created_at
 limit 1;

if v_template is null then
  -- RETURNING, never a second lookup: a select by (family, name) would match the
  -- SUPERSEDED row, which still carries this family and this name until the
  -- supersede step runs — and would then insert version 1 on a row that already
  -- has one. That is the duplicate key the roster suite raised.
  insert into public.design_templates (org_id, scope, purpose, family, name, is_default)
  values (null, 'platform', 'poster', 'workshop', 'ورشة', true)
  returning id into v_template;

  insert into public.design_template_versions (template_id, version, document, dynamic_fields, font_hashes, published_at)
  values (
    v_template, 1, v_doc, v_fields,
    -- No font hash is pinned on a platform version: the platform set is
    -- installed by hash in every image (REQ-DSG-016), as 0061 recorded.
    '{}',
    now()
  );
end if;
v_kept := v_kept || v_template;

-- @family panel@v1
v_template := null;
v_doc    := $json${
  "schemaVersion": 1,
  "purpose": "poster",
  "master": {
    "width": 1080,
    "height": 1350,
    "unit": "px",
    "dpi": 72
  },
  "direction": "rtl",
  "background": {
    "type": "solid",
    "color": "{{brand.surface}}"
  },
  "layers": [
    {
      "id": "l_logo",
      "kind": "image",
      "name": "شعار المؤسسة",
      "image": {
        "binding": "brand.logoAssetId",
        "fit": "contain"
      },
      "frame": {
        "x": 880,
        "y": 80,
        "w": 120,
        "h": 120
      },
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "name": "خلفية التصنيف",
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 2,
      "id": "l_pill_start",
      "kind": "shape",
      "frame": {
        "x": 80,
        "y": 80,
        "w": 72,
        "h": 72
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{brand.node}}"
      }
    },
    {
      "name": "خلفية التصنيف",
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 2,
      "id": "l_pill_body",
      "kind": "shape",
      "frame": {
        "x": 116,
        "y": 80,
        "w": 228,
        "h": 72
      },
      "shape": {
        "type": "rect",
        "fill": "{{brand.node}}"
      }
    },
    {
      "name": "خلفية التصنيف",
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 2,
      "id": "l_pill_end",
      "kind": "shape",
      "frame": {
        "x": 308,
        "y": 80,
        "w": 72,
        "h": 72
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{brand.node}}"
      }
    },
    {
      "id": "l_category",
      "kind": "text",
      "name": "التصنيف",
      "frame": {
        "x": 80,
        "y": 80,
        "w": 300,
        "h": 72
      },
      "text": {
        "literal": "حوار"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 40,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.canvas}}",
      "align": "center",
      "z": 10
    },
    {
      "id": "l_title",
      "kind": "text",
      "name": "عنوان الجلسة",
      "frame": {
        "x": 80,
        "y": 300,
        "w": 920,
        "h": 430
      },
      "text": {
        "binding": "session.title",
        "fallback": "عنوان الجلسة"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 96,
        "minSize": 56,
        "lineHeight": 1.12,
        "letterSpacing": 0,
        "weight": 800
      },
      "color": "{{brand.fgHeading}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 3
      },
      "z": 10
    },
    {
      "id": "l_presenters",
      "kind": "dynamic_field",
      "name": "المقدِّمون",
      "frame": {
        "x": 80,
        "y": 1010,
        "w": 640,
        "h": 130
      },
      "field": {
        "binding": "session.presenters",
        "fallback": "اسم المقدِّم"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 44,
        "minSize": 32,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.fgHeading}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_when",
      "kind": "dynamic_field",
      "name": "الموعد",
      "frame": {
        "x": 80,
        "y": 1150,
        "w": 640,
        "h": 62
      },
      "field": {
        "binding": "session.startsAt",
        "fallback": "التاريخ والوقت"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 40,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.fgHeading}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_qr",
      "kind": "qr",
      "name": "رمز الجلسة",
      "locked": true,
      "frame": {
        "x": 860,
        "y": 1130,
        "w": 140,
        "h": 140
      },
      "qr": {
        "binding": "session.eventUrl",
        "ecLevel": "M",
        "quietZoneModules": 4
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 10
    }
  ]
}$json$::jsonb;
v_fields := $fields$["brand.logoAssetId","session.title","session.presenters","session.startsAt","session.eventUrl"]$fields$::jsonb;

-- The platform row that already carries this document, if this seed has run before.
select t.id into v_template
  from public.design_templates t
  join public.design_template_versions v on v.template_id = t.id
 where t.scope = 'platform' and t.purpose = 'poster' and t.family = 'panel'
   and t.retired_at is null and v.document = v_doc
 order by t.created_at
 limit 1;

if v_template is null then
  -- RETURNING, never a second lookup: a select by (family, name) would match the
  -- SUPERSEDED row, which still carries this family and this name until the
  -- supersede step runs — and would then insert version 1 on a row that already
  -- has one. That is the duplicate key the roster suite raised.
  insert into public.design_templates (org_id, scope, purpose, family, name, is_default)
  values (null, 'platform', 'poster', 'panel', 'حوار', true)
  returning id into v_template;

  insert into public.design_template_versions (template_id, version, document, dynamic_fields, font_hashes, published_at)
  values (
    v_template, 1, v_doc, v_fields,
    -- No font hash is pinned on a platform version: the platform set is
    -- installed by hash in every image (REQ-DSG-016), as 0061 recorded.
    '{}',
    now()
  );
end if;
v_kept := v_kept || v_template;

-- @family meetup@v1
v_template := null;
v_doc    := $json${
  "schemaVersion": 1,
  "purpose": "poster",
  "master": {
    "width": 1080,
    "height": 1350,
    "unit": "px",
    "dpi": 72
  },
  "direction": "rtl",
  "background": {
    "type": "solid",
    "color": "{{brand.canvasRaise}}"
  },
  "layers": [
    {
      "id": "l_logo",
      "kind": "image",
      "name": "شعار المؤسسة",
      "image": {
        "binding": "brand.logoAssetId",
        "fit": "contain"
      },
      "frame": {
        "x": 880,
        "y": 80,
        "w": 120,
        "h": 120
      },
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "name": "خلفية التصنيف",
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 2,
      "id": "l_pill_start",
      "kind": "shape",
      "frame": {
        "x": 80,
        "y": 80,
        "w": 72,
        "h": 72
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{brand.node}}"
      }
    },
    {
      "name": "خلفية التصنيف",
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 2,
      "id": "l_pill_body",
      "kind": "shape",
      "frame": {
        "x": 116,
        "y": 80,
        "w": 228,
        "h": 72
      },
      "shape": {
        "type": "rect",
        "fill": "{{brand.node}}"
      }
    },
    {
      "name": "خلفية التصنيف",
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 2,
      "id": "l_pill_end",
      "kind": "shape",
      "frame": {
        "x": 308,
        "y": 80,
        "w": 72,
        "h": 72
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{brand.node}}"
      }
    },
    {
      "id": "l_category",
      "kind": "text",
      "name": "التصنيف",
      "frame": {
        "x": 80,
        "y": 80,
        "w": 300,
        "h": 72
      },
      "text": {
        "literal": "لقاء"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 40,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.canvas}}",
      "align": "center",
      "z": 10
    },
    {
      "id": "l_title",
      "kind": "text",
      "name": "عنوان الجلسة",
      "frame": {
        "x": 80,
        "y": 300,
        "w": 920,
        "h": 430
      },
      "text": {
        "binding": "session.title",
        "fallback": "عنوان الجلسة"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 96,
        "minSize": 56,
        "lineHeight": 1.12,
        "letterSpacing": 0,
        "weight": 800
      },
      "color": "{{brand.fgHeading}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 3
      },
      "z": 10
    },
    {
      "id": "l_presenters",
      "kind": "dynamic_field",
      "name": "المقدِّمون",
      "frame": {
        "x": 80,
        "y": 1010,
        "w": 640,
        "h": 130
      },
      "field": {
        "binding": "session.presenters",
        "fallback": "اسم المقدِّم"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 44,
        "minSize": 32,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.fgHeading}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_when",
      "kind": "dynamic_field",
      "name": "الموعد",
      "frame": {
        "x": 80,
        "y": 1150,
        "w": 640,
        "h": 62
      },
      "field": {
        "binding": "session.startsAt",
        "fallback": "التاريخ والوقت"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 40,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.fgHeading}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_qr",
      "kind": "qr",
      "name": "رمز الجلسة",
      "locked": true,
      "frame": {
        "x": 860,
        "y": 1130,
        "w": 140,
        "h": 140
      },
      "qr": {
        "binding": "session.eventUrl",
        "ecLevel": "M",
        "quietZoneModules": 4
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 10
    }
  ]
}$json$::jsonb;
v_fields := $fields$["brand.logoAssetId","session.title","session.presenters","session.startsAt","session.eventUrl"]$fields$::jsonb;

-- The platform row that already carries this document, if this seed has run before.
select t.id into v_template
  from public.design_templates t
  join public.design_template_versions v on v.template_id = t.id
 where t.scope = 'platform' and t.purpose = 'poster' and t.family = 'meetup'
   and t.retired_at is null and v.document = v_doc
 order by t.created_at
 limit 1;

if v_template is null then
  -- RETURNING, never a second lookup: a select by (family, name) would match the
  -- SUPERSEDED row, which still carries this family and this name until the
  -- supersede step runs — and would then insert version 1 on a row that already
  -- has one. That is the duplicate key the roster suite raised.
  insert into public.design_templates (org_id, scope, purpose, family, name, is_default)
  values (null, 'platform', 'poster', 'meetup', 'لقاء', true)
  returning id into v_template;

  insert into public.design_template_versions (template_id, version, document, dynamic_fields, font_hashes, published_at)
  values (
    v_template, 1, v_doc, v_fields,
    -- No font hash is pinned on a platform version: the platform set is
    -- installed by hash in every image (REQ-DSG-016), as 0061 recorded.
    '{}',
    now()
  );
end if;
v_kept := v_kept || v_template;

-- @family announcement@v1
v_template := null;
v_doc    := $json${
  "schemaVersion": 1,
  "purpose": "poster",
  "master": {
    "width": 1080,
    "height": 1350,
    "unit": "px",
    "dpi": 72
  },
  "direction": "rtl",
  "background": {
    "type": "solid",
    "color": "{{brand.node}}"
  },
  "layers": [
    {
      "id": "l_logo",
      "kind": "image",
      "name": "شعار المؤسسة",
      "image": {
        "binding": "brand.logoAssetId",
        "fit": "contain"
      },
      "frame": {
        "x": 880,
        "y": 80,
        "w": 120,
        "h": 120
      },
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "name": "خلفية التصنيف",
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 2,
      "id": "l_pill_start",
      "kind": "shape",
      "frame": {
        "x": 80,
        "y": 80,
        "w": 72,
        "h": 72
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{brand.canvas}}"
      }
    },
    {
      "name": "خلفية التصنيف",
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 2,
      "id": "l_pill_body",
      "kind": "shape",
      "frame": {
        "x": 116,
        "y": 80,
        "w": 228,
        "h": 72
      },
      "shape": {
        "type": "rect",
        "fill": "{{brand.canvas}}"
      }
    },
    {
      "name": "خلفية التصنيف",
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 2,
      "id": "l_pill_end",
      "kind": "shape",
      "frame": {
        "x": 308,
        "y": 80,
        "w": 72,
        "h": 72
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{brand.canvas}}"
      }
    },
    {
      "id": "l_category",
      "kind": "text",
      "name": "التصنيف",
      "frame": {
        "x": 80,
        "y": 80,
        "w": 300,
        "h": 72
      },
      "text": {
        "literal": "إعلان"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 40,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.node}}",
      "align": "center",
      "z": 10
    },
    {
      "id": "l_title",
      "kind": "text",
      "name": "عنوان الجلسة",
      "frame": {
        "x": 80,
        "y": 300,
        "w": 920,
        "h": 430
      },
      "text": {
        "binding": "session.title",
        "fallback": "عنوان الجلسة"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 96,
        "minSize": 56,
        "lineHeight": 1.12,
        "letterSpacing": 0,
        "weight": 800
      },
      "color": "{{brand.canvas}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 3
      },
      "z": 10
    },
    {
      "id": "l_presenters",
      "kind": "dynamic_field",
      "name": "المقدِّمون",
      "frame": {
        "x": 80,
        "y": 1010,
        "w": 640,
        "h": 130
      },
      "field": {
        "binding": "session.presenters",
        "fallback": "اسم المقدِّم"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 44,
        "minSize": 32,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.canvas}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_when",
      "kind": "dynamic_field",
      "name": "الموعد",
      "frame": {
        "x": 80,
        "y": 1150,
        "w": 640,
        "h": 62
      },
      "field": {
        "binding": "session.startsAt",
        "fallback": "التاريخ والوقت"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 40,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.canvas}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_qr",
      "kind": "qr",
      "name": "رمز الجلسة",
      "locked": true,
      "frame": {
        "x": 860,
        "y": 1130,
        "w": 140,
        "h": 140
      },
      "qr": {
        "binding": "session.eventUrl",
        "ecLevel": "M",
        "quietZoneModules": 4
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 10
    }
  ]
}$json$::jsonb;
v_fields := $fields$["brand.logoAssetId","session.title","session.presenters","session.startsAt","session.eventUrl"]$fields$::jsonb;

-- The platform row that already carries this document, if this seed has run before.
select t.id into v_template
  from public.design_templates t
  join public.design_template_versions v on v.template_id = t.id
 where t.scope = 'platform' and t.purpose = 'poster' and t.family = 'announcement'
   and t.retired_at is null and v.document = v_doc
 order by t.created_at
 limit 1;

if v_template is null then
  -- RETURNING, never a second lookup: a select by (family, name) would match the
  -- SUPERSEDED row, which still carries this family and this name until the
  -- supersede step runs — and would then insert version 1 on a row that already
  -- has one. That is the duplicate key the roster suite raised.
  insert into public.design_templates (org_id, scope, purpose, family, name, is_default)
  values (null, 'platform', 'poster', 'announcement', 'إعلان', true)
  returning id into v_template;

  insert into public.design_template_versions (template_id, version, document, dynamic_fields, font_hashes, published_at)
  values (
    v_template, 1, v_doc, v_fields,
    -- No font hash is pinned on a platform version: the platform set is
    -- installed by hash in every image (REQ-DSG-016), as 0061 recorded.
    '{}',
    now()
  );
end if;
v_kept := v_kept || v_template;

-- @family attendance@landscape@v1
v_template := null;
v_doc    := $json${
  "schemaVersion": 1,
  "purpose": "certificate",
  "master": {
    "width": 3508,
    "height": 2480,
    "unit": "px",
    "dpi": 300
  },
  "direction": "rtl",
  "background": {
    "type": "solid",
    "color": "{{brand.canvas}}"
  },
  "layers": [
    {
      "id": "l_logo",
      "kind": "image",
      "name": "شعار المؤسسة",
      "image": {
        "binding": "brand.logoAssetId",
        "fit": "contain"
      },
      "frame": {
        "x": 3048,
        "y": 240,
        "w": 220,
        "h": 220
      },
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_org",
      "kind": "dynamic_field",
      "name": "اسم المؤسسة",
      "frame": {
        "x": 240,
        "y": 240,
        "w": 2200,
        "h": 170
      },
      "field": {
        "binding": "org.name",
        "fallback": "اسم المؤسسة"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 120,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.fgHeading}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_kind",
      "kind": "text",
      "name": "نوع الشهادة",
      "frame": {
        "x": 240,
        "y": 430,
        "w": 2200,
        "h": 120
      },
      "text": {
        "literal": "شهادة حضور"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 84,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_recipient",
      "kind": "dynamic_field",
      "name": "اسم المستفيد",
      "frame": {
        "x": 240,
        "y": 640,
        "w": 3028,
        "h": 850
      },
      "field": {
        "binding": "recipient.name",
        "fallback": "اسم المستفيد"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 300,
        "minSize": 150,
        "lineHeight": 1.12,
        "letterSpacing": 0,
        "weight": 800
      },
      "color": "{{brand.fgHeading}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_reason",
      "kind": "dynamic_field",
      "name": "عن الجلسة",
      "frame": {
        "x": 240,
        "y": 1540,
        "w": 3028,
        "h": 260
      },
      "field": {
        "binding": "session.title",
        "fallback": "عنوان الجلسة"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 72,
        "minSize": 48,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgBody}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_issued",
      "kind": "dynamic_field",
      "name": "تاريخ الإصدار",
      "frame": {
        "x": 240,
        "y": 1840,
        "w": 1400,
        "h": 100
      },
      "field": {
        "binding": "certificate.issuedAt",
        "fallback": "تاريخ الإصدار"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_qr",
      "kind": "qr",
      "name": "رمز التحقّق",
      "locked": true,
      "frame": {
        "x": 2948,
        "y": 1920,
        "w": 320,
        "h": 320
      },
      "qr": {
        "binding": "certificate.verifyUrl",
        "ecLevel": "Q",
        "quietZoneModules": 4
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_serial",
      "kind": "dynamic_field",
      "name": "الرقم التسلسلي",
      "locked": true,
      "frame": {
        "x": 240,
        "y": 2020,
        "w": 1400,
        "h": 100
      },
      "field": {
        "binding": "certificate.serial",
        "fallback": "الرقم التسلسلي"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_code",
      "kind": "dynamic_field",
      "name": "رمز التحقّق النصّي",
      "locked": true,
      "frame": {
        "x": 240,
        "y": 2130,
        "w": 1400,
        "h": 100
      },
      "field": {
        "binding": "certificate.verificationCode",
        "fallback": "رمز التحقّق"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_signature",
      "kind": "shape",
      "name": "موضع التوقيع",
      "locked": true,
      "frame": {
        "x": 1900,
        "y": 2120,
        "w": 800,
        "h": 2
      },
      "shape": {
        "type": "rect",
        "fill": "{{brand.edge}}"
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    }
  ]
}$json$::jsonb;
v_fields := $fields$["brand.logoAssetId","org.name","recipient.name","session.title","certificate.issuedAt","certificate.verifyUrl","certificate.serial","certificate.verificationCode"]$fields$::jsonb;

-- The platform row that already carries this document, if this seed has run before.
select t.id into v_template
  from public.design_templates t
  join public.design_template_versions v on v.template_id = t.id
 where t.scope = 'platform' and t.purpose = 'certificate' and t.family = 'attendance'
   and t.retired_at is null and v.document = v_doc
 order by t.created_at
 limit 1;

if v_template is null then
  -- RETURNING, never a second lookup: a select by (family, name) would match the
  -- SUPERSEDED row, which still carries this family and this name until the
  -- supersede step runs — and would then insert version 1 on a row that already
  -- has one. That is the duplicate key the roster suite raised.
  insert into public.design_templates (org_id, scope, purpose, family, name, is_default)
  values (null, 'platform', 'certificate', 'attendance', 'شهادة حضور أفقية', true)
  returning id into v_template;

  insert into public.design_template_versions (template_id, version, document, dynamic_fields, font_hashes, published_at)
  values (
    v_template, 1, v_doc, v_fields,
    -- No font hash is pinned on a platform version: the platform set is
    -- installed by hash in every image (REQ-DSG-016), as 0061 recorded.
    '{}',
    now()
  );
end if;
v_kept := v_kept || v_template;

-- @family attendance@portrait@v1
v_template := null;
v_doc    := $json${
  "schemaVersion": 1,
  "purpose": "certificate",
  "master": {
    "width": 2480,
    "height": 3508,
    "unit": "px",
    "dpi": 300
  },
  "direction": "rtl",
  "background": {
    "type": "solid",
    "color": "{{brand.canvas}}"
  },
  "layers": [
    {
      "id": "l_logo",
      "kind": "image",
      "name": "شعار المؤسسة",
      "image": {
        "binding": "brand.logoAssetId",
        "fit": "contain"
      },
      "frame": {
        "x": 2020,
        "y": 240,
        "w": 220,
        "h": 220
      },
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_org",
      "kind": "dynamic_field",
      "name": "اسم المؤسسة",
      "frame": {
        "x": 240,
        "y": 240,
        "w": 1700,
        "h": 170
      },
      "field": {
        "binding": "org.name",
        "fallback": "اسم المؤسسة"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 120,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.fgHeading}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_kind",
      "kind": "text",
      "name": "نوع الشهادة",
      "frame": {
        "x": 240,
        "y": 430,
        "w": 1700,
        "h": 120
      },
      "text": {
        "literal": "شهادة حضور"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 84,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_recipient",
      "kind": "dynamic_field",
      "name": "اسم المستفيد",
      "frame": {
        "x": 240,
        "y": 700,
        "w": 2000,
        "h": 1000
      },
      "field": {
        "binding": "recipient.name",
        "fallback": "اسم المستفيد"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 300,
        "minSize": 150,
        "lineHeight": 1.12,
        "letterSpacing": 0,
        "weight": 800
      },
      "color": "{{brand.fgHeading}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_reason",
      "kind": "dynamic_field",
      "name": "عن الجلسة",
      "frame": {
        "x": 240,
        "y": 1780,
        "w": 2000,
        "h": 260
      },
      "field": {
        "binding": "session.title",
        "fallback": "عنوان الجلسة"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 72,
        "minSize": 48,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgBody}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_issued",
      "kind": "dynamic_field",
      "name": "تاريخ الإصدار",
      "frame": {
        "x": 240,
        "y": 2100,
        "w": 1300,
        "h": 100
      },
      "field": {
        "binding": "certificate.issuedAt",
        "fallback": "تاريخ الإصدار"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_qr",
      "kind": "qr",
      "name": "رمز التحقّق",
      "locked": true,
      "frame": {
        "x": 1920,
        "y": 2948,
        "w": 320,
        "h": 320
      },
      "qr": {
        "binding": "certificate.verifyUrl",
        "ecLevel": "Q",
        "quietZoneModules": 4
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_serial",
      "kind": "dynamic_field",
      "name": "الرقم التسلسلي",
      "locked": true,
      "frame": {
        "x": 240,
        "y": 2980,
        "w": 1300,
        "h": 100
      },
      "field": {
        "binding": "certificate.serial",
        "fallback": "الرقم التسلسلي"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_code",
      "kind": "dynamic_field",
      "name": "رمز التحقّق النصّي",
      "locked": true,
      "frame": {
        "x": 240,
        "y": 3090,
        "w": 1300,
        "h": 100
      },
      "field": {
        "binding": "certificate.verificationCode",
        "fallback": "رمز التحقّق"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_signature",
      "kind": "shape",
      "name": "موضع التوقيع",
      "locked": true,
      "frame": {
        "x": 1440,
        "y": 2900,
        "w": 800,
        "h": 2
      },
      "shape": {
        "type": "rect",
        "fill": "{{brand.edge}}"
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    }
  ]
}$json$::jsonb;
v_fields := $fields$["brand.logoAssetId","org.name","recipient.name","session.title","certificate.issuedAt","certificate.verifyUrl","certificate.serial","certificate.verificationCode"]$fields$::jsonb;

-- The platform row that already carries this document, if this seed has run before.
select t.id into v_template
  from public.design_templates t
  join public.design_template_versions v on v.template_id = t.id
 where t.scope = 'platform' and t.purpose = 'certificate' and t.family = 'attendance'
   and t.retired_at is null and v.document = v_doc
 order by t.created_at
 limit 1;

if v_template is null then
  -- RETURNING, never a second lookup: a select by (family, name) would match the
  -- SUPERSEDED row, which still carries this family and this name until the
  -- supersede step runs — and would then insert version 1 on a row that already
  -- has one. That is the duplicate key the roster suite raised.
  insert into public.design_templates (org_id, scope, purpose, family, name, is_default)
  values (null, 'platform', 'certificate', 'attendance', 'شهادة حضور عمودية', false)
  returning id into v_template;

  insert into public.design_template_versions (template_id, version, document, dynamic_fields, font_hashes, published_at)
  values (
    v_template, 1, v_doc, v_fields,
    -- No font hash is pinned on a platform version: the platform set is
    -- installed by hash in every image (REQ-DSG-016), as 0061 recorded.
    '{}',
    now()
  );
end if;
v_kept := v_kept || v_template;

-- @family presenter@landscape@v1
v_template := null;
v_doc    := $json${
  "schemaVersion": 1,
  "purpose": "certificate",
  "master": {
    "width": 3508,
    "height": 2480,
    "unit": "px",
    "dpi": 300
  },
  "direction": "rtl",
  "background": {
    "type": "solid",
    "color": "{{brand.canvas}}"
  },
  "layers": [
    {
      "id": "l_logo",
      "kind": "image",
      "name": "شعار المؤسسة",
      "image": {
        "binding": "brand.logoAssetId",
        "fit": "contain"
      },
      "frame": {
        "x": 3048,
        "y": 240,
        "w": 220,
        "h": 220
      },
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_org",
      "kind": "dynamic_field",
      "name": "اسم المؤسسة",
      "frame": {
        "x": 240,
        "y": 240,
        "w": 2200,
        "h": 170
      },
      "field": {
        "binding": "org.name",
        "fallback": "اسم المؤسسة"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 120,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.fgHeading}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_kind",
      "kind": "text",
      "name": "نوع الشهادة",
      "frame": {
        "x": 240,
        "y": 430,
        "w": 2200,
        "h": 120
      },
      "text": {
        "literal": "شهادة تقديم"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 84,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_recipient",
      "kind": "dynamic_field",
      "name": "اسم المستفيد",
      "frame": {
        "x": 240,
        "y": 640,
        "w": 3028,
        "h": 850
      },
      "field": {
        "binding": "recipient.name",
        "fallback": "اسم المستفيد"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 300,
        "minSize": 150,
        "lineHeight": 1.12,
        "letterSpacing": 0,
        "weight": 800
      },
      "color": "{{brand.fgHeading}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_reason",
      "kind": "dynamic_field",
      "name": "عن الجلسة",
      "frame": {
        "x": 240,
        "y": 1540,
        "w": 3028,
        "h": 260
      },
      "field": {
        "binding": "session.title",
        "fallback": "عنوان الجلسة"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 72,
        "minSize": 48,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgBody}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_issued",
      "kind": "dynamic_field",
      "name": "تاريخ الإصدار",
      "frame": {
        "x": 240,
        "y": 1840,
        "w": 1400,
        "h": 100
      },
      "field": {
        "binding": "certificate.issuedAt",
        "fallback": "تاريخ الإصدار"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_qr",
      "kind": "qr",
      "name": "رمز التحقّق",
      "locked": true,
      "frame": {
        "x": 2948,
        "y": 1920,
        "w": 320,
        "h": 320
      },
      "qr": {
        "binding": "certificate.verifyUrl",
        "ecLevel": "Q",
        "quietZoneModules": 4
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_serial",
      "kind": "dynamic_field",
      "name": "الرقم التسلسلي",
      "locked": true,
      "frame": {
        "x": 240,
        "y": 2020,
        "w": 1400,
        "h": 100
      },
      "field": {
        "binding": "certificate.serial",
        "fallback": "الرقم التسلسلي"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_code",
      "kind": "dynamic_field",
      "name": "رمز التحقّق النصّي",
      "locked": true,
      "frame": {
        "x": 240,
        "y": 2130,
        "w": 1400,
        "h": 100
      },
      "field": {
        "binding": "certificate.verificationCode",
        "fallback": "رمز التحقّق"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_signature",
      "kind": "shape",
      "name": "موضع التوقيع",
      "locked": true,
      "frame": {
        "x": 1900,
        "y": 2120,
        "w": 800,
        "h": 2
      },
      "shape": {
        "type": "rect",
        "fill": "{{brand.edge}}"
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    }
  ]
}$json$::jsonb;
v_fields := $fields$["brand.logoAssetId","org.name","recipient.name","session.title","certificate.issuedAt","certificate.verifyUrl","certificate.serial","certificate.verificationCode"]$fields$::jsonb;

-- The platform row that already carries this document, if this seed has run before.
select t.id into v_template
  from public.design_templates t
  join public.design_template_versions v on v.template_id = t.id
 where t.scope = 'platform' and t.purpose = 'certificate' and t.family = 'presenter'
   and t.retired_at is null and v.document = v_doc
 order by t.created_at
 limit 1;

if v_template is null then
  -- RETURNING, never a second lookup: a select by (family, name) would match the
  -- SUPERSEDED row, which still carries this family and this name until the
  -- supersede step runs — and would then insert version 1 on a row that already
  -- has one. That is the duplicate key the roster suite raised.
  insert into public.design_templates (org_id, scope, purpose, family, name, is_default)
  values (null, 'platform', 'certificate', 'presenter', 'شهادة تقديم أفقية', true)
  returning id into v_template;

  insert into public.design_template_versions (template_id, version, document, dynamic_fields, font_hashes, published_at)
  values (
    v_template, 1, v_doc, v_fields,
    -- No font hash is pinned on a platform version: the platform set is
    -- installed by hash in every image (REQ-DSG-016), as 0061 recorded.
    '{}',
    now()
  );
end if;
v_kept := v_kept || v_template;

-- @family presenter@portrait@v1
v_template := null;
v_doc    := $json${
  "schemaVersion": 1,
  "purpose": "certificate",
  "master": {
    "width": 2480,
    "height": 3508,
    "unit": "px",
    "dpi": 300
  },
  "direction": "rtl",
  "background": {
    "type": "solid",
    "color": "{{brand.canvas}}"
  },
  "layers": [
    {
      "id": "l_logo",
      "kind": "image",
      "name": "شعار المؤسسة",
      "image": {
        "binding": "brand.logoAssetId",
        "fit": "contain"
      },
      "frame": {
        "x": 2020,
        "y": 240,
        "w": 220,
        "h": 220
      },
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_org",
      "kind": "dynamic_field",
      "name": "اسم المؤسسة",
      "frame": {
        "x": 240,
        "y": 240,
        "w": 1700,
        "h": 170
      },
      "field": {
        "binding": "org.name",
        "fallback": "اسم المؤسسة"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 120,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.fgHeading}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_kind",
      "kind": "text",
      "name": "نوع الشهادة",
      "frame": {
        "x": 240,
        "y": 430,
        "w": 1700,
        "h": 120
      },
      "text": {
        "literal": "شهادة تقديم"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 84,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_recipient",
      "kind": "dynamic_field",
      "name": "اسم المستفيد",
      "frame": {
        "x": 240,
        "y": 700,
        "w": 2000,
        "h": 1000
      },
      "field": {
        "binding": "recipient.name",
        "fallback": "اسم المستفيد"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 300,
        "minSize": 150,
        "lineHeight": 1.12,
        "letterSpacing": 0,
        "weight": 800
      },
      "color": "{{brand.fgHeading}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_reason",
      "kind": "dynamic_field",
      "name": "عن الجلسة",
      "frame": {
        "x": 240,
        "y": 1780,
        "w": 2000,
        "h": 260
      },
      "field": {
        "binding": "session.title",
        "fallback": "عنوان الجلسة"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 72,
        "minSize": 48,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgBody}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_issued",
      "kind": "dynamic_field",
      "name": "تاريخ الإصدار",
      "frame": {
        "x": 240,
        "y": 2100,
        "w": 1300,
        "h": 100
      },
      "field": {
        "binding": "certificate.issuedAt",
        "fallback": "تاريخ الإصدار"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_qr",
      "kind": "qr",
      "name": "رمز التحقّق",
      "locked": true,
      "frame": {
        "x": 1920,
        "y": 2948,
        "w": 320,
        "h": 320
      },
      "qr": {
        "binding": "certificate.verifyUrl",
        "ecLevel": "Q",
        "quietZoneModules": 4
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_serial",
      "kind": "dynamic_field",
      "name": "الرقم التسلسلي",
      "locked": true,
      "frame": {
        "x": 240,
        "y": 2980,
        "w": 1300,
        "h": 100
      },
      "field": {
        "binding": "certificate.serial",
        "fallback": "الرقم التسلسلي"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_code",
      "kind": "dynamic_field",
      "name": "رمز التحقّق النصّي",
      "locked": true,
      "frame": {
        "x": 240,
        "y": 3090,
        "w": 1300,
        "h": 100
      },
      "field": {
        "binding": "certificate.verificationCode",
        "fallback": "رمز التحقّق"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_signature",
      "kind": "shape",
      "name": "موضع التوقيع",
      "locked": true,
      "frame": {
        "x": 1440,
        "y": 2900,
        "w": 800,
        "h": 2
      },
      "shape": {
        "type": "rect",
        "fill": "{{brand.edge}}"
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    }
  ]
}$json$::jsonb;
v_fields := $fields$["brand.logoAssetId","org.name","recipient.name","session.title","certificate.issuedAt","certificate.verifyUrl","certificate.serial","certificate.verificationCode"]$fields$::jsonb;

-- The platform row that already carries this document, if this seed has run before.
select t.id into v_template
  from public.design_templates t
  join public.design_template_versions v on v.template_id = t.id
 where t.scope = 'platform' and t.purpose = 'certificate' and t.family = 'presenter'
   and t.retired_at is null and v.document = v_doc
 order by t.created_at
 limit 1;

if v_template is null then
  -- RETURNING, never a second lookup: a select by (family, name) would match the
  -- SUPERSEDED row, which still carries this family and this name until the
  -- supersede step runs — and would then insert version 1 on a row that already
  -- has one. That is the duplicate key the roster suite raised.
  insert into public.design_templates (org_id, scope, purpose, family, name, is_default)
  values (null, 'platform', 'certificate', 'presenter', 'شهادة تقديم عمودية', false)
  returning id into v_template;

  insert into public.design_template_versions (template_id, version, document, dynamic_fields, font_hashes, published_at)
  values (
    v_template, 1, v_doc, v_fields,
    -- No font hash is pinned on a platform version: the platform set is
    -- installed by hash in every image (REQ-DSG-016), as 0061 recorded.
    '{}',
    now()
  );
end if;
v_kept := v_kept || v_template;

-- @family achievement@landscape@v1
v_template := null;
v_doc    := $json${
  "schemaVersion": 1,
  "purpose": "certificate",
  "master": {
    "width": 3508,
    "height": 2480,
    "unit": "px",
    "dpi": 300
  },
  "direction": "rtl",
  "background": {
    "type": "solid",
    "color": "{{brand.canvas}}"
  },
  "layers": [
    {
      "id": "l_logo",
      "kind": "image",
      "name": "شعار المؤسسة",
      "image": {
        "binding": "brand.logoAssetId",
        "fit": "contain"
      },
      "frame": {
        "x": 3048,
        "y": 240,
        "w": 220,
        "h": 220
      },
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_org",
      "kind": "dynamic_field",
      "name": "اسم المؤسسة",
      "frame": {
        "x": 240,
        "y": 240,
        "w": 2200,
        "h": 170
      },
      "field": {
        "binding": "org.name",
        "fallback": "اسم المؤسسة"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 120,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.fgHeading}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_kind",
      "kind": "text",
      "name": "نوع الشهادة",
      "frame": {
        "x": 240,
        "y": 430,
        "w": 2200,
        "h": 120
      },
      "text": {
        "literal": "شهادة إنجاز"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 84,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_recipient",
      "kind": "dynamic_field",
      "name": "اسم المستفيد",
      "frame": {
        "x": 240,
        "y": 640,
        "w": 3028,
        "h": 850
      },
      "field": {
        "binding": "recipient.name",
        "fallback": "اسم المستفيد"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 300,
        "minSize": 150,
        "lineHeight": 1.12,
        "letterSpacing": 0,
        "weight": 800
      },
      "color": "{{brand.fgHeading}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_reason",
      "kind": "dynamic_field",
      "name": "عن الجلسة",
      "frame": {
        "x": 240,
        "y": 1540,
        "w": 3028,
        "h": 260
      },
      "field": {
        "binding": "certificate.achievementName",
        "fallback": "اسم الإنجاز"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 72,
        "minSize": 48,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgBody}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_issued",
      "kind": "dynamic_field",
      "name": "تاريخ الإصدار",
      "frame": {
        "x": 240,
        "y": 1840,
        "w": 1400,
        "h": 100
      },
      "field": {
        "binding": "certificate.issuedAt",
        "fallback": "تاريخ الإصدار"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_qr",
      "kind": "qr",
      "name": "رمز التحقّق",
      "locked": true,
      "frame": {
        "x": 2948,
        "y": 1920,
        "w": 320,
        "h": 320
      },
      "qr": {
        "binding": "certificate.verifyUrl",
        "ecLevel": "Q",
        "quietZoneModules": 4
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_serial",
      "kind": "dynamic_field",
      "name": "الرقم التسلسلي",
      "locked": true,
      "frame": {
        "x": 240,
        "y": 2020,
        "w": 1400,
        "h": 100
      },
      "field": {
        "binding": "certificate.serial",
        "fallback": "الرقم التسلسلي"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_code",
      "kind": "dynamic_field",
      "name": "رمز التحقّق النصّي",
      "locked": true,
      "frame": {
        "x": 240,
        "y": 2130,
        "w": 1400,
        "h": 100
      },
      "field": {
        "binding": "certificate.verificationCode",
        "fallback": "رمز التحقّق"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_signature",
      "kind": "shape",
      "name": "موضع التوقيع",
      "locked": true,
      "frame": {
        "x": 1900,
        "y": 2120,
        "w": 800,
        "h": 2
      },
      "shape": {
        "type": "rect",
        "fill": "{{brand.edge}}"
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    }
  ]
}$json$::jsonb;
v_fields := $fields$["brand.logoAssetId","org.name","recipient.name","certificate.achievementName","certificate.issuedAt","certificate.verifyUrl","certificate.serial","certificate.verificationCode"]$fields$::jsonb;

-- The platform row that already carries this document, if this seed has run before.
select t.id into v_template
  from public.design_templates t
  join public.design_template_versions v on v.template_id = t.id
 where t.scope = 'platform' and t.purpose = 'certificate' and t.family = 'achievement'
   and t.retired_at is null and v.document = v_doc
 order by t.created_at
 limit 1;

if v_template is null then
  -- RETURNING, never a second lookup: a select by (family, name) would match the
  -- SUPERSEDED row, which still carries this family and this name until the
  -- supersede step runs — and would then insert version 1 on a row that already
  -- has one. That is the duplicate key the roster suite raised.
  insert into public.design_templates (org_id, scope, purpose, family, name, is_default)
  values (null, 'platform', 'certificate', 'achievement', 'شهادة إنجاز أفقية', true)
  returning id into v_template;

  insert into public.design_template_versions (template_id, version, document, dynamic_fields, font_hashes, published_at)
  values (
    v_template, 1, v_doc, v_fields,
    -- No font hash is pinned on a platform version: the platform set is
    -- installed by hash in every image (REQ-DSG-016), as 0061 recorded.
    '{}',
    now()
  );
end if;
v_kept := v_kept || v_template;

-- @family achievement@portrait@v1
v_template := null;
v_doc    := $json${
  "schemaVersion": 1,
  "purpose": "certificate",
  "master": {
    "width": 2480,
    "height": 3508,
    "unit": "px",
    "dpi": 300
  },
  "direction": "rtl",
  "background": {
    "type": "solid",
    "color": "{{brand.canvas}}"
  },
  "layers": [
    {
      "id": "l_logo",
      "kind": "image",
      "name": "شعار المؤسسة",
      "image": {
        "binding": "brand.logoAssetId",
        "fit": "contain"
      },
      "frame": {
        "x": 2020,
        "y": 240,
        "w": 220,
        "h": 220
      },
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_org",
      "kind": "dynamic_field",
      "name": "اسم المؤسسة",
      "frame": {
        "x": 240,
        "y": 240,
        "w": 1700,
        "h": 170
      },
      "field": {
        "binding": "org.name",
        "fallback": "اسم المؤسسة"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 120,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.fgHeading}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_kind",
      "kind": "text",
      "name": "نوع الشهادة",
      "frame": {
        "x": 240,
        "y": 430,
        "w": 1700,
        "h": 120
      },
      "text": {
        "literal": "شهادة إنجاز"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 84,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_recipient",
      "kind": "dynamic_field",
      "name": "اسم المستفيد",
      "frame": {
        "x": 240,
        "y": 700,
        "w": 2000,
        "h": 1000
      },
      "field": {
        "binding": "recipient.name",
        "fallback": "اسم المستفيد"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 300,
        "minSize": 150,
        "lineHeight": 1.12,
        "letterSpacing": 0,
        "weight": 800
      },
      "color": "{{brand.fgHeading}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_reason",
      "kind": "dynamic_field",
      "name": "عن الجلسة",
      "frame": {
        "x": 240,
        "y": 1780,
        "w": 2000,
        "h": 260
      },
      "field": {
        "binding": "certificate.achievementName",
        "fallback": "اسم الإنجاز"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 72,
        "minSize": 48,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgBody}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_issued",
      "kind": "dynamic_field",
      "name": "تاريخ الإصدار",
      "frame": {
        "x": 240,
        "y": 2100,
        "w": 1300,
        "h": 100
      },
      "field": {
        "binding": "certificate.issuedAt",
        "fallback": "تاريخ الإصدار"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_qr",
      "kind": "qr",
      "name": "رمز التحقّق",
      "locked": true,
      "frame": {
        "x": 1920,
        "y": 2948,
        "w": 320,
        "h": 320
      },
      "qr": {
        "binding": "certificate.verifyUrl",
        "ecLevel": "Q",
        "quietZoneModules": 4
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_serial",
      "kind": "dynamic_field",
      "name": "الرقم التسلسلي",
      "locked": true,
      "frame": {
        "x": 240,
        "y": 2980,
        "w": 1300,
        "h": 100
      },
      "field": {
        "binding": "certificate.serial",
        "fallback": "الرقم التسلسلي"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_code",
      "kind": "dynamic_field",
      "name": "رمز التحقّق النصّي",
      "locked": true,
      "frame": {
        "x": 240,
        "y": 3090,
        "w": 1300,
        "h": 100
      },
      "field": {
        "binding": "certificate.verificationCode",
        "fallback": "رمز التحقّق"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_signature",
      "kind": "shape",
      "name": "موضع التوقيع",
      "locked": true,
      "frame": {
        "x": 1440,
        "y": 2900,
        "w": 800,
        "h": 2
      },
      "shape": {
        "type": "rect",
        "fill": "{{brand.edge}}"
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    }
  ]
}$json$::jsonb;
v_fields := $fields$["brand.logoAssetId","org.name","recipient.name","certificate.achievementName","certificate.issuedAt","certificate.verifyUrl","certificate.serial","certificate.verificationCode"]$fields$::jsonb;

-- The platform row that already carries this document, if this seed has run before.
select t.id into v_template
  from public.design_templates t
  join public.design_template_versions v on v.template_id = t.id
 where t.scope = 'platform' and t.purpose = 'certificate' and t.family = 'achievement'
   and t.retired_at is null and v.document = v_doc
 order by t.created_at
 limit 1;

if v_template is null then
  -- RETURNING, never a second lookup: a select by (family, name) would match the
  -- SUPERSEDED row, which still carries this family and this name until the
  -- supersede step runs — and would then insert version 1 on a row that already
  -- has one. That is the duplicate key the roster suite raised.
  insert into public.design_templates (org_id, scope, purpose, family, name, is_default)
  values (null, 'platform', 'certificate', 'achievement', 'شهادة إنجاز عمودية', false)
  returning id into v_template;

  insert into public.design_template_versions (template_id, version, document, dynamic_fields, font_hashes, published_at)
  values (
    v_template, 1, v_doc, v_fields,
    -- No font hash is pinned on a platform version: the platform set is
    -- installed by hash in every image (REQ-DSG-016), as 0061 recorded.
    '{}',
    now()
  );
end if;
v_kept := v_kept || v_template;

-- ★ The eleven are seeded. Everything else in platform scope is superseded.

-- @supersede
for v_old in
  select t.id, t.purpose::text as purpose, t.family, t.name
    from public.design_templates t
   where t.scope = 'platform' and t.retired_at is null and t.id <> all(v_kept)
   order by t.purpose, t.family, t.created_at
loop
  select s.outcome, s.refused_by into v_outcome, v_refused
    from public.supersede_baseline_template(v_old.id) s;
  raise notice 'supersede % % % (%) -> % %',
    v_old.purpose, v_old.family, v_old.name, v_old.id, v_outcome, coalesce(v_refused, '');
end loop;

end $$;
