-- designer (wave 27, M29) — an org owns its templates: the baseline library as a SEED every org
-- receives as its own rows. Generated; the lead promotes it as the first part of M1.
--
-- Serves:  REQ-DSG-035 (an organisation owns its templates from the day it is created),
--          REQ-DSG-026 as DEC-254 §3 amends it (the roster is counted per org),
--          REQ-DSG-007 (a published version is immutable), REQ-CRT-015 (one default per kind)
-- Cites:   DEC-254 §3.1 · DEC-255 §5–§6 (the sync-1 rulings) · DEC-148 · DEC-176
--
-- 03 §8.2 ROWS THIS FILE NEEDS:
--   | `RPC-seed_org_templates.set` | An org holds the eleven compositions as its own published v1 rows: five poster families, three certificate families × landscape and portrait, one default per (purpose, family) — every poster and the landscape certificates. |
--   | `RPC-seed_org_templates.idempotent` | A second call inserts nothing and returns 0; a retired seeded row is not re-seeded. |
--   | `RPC-seed_org_templates.keeps_defaults` | An org's own live default of a (purpose, family) is not demoted. |
--   | `RPC-seed_org_templates.not_callable` | No role may execute it: owner-only, invisible through PostgREST. |
--
-- GENERATED by packages/designer-runtime/scripts/seed-sql.mjs from
-- packages/designer-runtime/src/library.ts. Do not edit by hand:
-- tests/unit/designer-library.test.ts parses every $json$…$json$ back out and
-- deep-equals it against the library.
--
-- ★ THE MARKER CARRIES THE LIBRARY'S VERSION (`@v2`), THE ROW CARRIES VERSION 1. The marker names WHICH
-- library document this is — the same document 0196 stored as platform v2 — so the roster unit's
-- «the newest file wins» comparison holds unchanged. The row is a new template of the org's, and a new
-- template's first version is 1; the platform's numbering means nothing on it.
--
-- ★ NO PARITY GOLDEN MOVES (DEC-176). Every document below is byte-identical to the platform row's latest
-- version it replaces — the same library object, serialised the same way — and no golden reads the
-- database in any case: the harness renders from BASELINE_LIBRARY in memory.
--
-- ★ AUDITED, AND TRUTHFULLY: each inserted template fires 0191's `design_template.created`, with no
-- session, so the actor is null and the role `system` (write_audit, 0005:33-34). Eleven rows per org
-- (DEC-255, D7). The v1 versions write nothing (0191:76).
--
-- ★ WHAT IS NOT SET: `created_by`, `published_by`, `description`, `duplicated_from` — no member made
-- these, and a provenance link to a platform row that is about to be deleted would only be nulled by
-- `on delete set null` (0055:84). `font_hashes` and `safe_areas` are '{}', as on every platform row
-- (issuance pins fonts from the worker, 0127:282).

create or replace function public.seed_org_templates(p_org uuid)
returns integer
language plpgsql security definer set search_path = '' as $seed$
declare
  v_template uuid;
  v_doc      jsonb;
  v_fields   jsonb;
  v_n        integer := 0;
begin
  if not exists (select 1 from public.orgs o where o.id = p_org) then
    raise exception 'unknown_org' using errcode = '42704';
  end if;

-- @family talk@v2
v_doc    := $json${
  "schemaVersion": 1,
  "purpose": "poster",
  "master": {
    "width": 1080,
    "height": 1350,
    "unit": "px",
    "dpi": 72
  },
  "direction": "rtl",
  "background": {
    "type": "solid",
    "color": "{{design.tangerine}}"
  },
  "layers": [
    {
      "id": "l_logo",
      "kind": "image",
      "name": "شعار المؤسسة",
      "image": {
        "binding": "brand.logoAssetId",
        "fit": "contain"
      },
      "frame": {
        "x": 880,
        "y": 80,
        "w": 120,
        "h": 120
      },
      "presets": {
        "default": {
          "anchor": "block-start",
          "inlineAnchor": "end",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "name": "خلفية التصنيف",
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 2,
      "id": "l_pill_start",
      "kind": "shape",
      "frame": {
        "x": 80,
        "y": 80,
        "w": 72,
        "h": 72
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{design.ink}}"
      }
    },
    {
      "name": "خلفية التصنيف",
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 2,
      "id": "l_pill_body",
      "kind": "shape",
      "frame": {
        "x": 116,
        "y": 80,
        "w": 228,
        "h": 72
      },
      "shape": {
        "type": "rect",
        "fill": "{{design.ink}}"
      }
    },
    {
      "name": "خلفية التصنيف",
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 2,
      "id": "l_pill_end",
      "kind": "shape",
      "frame": {
        "x": 308,
        "y": 80,
        "w": 72,
        "h": 72
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{design.ink}}"
      }
    },
    {
      "id": "l_category",
      "kind": "text",
      "name": "التصنيف",
      "frame": {
        "x": 80,
        "y": 80,
        "w": 300,
        "h": 72
      },
      "text": {
        "literal": "جلسة"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 40,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{design.tangerine}}",
      "align": "center",
      "z": 10
    },
    {
      "id": "l_title",
      "kind": "text",
      "name": "عنوان الجلسة",
      "frame": {
        "x": 80,
        "y": 300,
        "w": 920,
        "h": 430
      },
      "text": {
        "binding": "session.title",
        "fallback": "عنوان الجلسة"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 96,
        "minSize": 56,
        "lineHeight": 1.12,
        "letterSpacing": 0,
        "weight": 800
      },
      "color": "{{design.ink}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 3
      },
      "z": 10
    },
    {
      "id": "l_presenters",
      "kind": "dynamic_field",
      "name": "المقدِّمون",
      "frame": {
        "x": 80,
        "y": 1010,
        "w": 640,
        "h": 130
      },
      "field": {
        "binding": "session.presenters",
        "fallback": "اسم المقدِّم"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 44,
        "minSize": 32,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{design.ink}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_when",
      "kind": "dynamic_field",
      "name": "الموعد",
      "frame": {
        "x": 80,
        "y": 1150,
        "w": 640,
        "h": 62
      },
      "field": {
        "binding": "session.startsAt",
        "fallback": "التاريخ والوقت"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 40,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{design.ink}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_qr",
      "kind": "qr",
      "name": "رمز الجلسة",
      "locked": true,
      "frame": {
        "x": 860,
        "y": 1130,
        "w": 140,
        "h": 140
      },
      "qr": {
        "binding": "session.eventUrl",
        "ecLevel": "M",
        "quietZoneModules": 4
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "inlineAnchor": "end",
          "scale": "proportional"
        }
      },
      "z": 10
    }
  ]
}$json$::jsonb;
v_fields := $fields$["brand.logoAssetId","session.title","session.presenters","session.startsAt","session.eventUrl"]$fields$::jsonb;

if not exists (
    select 1 from public.design_templates t
     where t.org_id = p_org and t.purpose = 'poster' and t.family = 'talk'
  ) then
  -- RETURNING, never a second lookup: a lookup by (family, name) is how 0193 once
  -- matched the wrong row and inserted a second version 1 (0193:450-453).
  insert into public.design_templates (org_id, scope, purpose, family, name, is_default)
  values (
    p_org, 'org', 'poster', 'talk', 'جلسة',
    not exists (
      select 1 from public.design_templates d
       where d.org_id = p_org and d.purpose = 'poster' and d.family = 'talk'
         and d.is_default and d.retired_at is null
    )
  )
  returning id into v_template;

  insert into public.design_template_versions (template_id, version, document, dynamic_fields, font_hashes, published_at)
  values (v_template, 1, v_doc, v_fields, '{}', now());
  v_n := v_n + 1;
end if;

-- @family workshop@v2
v_doc    := $json${
  "schemaVersion": 1,
  "purpose": "poster",
  "master": {
    "width": 1080,
    "height": 1350,
    "unit": "px",
    "dpi": 72
  },
  "direction": "rtl",
  "background": {
    "type": "solid",
    "color": "{{design.lime}}"
  },
  "layers": [
    {
      "id": "l_logo",
      "kind": "image",
      "name": "شعار المؤسسة",
      "image": {
        "binding": "brand.logoAssetId",
        "fit": "contain"
      },
      "frame": {
        "x": 880,
        "y": 80,
        "w": 120,
        "h": 120
      },
      "presets": {
        "default": {
          "anchor": "block-start",
          "inlineAnchor": "end",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "name": "خلفية التصنيف",
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 2,
      "id": "l_pill_start",
      "kind": "shape",
      "frame": {
        "x": 80,
        "y": 80,
        "w": 72,
        "h": 72
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{design.ink}}"
      }
    },
    {
      "name": "خلفية التصنيف",
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 2,
      "id": "l_pill_body",
      "kind": "shape",
      "frame": {
        "x": 116,
        "y": 80,
        "w": 228,
        "h": 72
      },
      "shape": {
        "type": "rect",
        "fill": "{{design.ink}}"
      }
    },
    {
      "name": "خلفية التصنيف",
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 2,
      "id": "l_pill_end",
      "kind": "shape",
      "frame": {
        "x": 308,
        "y": 80,
        "w": 72,
        "h": 72
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{design.ink}}"
      }
    },
    {
      "id": "l_category",
      "kind": "text",
      "name": "التصنيف",
      "frame": {
        "x": 80,
        "y": 80,
        "w": 300,
        "h": 72
      },
      "text": {
        "literal": "ورشة"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 40,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{design.lime}}",
      "align": "center",
      "z": 10
    },
    {
      "id": "l_title",
      "kind": "text",
      "name": "عنوان الجلسة",
      "frame": {
        "x": 80,
        "y": 300,
        "w": 920,
        "h": 430
      },
      "text": {
        "binding": "session.title",
        "fallback": "عنوان الجلسة"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 96,
        "minSize": 56,
        "lineHeight": 1.12,
        "letterSpacing": 0,
        "weight": 800
      },
      "color": "{{design.ink}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 3
      },
      "z": 10
    },
    {
      "id": "l_presenters",
      "kind": "dynamic_field",
      "name": "المقدِّمون",
      "frame": {
        "x": 80,
        "y": 1010,
        "w": 640,
        "h": 130
      },
      "field": {
        "binding": "session.presenters",
        "fallback": "اسم المقدِّم"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 44,
        "minSize": 32,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{design.ink}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_when",
      "kind": "dynamic_field",
      "name": "الموعد",
      "frame": {
        "x": 80,
        "y": 1150,
        "w": 640,
        "h": 62
      },
      "field": {
        "binding": "session.startsAt",
        "fallback": "التاريخ والوقت"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 40,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{design.ink}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_qr",
      "kind": "qr",
      "name": "رمز الجلسة",
      "locked": true,
      "frame": {
        "x": 860,
        "y": 1130,
        "w": 140,
        "h": 140
      },
      "qr": {
        "binding": "session.eventUrl",
        "ecLevel": "M",
        "quietZoneModules": 4
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "inlineAnchor": "end",
          "scale": "proportional"
        }
      },
      "z": 10
    }
  ]
}$json$::jsonb;
v_fields := $fields$["brand.logoAssetId","session.title","session.presenters","session.startsAt","session.eventUrl"]$fields$::jsonb;

if not exists (
    select 1 from public.design_templates t
     where t.org_id = p_org and t.purpose = 'poster' and t.family = 'workshop'
  ) then
  -- RETURNING, never a second lookup: a lookup by (family, name) is how 0193 once
  -- matched the wrong row and inserted a second version 1 (0193:450-453).
  insert into public.design_templates (org_id, scope, purpose, family, name, is_default)
  values (
    p_org, 'org', 'poster', 'workshop', 'ورشة',
    not exists (
      select 1 from public.design_templates d
       where d.org_id = p_org and d.purpose = 'poster' and d.family = 'workshop'
         and d.is_default and d.retired_at is null
    )
  )
  returning id into v_template;

  insert into public.design_template_versions (template_id, version, document, dynamic_fields, font_hashes, published_at)
  values (v_template, 1, v_doc, v_fields, '{}', now());
  v_n := v_n + 1;
end if;

-- @family panel@v2
v_doc    := $json${
  "schemaVersion": 1,
  "purpose": "poster",
  "master": {
    "width": 1080,
    "height": 1350,
    "unit": "px",
    "dpi": 72
  },
  "direction": "rtl",
  "background": {
    "type": "solid",
    "color": "{{design.coral}}"
  },
  "layers": [
    {
      "id": "l_logo",
      "kind": "image",
      "name": "شعار المؤسسة",
      "image": {
        "binding": "brand.logoAssetId",
        "fit": "contain"
      },
      "frame": {
        "x": 880,
        "y": 80,
        "w": 120,
        "h": 120
      },
      "presets": {
        "default": {
          "anchor": "block-start",
          "inlineAnchor": "end",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "name": "خلفية التصنيف",
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 2,
      "id": "l_pill_start",
      "kind": "shape",
      "frame": {
        "x": 80,
        "y": 80,
        "w": 72,
        "h": 72
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{design.ink}}"
      }
    },
    {
      "name": "خلفية التصنيف",
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 2,
      "id": "l_pill_body",
      "kind": "shape",
      "frame": {
        "x": 116,
        "y": 80,
        "w": 228,
        "h": 72
      },
      "shape": {
        "type": "rect",
        "fill": "{{design.ink}}"
      }
    },
    {
      "name": "خلفية التصنيف",
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 2,
      "id": "l_pill_end",
      "kind": "shape",
      "frame": {
        "x": 308,
        "y": 80,
        "w": 72,
        "h": 72
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{design.ink}}"
      }
    },
    {
      "id": "l_category",
      "kind": "text",
      "name": "التصنيف",
      "frame": {
        "x": 80,
        "y": 80,
        "w": 300,
        "h": 72
      },
      "text": {
        "literal": "حوار"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 40,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{design.coral}}",
      "align": "center",
      "z": 10
    },
    {
      "id": "l_title",
      "kind": "text",
      "name": "عنوان الجلسة",
      "frame": {
        "x": 80,
        "y": 300,
        "w": 920,
        "h": 430
      },
      "text": {
        "binding": "session.title",
        "fallback": "عنوان الجلسة"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 96,
        "minSize": 56,
        "lineHeight": 1.12,
        "letterSpacing": 0,
        "weight": 800
      },
      "color": "{{design.ink}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 3
      },
      "z": 10
    },
    {
      "id": "l_presenters",
      "kind": "dynamic_field",
      "name": "المقدِّمون",
      "frame": {
        "x": 80,
        "y": 1010,
        "w": 640,
        "h": 130
      },
      "field": {
        "binding": "session.presenters",
        "fallback": "اسم المقدِّم"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 44,
        "minSize": 32,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{design.ink}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_when",
      "kind": "dynamic_field",
      "name": "الموعد",
      "frame": {
        "x": 80,
        "y": 1150,
        "w": 640,
        "h": 62
      },
      "field": {
        "binding": "session.startsAt",
        "fallback": "التاريخ والوقت"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 40,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{design.ink}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_qr",
      "kind": "qr",
      "name": "رمز الجلسة",
      "locked": true,
      "frame": {
        "x": 860,
        "y": 1130,
        "w": 140,
        "h": 140
      },
      "qr": {
        "binding": "session.eventUrl",
        "ecLevel": "M",
        "quietZoneModules": 4
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "inlineAnchor": "end",
          "scale": "proportional"
        }
      },
      "z": 10
    }
  ]
}$json$::jsonb;
v_fields := $fields$["brand.logoAssetId","session.title","session.presenters","session.startsAt","session.eventUrl"]$fields$::jsonb;

if not exists (
    select 1 from public.design_templates t
     where t.org_id = p_org and t.purpose = 'poster' and t.family = 'panel'
  ) then
  -- RETURNING, never a second lookup: a lookup by (family, name) is how 0193 once
  -- matched the wrong row and inserted a second version 1 (0193:450-453).
  insert into public.design_templates (org_id, scope, purpose, family, name, is_default)
  values (
    p_org, 'org', 'poster', 'panel', 'حوار',
    not exists (
      select 1 from public.design_templates d
       where d.org_id = p_org and d.purpose = 'poster' and d.family = 'panel'
         and d.is_default and d.retired_at is null
    )
  )
  returning id into v_template;

  insert into public.design_template_versions (template_id, version, document, dynamic_fields, font_hashes, published_at)
  values (v_template, 1, v_doc, v_fields, '{}', now());
  v_n := v_n + 1;
end if;

-- @family meetup@v2
v_doc    := $json${
  "schemaVersion": 1,
  "purpose": "poster",
  "master": {
    "width": 1080,
    "height": 1350,
    "unit": "px",
    "dpi": 72
  },
  "direction": "rtl",
  "background": {
    "type": "solid",
    "color": "{{design.cyan}}"
  },
  "layers": [
    {
      "id": "l_logo",
      "kind": "image",
      "name": "شعار المؤسسة",
      "image": {
        "binding": "brand.logoAssetId",
        "fit": "contain"
      },
      "frame": {
        "x": 880,
        "y": 80,
        "w": 120,
        "h": 120
      },
      "presets": {
        "default": {
          "anchor": "block-start",
          "inlineAnchor": "end",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "name": "خلفية التصنيف",
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 2,
      "id": "l_pill_start",
      "kind": "shape",
      "frame": {
        "x": 80,
        "y": 80,
        "w": 72,
        "h": 72
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{design.ink}}"
      }
    },
    {
      "name": "خلفية التصنيف",
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 2,
      "id": "l_pill_body",
      "kind": "shape",
      "frame": {
        "x": 116,
        "y": 80,
        "w": 228,
        "h": 72
      },
      "shape": {
        "type": "rect",
        "fill": "{{design.ink}}"
      }
    },
    {
      "name": "خلفية التصنيف",
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 2,
      "id": "l_pill_end",
      "kind": "shape",
      "frame": {
        "x": 308,
        "y": 80,
        "w": 72,
        "h": 72
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{design.ink}}"
      }
    },
    {
      "id": "l_category",
      "kind": "text",
      "name": "التصنيف",
      "frame": {
        "x": 80,
        "y": 80,
        "w": 300,
        "h": 72
      },
      "text": {
        "literal": "لقاء"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 40,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{design.cyan}}",
      "align": "center",
      "z": 10
    },
    {
      "id": "l_title",
      "kind": "text",
      "name": "عنوان الجلسة",
      "frame": {
        "x": 80,
        "y": 300,
        "w": 920,
        "h": 430
      },
      "text": {
        "binding": "session.title",
        "fallback": "عنوان الجلسة"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 96,
        "minSize": 56,
        "lineHeight": 1.12,
        "letterSpacing": 0,
        "weight": 800
      },
      "color": "{{design.ink}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 3
      },
      "z": 10
    },
    {
      "id": "l_presenters",
      "kind": "dynamic_field",
      "name": "المقدِّمون",
      "frame": {
        "x": 80,
        "y": 1010,
        "w": 640,
        "h": 130
      },
      "field": {
        "binding": "session.presenters",
        "fallback": "اسم المقدِّم"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 44,
        "minSize": 32,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{design.ink}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_when",
      "kind": "dynamic_field",
      "name": "الموعد",
      "frame": {
        "x": 80,
        "y": 1150,
        "w": 640,
        "h": 62
      },
      "field": {
        "binding": "session.startsAt",
        "fallback": "التاريخ والوقت"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 40,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{design.ink}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_qr",
      "kind": "qr",
      "name": "رمز الجلسة",
      "locked": true,
      "frame": {
        "x": 860,
        "y": 1130,
        "w": 140,
        "h": 140
      },
      "qr": {
        "binding": "session.eventUrl",
        "ecLevel": "M",
        "quietZoneModules": 4
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "inlineAnchor": "end",
          "scale": "proportional"
        }
      },
      "z": 10
    }
  ]
}$json$::jsonb;
v_fields := $fields$["brand.logoAssetId","session.title","session.presenters","session.startsAt","session.eventUrl"]$fields$::jsonb;

if not exists (
    select 1 from public.design_templates t
     where t.org_id = p_org and t.purpose = 'poster' and t.family = 'meetup'
  ) then
  -- RETURNING, never a second lookup: a lookup by (family, name) is how 0193 once
  -- matched the wrong row and inserted a second version 1 (0193:450-453).
  insert into public.design_templates (org_id, scope, purpose, family, name, is_default)
  values (
    p_org, 'org', 'poster', 'meetup', 'لقاء',
    not exists (
      select 1 from public.design_templates d
       where d.org_id = p_org and d.purpose = 'poster' and d.family = 'meetup'
         and d.is_default and d.retired_at is null
    )
  )
  returning id into v_template;

  insert into public.design_template_versions (template_id, version, document, dynamic_fields, font_hashes, published_at)
  values (v_template, 1, v_doc, v_fields, '{}', now());
  v_n := v_n + 1;
end if;

-- @family announcement@v2
v_doc    := $json${
  "schemaVersion": 1,
  "purpose": "poster",
  "master": {
    "width": 1080,
    "height": 1350,
    "unit": "px",
    "dpi": 72
  },
  "direction": "rtl",
  "background": {
    "type": "solid",
    "color": "{{design.violet}}"
  },
  "layers": [
    {
      "id": "l_logo",
      "kind": "image",
      "name": "شعار المؤسسة",
      "image": {
        "binding": "brand.logoAssetId",
        "fit": "contain"
      },
      "frame": {
        "x": 880,
        "y": 80,
        "w": 120,
        "h": 120
      },
      "presets": {
        "default": {
          "anchor": "block-start",
          "inlineAnchor": "end",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "name": "خلفية التصنيف",
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 2,
      "id": "l_pill_start",
      "kind": "shape",
      "frame": {
        "x": 80,
        "y": 80,
        "w": 72,
        "h": 72
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{design.ink}}"
      }
    },
    {
      "name": "خلفية التصنيف",
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 2,
      "id": "l_pill_body",
      "kind": "shape",
      "frame": {
        "x": 116,
        "y": 80,
        "w": 228,
        "h": 72
      },
      "shape": {
        "type": "rect",
        "fill": "{{design.ink}}"
      }
    },
    {
      "name": "خلفية التصنيف",
      "presets": {
        "default": {
          "anchor": "block-start",
          "scale": "proportional"
        }
      },
      "z": 2,
      "id": "l_pill_end",
      "kind": "shape",
      "frame": {
        "x": 308,
        "y": 80,
        "w": 72,
        "h": 72
      },
      "shape": {
        "type": "ellipse",
        "fill": "{{design.ink}}"
      }
    },
    {
      "id": "l_category",
      "kind": "text",
      "name": "التصنيف",
      "frame": {
        "x": 80,
        "y": 80,
        "w": 300,
        "h": 72
      },
      "text": {
        "literal": "إعلان"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 40,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{design.violet}}",
      "align": "center",
      "z": 10
    },
    {
      "id": "l_title",
      "kind": "text",
      "name": "عنوان الجلسة",
      "frame": {
        "x": 80,
        "y": 300,
        "w": 920,
        "h": 430
      },
      "text": {
        "binding": "session.title",
        "fallback": "عنوان الجلسة"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 96,
        "minSize": 56,
        "lineHeight": 1.12,
        "letterSpacing": 0,
        "weight": 800
      },
      "color": "{{design.ink}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 3
      },
      "z": 10
    },
    {
      "id": "l_presenters",
      "kind": "dynamic_field",
      "name": "المقدِّمون",
      "frame": {
        "x": 80,
        "y": 1010,
        "w": 640,
        "h": 130
      },
      "field": {
        "binding": "session.presenters",
        "fallback": "اسم المقدِّم"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 44,
        "minSize": 32,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{design.ink}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_when",
      "kind": "dynamic_field",
      "name": "الموعد",
      "frame": {
        "x": 80,
        "y": 1150,
        "w": 640,
        "h": 62
      },
      "field": {
        "binding": "session.startsAt",
        "fallback": "التاريخ والوقت"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 40,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{design.ink}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_qr",
      "kind": "qr",
      "name": "رمز الجلسة",
      "locked": true,
      "frame": {
        "x": 860,
        "y": 1130,
        "w": 140,
        "h": 140
      },
      "qr": {
        "binding": "session.eventUrl",
        "ecLevel": "M",
        "quietZoneModules": 4
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "inlineAnchor": "end",
          "scale": "proportional"
        }
      },
      "z": 10
    }
  ]
}$json$::jsonb;
v_fields := $fields$["brand.logoAssetId","session.title","session.presenters","session.startsAt","session.eventUrl"]$fields$::jsonb;

if not exists (
    select 1 from public.design_templates t
     where t.org_id = p_org and t.purpose = 'poster' and t.family = 'announcement'
  ) then
  -- RETURNING, never a second lookup: a lookup by (family, name) is how 0193 once
  -- matched the wrong row and inserted a second version 1 (0193:450-453).
  insert into public.design_templates (org_id, scope, purpose, family, name, is_default)
  values (
    p_org, 'org', 'poster', 'announcement', 'إعلان',
    not exists (
      select 1 from public.design_templates d
       where d.org_id = p_org and d.purpose = 'poster' and d.family = 'announcement'
         and d.is_default and d.retired_at is null
    )
  )
  returning id into v_template;

  insert into public.design_template_versions (template_id, version, document, dynamic_fields, font_hashes, published_at)
  values (v_template, 1, v_doc, v_fields, '{}', now());
  v_n := v_n + 1;
end if;

-- @family attendance@landscape@v2
v_doc    := $json${
  "schemaVersion": 1,
  "purpose": "certificate",
  "master": {
    "width": 3508,
    "height": 2480,
    "unit": "px",
    "dpi": 300
  },
  "direction": "rtl",
  "background": {
    "type": "solid",
    "color": "{{brand.canvas}}"
  },
  "layers": [
    {
      "id": "l_logo",
      "kind": "image",
      "name": "شعار المؤسسة",
      "image": {
        "binding": "brand.logoAssetId",
        "fit": "contain"
      },
      "frame": {
        "x": 240,
        "y": 240,
        "w": 220,
        "h": 220
      },
      "presets": {
        "default": {
          "anchor": "block-start",
          "inlineAnchor": "end",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_wordmark",
      "kind": "text",
      "name": "اسم المنصة",
      "frame": {
        "x": 512,
        "y": 265,
        "w": 700,
        "h": 170
      },
      "text": {
        "literal": "كريم معرفة"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 120,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.fgHeading}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_org",
      "kind": "dynamic_field",
      "name": "اسم المؤسسة",
      "frame": {
        "x": 1264,
        "y": 327,
        "w": 1176,
        "h": 90
      },
      "field": {
        "binding": "org.name",
        "fallback": "اسم المؤسسة"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 64,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_kind",
      "kind": "text",
      "name": "نوع الشهادة",
      "frame": {
        "x": 240,
        "y": 500,
        "w": 2200,
        "h": 120
      },
      "text": {
        "literal": "شهادة حضور"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 84,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_recipient",
      "kind": "dynamic_field",
      "name": "اسم المستفيد",
      "frame": {
        "x": 240,
        "y": 640,
        "w": 3028,
        "h": 850
      },
      "field": {
        "binding": "recipient.name",
        "fallback": "اسم المستفيد"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 300,
        "minSize": 150,
        "lineHeight": 1.12,
        "letterSpacing": 0,
        "weight": 800
      },
      "color": "{{brand.fgHeading}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_reason",
      "kind": "dynamic_field",
      "name": "عن الجلسة",
      "frame": {
        "x": 240,
        "y": 1540,
        "w": 3028,
        "h": 260
      },
      "field": {
        "binding": "session.title",
        "fallback": "عنوان الجلسة"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 72,
        "minSize": 48,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgBody}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_issued",
      "kind": "dynamic_field",
      "name": "تاريخ الإصدار",
      "frame": {
        "x": 240,
        "y": 1840,
        "w": 1400,
        "h": 100
      },
      "field": {
        "binding": "certificate.issuedAt",
        "fallback": "تاريخ الإصدار"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_qr",
      "kind": "qr",
      "name": "رمز التحقّق",
      "locked": true,
      "frame": {
        "x": 2948,
        "y": 1920,
        "w": 320,
        "h": 320
      },
      "qr": {
        "binding": "certificate.verifyUrl",
        "ecLevel": "Q",
        "quietZoneModules": 4
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_serial",
      "kind": "dynamic_field",
      "name": "الرقم التسلسلي",
      "locked": true,
      "frame": {
        "x": 240,
        "y": 2020,
        "w": 1400,
        "h": 100
      },
      "field": {
        "binding": "certificate.serial",
        "fallback": "الرقم التسلسلي"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_code",
      "kind": "dynamic_field",
      "name": "رمز التحقّق النصّي",
      "locked": true,
      "frame": {
        "x": 240,
        "y": 2130,
        "w": 1400,
        "h": 100
      },
      "field": {
        "binding": "certificate.verificationCode",
        "fallback": "رمز التحقّق"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_signature",
      "kind": "shape",
      "name": "موضع التوقيع",
      "locked": true,
      "frame": {
        "x": 1900,
        "y": 2120,
        "w": 800,
        "h": 2
      },
      "shape": {
        "type": "rect",
        "fill": "{{brand.edge}}"
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_signature_label",
      "kind": "text",
      "name": "تسمية التوقيع",
      "frame": {
        "x": 1900,
        "y": 2144,
        "w": 800,
        "h": 96
      },
      "text": {
        "literal": "التوقيع"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "letterSpacing": 0,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    }
  ]
}$json$::jsonb;
v_fields := $fields$["brand.logoAssetId","org.name","recipient.name","session.title","certificate.issuedAt","certificate.verifyUrl","certificate.serial","certificate.verificationCode"]$fields$::jsonb;

if not exists (
    select 1
      from public.design_templates t
      cross join lateral (
        select v.document from public.design_template_versions v
         where v.template_id = t.id order by v.version desc limit 1
      ) l
     where t.org_id = p_org and t.purpose = 'certificate' and t.family = 'attendance'
       and ((l.document #>> '{master,width}')::numeric >= (l.document #>> '{master,height}')::numeric) is true
  ) then
  -- RETURNING, never a second lookup: a lookup by (family, name) is how 0193 once
  -- matched the wrong row and inserted a second version 1 (0193:450-453).
  insert into public.design_templates (org_id, scope, purpose, family, name, is_default)
  values (
    p_org, 'org', 'certificate', 'attendance', 'شهادة حضور أفقية',
    not exists (
      select 1 from public.design_templates d
       where d.org_id = p_org and d.purpose = 'certificate' and d.family = 'attendance'
         and d.is_default and d.retired_at is null
    )
  )
  returning id into v_template;

  insert into public.design_template_versions (template_id, version, document, dynamic_fields, font_hashes, published_at)
  values (v_template, 1, v_doc, v_fields, '{}', now());
  v_n := v_n + 1;
end if;

-- @family attendance@portrait@v2
v_doc    := $json${
  "schemaVersion": 1,
  "purpose": "certificate",
  "master": {
    "width": 2480,
    "height": 3508,
    "unit": "px",
    "dpi": 300
  },
  "direction": "rtl",
  "background": {
    "type": "solid",
    "color": "{{brand.canvas}}"
  },
  "layers": [
    {
      "id": "l_logo",
      "kind": "image",
      "name": "شعار المؤسسة",
      "image": {
        "binding": "brand.logoAssetId",
        "fit": "contain"
      },
      "frame": {
        "x": 240,
        "y": 240,
        "w": 220,
        "h": 220
      },
      "presets": {
        "default": {
          "anchor": "block-start",
          "inlineAnchor": "end",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_wordmark",
      "kind": "text",
      "name": "اسم المنصة",
      "frame": {
        "x": 512,
        "y": 265,
        "w": 700,
        "h": 170
      },
      "text": {
        "literal": "كريم معرفة"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 120,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.fgHeading}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_org",
      "kind": "dynamic_field",
      "name": "اسم المؤسسة",
      "frame": {
        "x": 1264,
        "y": 327,
        "w": 676,
        "h": 90
      },
      "field": {
        "binding": "org.name",
        "fallback": "اسم المؤسسة"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 64,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_kind",
      "kind": "text",
      "name": "نوع الشهادة",
      "frame": {
        "x": 240,
        "y": 500,
        "w": 1700,
        "h": 120
      },
      "text": {
        "literal": "شهادة حضور"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 84,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_recipient",
      "kind": "dynamic_field",
      "name": "اسم المستفيد",
      "frame": {
        "x": 240,
        "y": 700,
        "w": 2000,
        "h": 1000
      },
      "field": {
        "binding": "recipient.name",
        "fallback": "اسم المستفيد"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 300,
        "minSize": 150,
        "lineHeight": 1.12,
        "letterSpacing": 0,
        "weight": 800
      },
      "color": "{{brand.fgHeading}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_reason",
      "kind": "dynamic_field",
      "name": "عن الجلسة",
      "frame": {
        "x": 240,
        "y": 1780,
        "w": 2000,
        "h": 260
      },
      "field": {
        "binding": "session.title",
        "fallback": "عنوان الجلسة"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 72,
        "minSize": 48,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgBody}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_issued",
      "kind": "dynamic_field",
      "name": "تاريخ الإصدار",
      "frame": {
        "x": 240,
        "y": 2100,
        "w": 1300,
        "h": 100
      },
      "field": {
        "binding": "certificate.issuedAt",
        "fallback": "تاريخ الإصدار"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_qr",
      "kind": "qr",
      "name": "رمز التحقّق",
      "locked": true,
      "frame": {
        "x": 1920,
        "y": 2948,
        "w": 320,
        "h": 320
      },
      "qr": {
        "binding": "certificate.verifyUrl",
        "ecLevel": "Q",
        "quietZoneModules": 4
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_serial",
      "kind": "dynamic_field",
      "name": "الرقم التسلسلي",
      "locked": true,
      "frame": {
        "x": 240,
        "y": 2980,
        "w": 1300,
        "h": 100
      },
      "field": {
        "binding": "certificate.serial",
        "fallback": "الرقم التسلسلي"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_code",
      "kind": "dynamic_field",
      "name": "رمز التحقّق النصّي",
      "locked": true,
      "frame": {
        "x": 240,
        "y": 3090,
        "w": 1300,
        "h": 100
      },
      "field": {
        "binding": "certificate.verificationCode",
        "fallback": "رمز التحقّق"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_signature",
      "kind": "shape",
      "name": "موضع التوقيع",
      "locked": true,
      "frame": {
        "x": 1440,
        "y": 2900,
        "w": 800,
        "h": 2
      },
      "shape": {
        "type": "rect",
        "fill": "{{brand.edge}}"
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_signature_label",
      "kind": "text",
      "name": "تسمية التوقيع",
      "frame": {
        "x": 1440,
        "y": 2931,
        "w": 440,
        "h": 96
      },
      "text": {
        "literal": "التوقيع"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "letterSpacing": 0,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    }
  ]
}$json$::jsonb;
v_fields := $fields$["brand.logoAssetId","org.name","recipient.name","session.title","certificate.issuedAt","certificate.verifyUrl","certificate.serial","certificate.verificationCode"]$fields$::jsonb;

if not exists (
    select 1
      from public.design_templates t
      cross join lateral (
        select v.document from public.design_template_versions v
         where v.template_id = t.id order by v.version desc limit 1
      ) l
     where t.org_id = p_org and t.purpose = 'certificate' and t.family = 'attendance'
       and ((l.document #>> '{master,width}')::numeric >= (l.document #>> '{master,height}')::numeric) is false
  ) then
  -- RETURNING, never a second lookup: a lookup by (family, name) is how 0193 once
  -- matched the wrong row and inserted a second version 1 (0193:450-453).
  insert into public.design_templates (org_id, scope, purpose, family, name, is_default)
  values (
    p_org, 'org', 'certificate', 'attendance', 'شهادة حضور عمودية',
    false
  )
  returning id into v_template;

  insert into public.design_template_versions (template_id, version, document, dynamic_fields, font_hashes, published_at)
  values (v_template, 1, v_doc, v_fields, '{}', now());
  v_n := v_n + 1;
end if;

-- @family presenter@landscape@v2
v_doc    := $json${
  "schemaVersion": 1,
  "purpose": "certificate",
  "master": {
    "width": 3508,
    "height": 2480,
    "unit": "px",
    "dpi": 300
  },
  "direction": "rtl",
  "background": {
    "type": "solid",
    "color": "{{brand.canvas}}"
  },
  "layers": [
    {
      "id": "l_logo",
      "kind": "image",
      "name": "شعار المؤسسة",
      "image": {
        "binding": "brand.logoAssetId",
        "fit": "contain"
      },
      "frame": {
        "x": 240,
        "y": 240,
        "w": 220,
        "h": 220
      },
      "presets": {
        "default": {
          "anchor": "block-start",
          "inlineAnchor": "end",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_wordmark",
      "kind": "text",
      "name": "اسم المنصة",
      "frame": {
        "x": 512,
        "y": 265,
        "w": 700,
        "h": 170
      },
      "text": {
        "literal": "كريم معرفة"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 120,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.fgHeading}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_org",
      "kind": "dynamic_field",
      "name": "اسم المؤسسة",
      "frame": {
        "x": 1264,
        "y": 327,
        "w": 1176,
        "h": 90
      },
      "field": {
        "binding": "org.name",
        "fallback": "اسم المؤسسة"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 64,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_kind",
      "kind": "text",
      "name": "نوع الشهادة",
      "frame": {
        "x": 240,
        "y": 500,
        "w": 2200,
        "h": 120
      },
      "text": {
        "literal": "شهادة تقديم"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 84,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_recipient",
      "kind": "dynamic_field",
      "name": "اسم المستفيد",
      "frame": {
        "x": 240,
        "y": 640,
        "w": 3028,
        "h": 850
      },
      "field": {
        "binding": "recipient.name",
        "fallback": "اسم المستفيد"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 300,
        "minSize": 150,
        "lineHeight": 1.12,
        "letterSpacing": 0,
        "weight": 800
      },
      "color": "{{brand.fgHeading}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_reason",
      "kind": "dynamic_field",
      "name": "عن الجلسة",
      "frame": {
        "x": 240,
        "y": 1540,
        "w": 3028,
        "h": 260
      },
      "field": {
        "binding": "session.title",
        "fallback": "عنوان الجلسة"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 72,
        "minSize": 48,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgBody}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_issued",
      "kind": "dynamic_field",
      "name": "تاريخ الإصدار",
      "frame": {
        "x": 240,
        "y": 1840,
        "w": 1400,
        "h": 100
      },
      "field": {
        "binding": "certificate.issuedAt",
        "fallback": "تاريخ الإصدار"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_qr",
      "kind": "qr",
      "name": "رمز التحقّق",
      "locked": true,
      "frame": {
        "x": 2948,
        "y": 1920,
        "w": 320,
        "h": 320
      },
      "qr": {
        "binding": "certificate.verifyUrl",
        "ecLevel": "Q",
        "quietZoneModules": 4
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_serial",
      "kind": "dynamic_field",
      "name": "الرقم التسلسلي",
      "locked": true,
      "frame": {
        "x": 240,
        "y": 2020,
        "w": 1400,
        "h": 100
      },
      "field": {
        "binding": "certificate.serial",
        "fallback": "الرقم التسلسلي"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_code",
      "kind": "dynamic_field",
      "name": "رمز التحقّق النصّي",
      "locked": true,
      "frame": {
        "x": 240,
        "y": 2130,
        "w": 1400,
        "h": 100
      },
      "field": {
        "binding": "certificate.verificationCode",
        "fallback": "رمز التحقّق"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_signature",
      "kind": "shape",
      "name": "موضع التوقيع",
      "locked": true,
      "frame": {
        "x": 1900,
        "y": 2120,
        "w": 800,
        "h": 2
      },
      "shape": {
        "type": "rect",
        "fill": "{{brand.edge}}"
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_signature_label",
      "kind": "text",
      "name": "تسمية التوقيع",
      "frame": {
        "x": 1900,
        "y": 2144,
        "w": 800,
        "h": 96
      },
      "text": {
        "literal": "التوقيع"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "letterSpacing": 0,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    }
  ]
}$json$::jsonb;
v_fields := $fields$["brand.logoAssetId","org.name","recipient.name","session.title","certificate.issuedAt","certificate.verifyUrl","certificate.serial","certificate.verificationCode"]$fields$::jsonb;

if not exists (
    select 1
      from public.design_templates t
      cross join lateral (
        select v.document from public.design_template_versions v
         where v.template_id = t.id order by v.version desc limit 1
      ) l
     where t.org_id = p_org and t.purpose = 'certificate' and t.family = 'presenter'
       and ((l.document #>> '{master,width}')::numeric >= (l.document #>> '{master,height}')::numeric) is true
  ) then
  -- RETURNING, never a second lookup: a lookup by (family, name) is how 0193 once
  -- matched the wrong row and inserted a second version 1 (0193:450-453).
  insert into public.design_templates (org_id, scope, purpose, family, name, is_default)
  values (
    p_org, 'org', 'certificate', 'presenter', 'شهادة تقديم أفقية',
    not exists (
      select 1 from public.design_templates d
       where d.org_id = p_org and d.purpose = 'certificate' and d.family = 'presenter'
         and d.is_default and d.retired_at is null
    )
  )
  returning id into v_template;

  insert into public.design_template_versions (template_id, version, document, dynamic_fields, font_hashes, published_at)
  values (v_template, 1, v_doc, v_fields, '{}', now());
  v_n := v_n + 1;
end if;

-- @family presenter@portrait@v2
v_doc    := $json${
  "schemaVersion": 1,
  "purpose": "certificate",
  "master": {
    "width": 2480,
    "height": 3508,
    "unit": "px",
    "dpi": 300
  },
  "direction": "rtl",
  "background": {
    "type": "solid",
    "color": "{{brand.canvas}}"
  },
  "layers": [
    {
      "id": "l_logo",
      "kind": "image",
      "name": "شعار المؤسسة",
      "image": {
        "binding": "brand.logoAssetId",
        "fit": "contain"
      },
      "frame": {
        "x": 240,
        "y": 240,
        "w": 220,
        "h": 220
      },
      "presets": {
        "default": {
          "anchor": "block-start",
          "inlineAnchor": "end",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_wordmark",
      "kind": "text",
      "name": "اسم المنصة",
      "frame": {
        "x": 512,
        "y": 265,
        "w": 700,
        "h": 170
      },
      "text": {
        "literal": "كريم معرفة"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 120,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.fgHeading}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_org",
      "kind": "dynamic_field",
      "name": "اسم المؤسسة",
      "frame": {
        "x": 1264,
        "y": 327,
        "w": 676,
        "h": 90
      },
      "field": {
        "binding": "org.name",
        "fallback": "اسم المؤسسة"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 64,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_kind",
      "kind": "text",
      "name": "نوع الشهادة",
      "frame": {
        "x": 240,
        "y": 500,
        "w": 1700,
        "h": 120
      },
      "text": {
        "literal": "شهادة تقديم"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 84,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_recipient",
      "kind": "dynamic_field",
      "name": "اسم المستفيد",
      "frame": {
        "x": 240,
        "y": 700,
        "w": 2000,
        "h": 1000
      },
      "field": {
        "binding": "recipient.name",
        "fallback": "اسم المستفيد"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 300,
        "minSize": 150,
        "lineHeight": 1.12,
        "letterSpacing": 0,
        "weight": 800
      },
      "color": "{{brand.fgHeading}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_reason",
      "kind": "dynamic_field",
      "name": "عن الجلسة",
      "frame": {
        "x": 240,
        "y": 1780,
        "w": 2000,
        "h": 260
      },
      "field": {
        "binding": "session.title",
        "fallback": "عنوان الجلسة"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 72,
        "minSize": 48,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgBody}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_issued",
      "kind": "dynamic_field",
      "name": "تاريخ الإصدار",
      "frame": {
        "x": 240,
        "y": 2100,
        "w": 1300,
        "h": 100
      },
      "field": {
        "binding": "certificate.issuedAt",
        "fallback": "تاريخ الإصدار"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_qr",
      "kind": "qr",
      "name": "رمز التحقّق",
      "locked": true,
      "frame": {
        "x": 1920,
        "y": 2948,
        "w": 320,
        "h": 320
      },
      "qr": {
        "binding": "certificate.verifyUrl",
        "ecLevel": "Q",
        "quietZoneModules": 4
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_serial",
      "kind": "dynamic_field",
      "name": "الرقم التسلسلي",
      "locked": true,
      "frame": {
        "x": 240,
        "y": 2980,
        "w": 1300,
        "h": 100
      },
      "field": {
        "binding": "certificate.serial",
        "fallback": "الرقم التسلسلي"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_code",
      "kind": "dynamic_field",
      "name": "رمز التحقّق النصّي",
      "locked": true,
      "frame": {
        "x": 240,
        "y": 3090,
        "w": 1300,
        "h": 100
      },
      "field": {
        "binding": "certificate.verificationCode",
        "fallback": "رمز التحقّق"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_signature",
      "kind": "shape",
      "name": "موضع التوقيع",
      "locked": true,
      "frame": {
        "x": 1440,
        "y": 2900,
        "w": 800,
        "h": 2
      },
      "shape": {
        "type": "rect",
        "fill": "{{brand.edge}}"
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_signature_label",
      "kind": "text",
      "name": "تسمية التوقيع",
      "frame": {
        "x": 1440,
        "y": 2931,
        "w": 440,
        "h": 96
      },
      "text": {
        "literal": "التوقيع"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "letterSpacing": 0,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    }
  ]
}$json$::jsonb;
v_fields := $fields$["brand.logoAssetId","org.name","recipient.name","session.title","certificate.issuedAt","certificate.verifyUrl","certificate.serial","certificate.verificationCode"]$fields$::jsonb;

if not exists (
    select 1
      from public.design_templates t
      cross join lateral (
        select v.document from public.design_template_versions v
         where v.template_id = t.id order by v.version desc limit 1
      ) l
     where t.org_id = p_org and t.purpose = 'certificate' and t.family = 'presenter'
       and ((l.document #>> '{master,width}')::numeric >= (l.document #>> '{master,height}')::numeric) is false
  ) then
  -- RETURNING, never a second lookup: a lookup by (family, name) is how 0193 once
  -- matched the wrong row and inserted a second version 1 (0193:450-453).
  insert into public.design_templates (org_id, scope, purpose, family, name, is_default)
  values (
    p_org, 'org', 'certificate', 'presenter', 'شهادة تقديم عمودية',
    false
  )
  returning id into v_template;

  insert into public.design_template_versions (template_id, version, document, dynamic_fields, font_hashes, published_at)
  values (v_template, 1, v_doc, v_fields, '{}', now());
  v_n := v_n + 1;
end if;

-- @family achievement@landscape@v2
v_doc    := $json${
  "schemaVersion": 1,
  "purpose": "certificate",
  "master": {
    "width": 3508,
    "height": 2480,
    "unit": "px",
    "dpi": 300
  },
  "direction": "rtl",
  "background": {
    "type": "solid",
    "color": "{{brand.canvas}}"
  },
  "layers": [
    {
      "id": "l_logo",
      "kind": "image",
      "name": "شعار المؤسسة",
      "image": {
        "binding": "brand.logoAssetId",
        "fit": "contain"
      },
      "frame": {
        "x": 240,
        "y": 240,
        "w": 220,
        "h": 220
      },
      "presets": {
        "default": {
          "anchor": "block-start",
          "inlineAnchor": "end",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_wordmark",
      "kind": "text",
      "name": "اسم المنصة",
      "frame": {
        "x": 512,
        "y": 265,
        "w": 700,
        "h": 170
      },
      "text": {
        "literal": "كريم معرفة"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 120,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.fgHeading}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_org",
      "kind": "dynamic_field",
      "name": "اسم المؤسسة",
      "frame": {
        "x": 1264,
        "y": 327,
        "w": 1176,
        "h": 90
      },
      "field": {
        "binding": "org.name",
        "fallback": "اسم المؤسسة"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 64,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_kind",
      "kind": "text",
      "name": "نوع الشهادة",
      "frame": {
        "x": 240,
        "y": 500,
        "w": 2200,
        "h": 120
      },
      "text": {
        "literal": "شهادة إنجاز"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 84,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_recipient",
      "kind": "dynamic_field",
      "name": "اسم المستفيد",
      "frame": {
        "x": 240,
        "y": 640,
        "w": 3028,
        "h": 850
      },
      "field": {
        "binding": "recipient.name",
        "fallback": "اسم المستفيد"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 300,
        "minSize": 150,
        "lineHeight": 1.12,
        "letterSpacing": 0,
        "weight": 800
      },
      "color": "{{brand.fgHeading}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_reason",
      "kind": "dynamic_field",
      "name": "عن الجلسة",
      "frame": {
        "x": 240,
        "y": 1540,
        "w": 3028,
        "h": 260
      },
      "field": {
        "binding": "certificate.achievementName",
        "fallback": "اسم الإنجاز"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 72,
        "minSize": 48,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgBody}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_issued",
      "kind": "dynamic_field",
      "name": "تاريخ الإصدار",
      "frame": {
        "x": 240,
        "y": 1840,
        "w": 1400,
        "h": 100
      },
      "field": {
        "binding": "certificate.issuedAt",
        "fallback": "تاريخ الإصدار"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_qr",
      "kind": "qr",
      "name": "رمز التحقّق",
      "locked": true,
      "frame": {
        "x": 2948,
        "y": 1920,
        "w": 320,
        "h": 320
      },
      "qr": {
        "binding": "certificate.verifyUrl",
        "ecLevel": "Q",
        "quietZoneModules": 4
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_serial",
      "kind": "dynamic_field",
      "name": "الرقم التسلسلي",
      "locked": true,
      "frame": {
        "x": 240,
        "y": 2020,
        "w": 1400,
        "h": 100
      },
      "field": {
        "binding": "certificate.serial",
        "fallback": "الرقم التسلسلي"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_code",
      "kind": "dynamic_field",
      "name": "رمز التحقّق النصّي",
      "locked": true,
      "frame": {
        "x": 240,
        "y": 2130,
        "w": 1400,
        "h": 100
      },
      "field": {
        "binding": "certificate.verificationCode",
        "fallback": "رمز التحقّق"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_signature",
      "kind": "shape",
      "name": "موضع التوقيع",
      "locked": true,
      "frame": {
        "x": 1900,
        "y": 2120,
        "w": 800,
        "h": 2
      },
      "shape": {
        "type": "rect",
        "fill": "{{brand.edge}}"
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_signature_label",
      "kind": "text",
      "name": "تسمية التوقيع",
      "frame": {
        "x": 1900,
        "y": 2144,
        "w": 800,
        "h": 96
      },
      "text": {
        "literal": "التوقيع"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "letterSpacing": 0,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    }
  ]
}$json$::jsonb;
v_fields := $fields$["brand.logoAssetId","org.name","recipient.name","certificate.achievementName","certificate.issuedAt","certificate.verifyUrl","certificate.serial","certificate.verificationCode"]$fields$::jsonb;

if not exists (
    select 1
      from public.design_templates t
      cross join lateral (
        select v.document from public.design_template_versions v
         where v.template_id = t.id order by v.version desc limit 1
      ) l
     where t.org_id = p_org and t.purpose = 'certificate' and t.family = 'achievement'
       and ((l.document #>> '{master,width}')::numeric >= (l.document #>> '{master,height}')::numeric) is true
  ) then
  -- RETURNING, never a second lookup: a lookup by (family, name) is how 0193 once
  -- matched the wrong row and inserted a second version 1 (0193:450-453).
  insert into public.design_templates (org_id, scope, purpose, family, name, is_default)
  values (
    p_org, 'org', 'certificate', 'achievement', 'شهادة إنجاز أفقية',
    not exists (
      select 1 from public.design_templates d
       where d.org_id = p_org and d.purpose = 'certificate' and d.family = 'achievement'
         and d.is_default and d.retired_at is null
    )
  )
  returning id into v_template;

  insert into public.design_template_versions (template_id, version, document, dynamic_fields, font_hashes, published_at)
  values (v_template, 1, v_doc, v_fields, '{}', now());
  v_n := v_n + 1;
end if;

-- @family achievement@portrait@v2
v_doc    := $json${
  "schemaVersion": 1,
  "purpose": "certificate",
  "master": {
    "width": 2480,
    "height": 3508,
    "unit": "px",
    "dpi": 300
  },
  "direction": "rtl",
  "background": {
    "type": "solid",
    "color": "{{brand.canvas}}"
  },
  "layers": [
    {
      "id": "l_logo",
      "kind": "image",
      "name": "شعار المؤسسة",
      "image": {
        "binding": "brand.logoAssetId",
        "fit": "contain"
      },
      "frame": {
        "x": 240,
        "y": 240,
        "w": 220,
        "h": 220
      },
      "presets": {
        "default": {
          "anchor": "block-start",
          "inlineAnchor": "end",
          "scale": "proportional"
        }
      },
      "z": 10
    },
    {
      "id": "l_wordmark",
      "kind": "text",
      "name": "اسم المنصة",
      "frame": {
        "x": 512,
        "y": 265,
        "w": 700,
        "h": 170
      },
      "text": {
        "literal": "كريم معرفة"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 120,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.fgHeading}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_org",
      "kind": "dynamic_field",
      "name": "اسم المؤسسة",
      "frame": {
        "x": 1264,
        "y": 327,
        "w": 676,
        "h": 90
      },
      "field": {
        "binding": "org.name",
        "fallback": "اسم المؤسسة"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 64,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_kind",
      "kind": "text",
      "name": "نوع الشهادة",
      "frame": {
        "x": 240,
        "y": 500,
        "w": 1700,
        "h": 120
      },
      "text": {
        "literal": "شهادة إنجاز"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 84,
        "lineHeight": 1.4,
        "letterSpacing": 0,
        "weight": 700
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_recipient",
      "kind": "dynamic_field",
      "name": "اسم المستفيد",
      "frame": {
        "x": 240,
        "y": 700,
        "w": 2000,
        "h": 1000
      },
      "field": {
        "binding": "recipient.name",
        "fallback": "اسم المستفيد"
      },
      "font": {
        "family": "Baloo Bhaijaan 2",
        "size": 300,
        "minSize": 150,
        "lineHeight": 1.12,
        "letterSpacing": 0,
        "weight": 800
      },
      "color": "{{brand.fgHeading}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_reason",
      "kind": "dynamic_field",
      "name": "عن الجلسة",
      "frame": {
        "x": 240,
        "y": 1780,
        "w": 2000,
        "h": 260
      },
      "field": {
        "binding": "certificate.achievementName",
        "fallback": "اسم الإنجاز"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 72,
        "minSize": 48,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgBody}}",
      "align": "start",
      "autoFit": {
        "mode": "shrink-then-wrap",
        "maxLines": 2
      },
      "z": 10
    },
    {
      "id": "l_issued",
      "kind": "dynamic_field",
      "name": "تاريخ الإصدار",
      "frame": {
        "x": 240,
        "y": 2100,
        "w": 1300,
        "h": 100
      },
      "field": {
        "binding": "certificate.issuedAt",
        "fallback": "تاريخ الإصدار"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "z": 10
    },
    {
      "id": "l_qr",
      "kind": "qr",
      "name": "رمز التحقّق",
      "locked": true,
      "frame": {
        "x": 1920,
        "y": 2948,
        "w": 320,
        "h": 320
      },
      "qr": {
        "binding": "certificate.verifyUrl",
        "ecLevel": "Q",
        "quietZoneModules": 4
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_serial",
      "kind": "dynamic_field",
      "name": "الرقم التسلسلي",
      "locked": true,
      "frame": {
        "x": 240,
        "y": 2980,
        "w": 1300,
        "h": 100
      },
      "field": {
        "binding": "certificate.serial",
        "fallback": "الرقم التسلسلي"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_code",
      "kind": "dynamic_field",
      "name": "رمز التحقّق النصّي",
      "locked": true,
      "frame": {
        "x": 240,
        "y": 3090,
        "w": 1300,
        "h": 100
      },
      "field": {
        "binding": "certificate.verificationCode",
        "fallback": "رمز التحقّق"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_signature",
      "kind": "shape",
      "name": "موضع التوقيع",
      "locked": true,
      "frame": {
        "x": 1440,
        "y": 2900,
        "w": 800,
        "h": 2
      },
      "shape": {
        "type": "rect",
        "fill": "{{brand.edge}}"
      },
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    },
    {
      "id": "l_signature_label",
      "kind": "text",
      "name": "تسمية التوقيع",
      "frame": {
        "x": 1440,
        "y": 2931,
        "w": 440,
        "h": 96
      },
      "text": {
        "literal": "التوقيع"
      },
      "font": {
        "family": "IBM Plex Sans Arabic",
        "size": 56,
        "lineHeight": 1.7,
        "letterSpacing": 0,
        "weight": 400
      },
      "color": "{{brand.fgMuted}}",
      "align": "start",
      "presets": {
        "default": {
          "anchor": "block-end",
          "scale": "fixed"
        }
      },
      "z": 20
    }
  ]
}$json$::jsonb;
v_fields := $fields$["brand.logoAssetId","org.name","recipient.name","certificate.achievementName","certificate.issuedAt","certificate.verifyUrl","certificate.serial","certificate.verificationCode"]$fields$::jsonb;

if not exists (
    select 1
      from public.design_templates t
      cross join lateral (
        select v.document from public.design_template_versions v
         where v.template_id = t.id order by v.version desc limit 1
      ) l
     where t.org_id = p_org and t.purpose = 'certificate' and t.family = 'achievement'
       and ((l.document #>> '{master,width}')::numeric >= (l.document #>> '{master,height}')::numeric) is false
  ) then
  -- RETURNING, never a second lookup: a lookup by (family, name) is how 0193 once
  -- matched the wrong row and inserted a second version 1 (0193:450-453).
  insert into public.design_templates (org_id, scope, purpose, family, name, is_default)
  values (
    p_org, 'org', 'certificate', 'achievement', 'شهادة إنجاز عمودية',
    false
  )
  returning id into v_template;

  insert into public.design_template_versions (template_id, version, document, dynamic_fields, font_hashes, published_at)
  values (v_template, 1, v_doc, v_fields, '{}', now());
  v_n := v_n + 1;
end if;

return v_n;
end $seed$;

-- Owner-only. It is called by `orgs_seed_templates` (the trigger, M1's second part) and by M1's
-- backfill, both as the owner. No grant, so PostgREST never sees it (tests/rls/definer-exposure.test.ts).
revoke execute on function public.seed_org_templates(uuid) from public, anon, authenticated, service_role;

comment on function public.seed_org_templates(uuid) is
  'DEC-254 §3 — insert the baseline library as one org''s own published templates; idempotent by composition; returns how many it inserted. Owner-only.';
