"use client";

import { useId, useRef, useState, type ClipboardEvent, type KeyboardEvent } from "react";
import type { CodeInputProps } from "@/components/ui";
import { describedIds } from "@/components/ui/field";
import { AlertCircleIcon } from "@/components/ui/icons";

// The check-in code, in six boxes — REQ-UIX-035, REQ-CHK-002, REQ-CHK-003, DEC-186 §6.
//
// ★ THE ALPHABET IS THE MIGRATION'S, AND THIS FILE DOES NOT ENFORCE IT. A code
// is six of `ACDEFGHJKMNPQRTUVWXY34679` (`0010_m2_schema.sql:210`, generated by
// `0105_check_in_day.sql:117`), and `check_in()` is the judge. A character the
// member types that is not in it still appears: one that silently fails to
// appear is a failure with no message. Only case and separators are
// normalised — a code is compared upper-cased (`0105:279`), and a pasted
// «M7K 3QX» or «M7K-3QX» is the same code.
//
// ★ ONE NAME FOR THE GROUP, ONE POSITION PER BOX. The visible label names the
// `role="group"` (and, through `htmlFor`, lands a tap on box 1); each box is
// named by its position from the caller's catalogue — «الخانة 2 من 6» — so a
// screen reader entering box 2 hears where it is, not six unnamed fields. The
// error is tied to the GROUP by `aria-describedby` (the requirement's words),
// and each box carries `aria-invalid`, which a group role does not support.
//
// ★ LEFT TO RIGHT INSIDE AN ARABIC PAGE. The code is Latin, so the group is
// `dir="ltr"`: box 1 is on the left in either direction, the arrows move the
// way they point, and the label and the error above and below stay RTL.
//
// ★ IT POSTS ONE FIELD (REQ-CHK-003 as amended by DEC-186 §6): a hidden input
// under `name` carries the assembled code, so a Server Action reads `code`
// exactly as SCR-014's does today.
//
// ★ STATIC (DEC-186 §4). No pop as a character lands, and a wrong code never
// animates — the error appears in place. The complete state is a colour, not a
// movement.
//
// ★★ WHAT IS ON SHOW SURVIVES A FORM RESET (REQ-UIX-011, DEC-149 §1) — and it
// needs no repair here. React resets a `<form action>` after every submission.
// A controlled text box is not the select's or the checkbox's case: React keeps
// its `value` ATTRIBUTE in step with the state, so `reset()` restores what is on
// show. `code-input.test.tsx` proves it, so a React that stops doing so fails
// there rather than on SCR-014.
//
// Not a `<Field>` child: it names itself, as `ui/radio-group` does.

const LENGTH = 6;

/** Upper-case, and drop the separators a copied code may carry. Nothing else. */
function normalise(raw: string): string {
  return raw.toUpperCase().replace(/[\s-]/g, "");
}

function seed(defaultValue: string | undefined, length: number): string[] {
  const chars = [...normalise(defaultValue ?? "")];
  return Array.from({ length }, (_, i) => chars[i] ?? "");
}

export function CodeInput({
  name,
  id,
  label,
  positionLabels,
  length = LENGTH,
  defaultValue,
  error,
  invalid,
  "aria-describedby": describedBy,
  disabled,
  className = "",
}: CodeInputProps) {
  const generated = useId();
  const firstId = id ?? generated;
  const labelId = `${firstId}-label`;
  const errorId = `${firstId}-error`;
  const [chars, setChars] = useState<string[]>(() => seed(defaultValue, length));
  const boxes = useRef<(HTMLInputElement | null)[]>([]);
  const isInvalid = invalid ?? Boolean(error);
  const complete = chars.every(Boolean);

  const focusBox = (i: number) => boxes.current[Math.max(0, Math.min(length - 1, i))]?.focus();

  /** Write `text` into the boxes from `from`, and put the caret after it. */
  function fill(from: number, text: string) {
    const incoming = [...text];
    setChars((prev) => prev.map((c, i) => (i >= from && i - from < incoming.length ? incoming[i - from] : c)));
    focusBox(from + incoming.length);
  }

  function onChange(i: number, raw: string) {
    const value = normalise(raw);
    if (value.length <= 1) {
      setChars((prev) => prev.map((c, j) => (j === i ? value : c)));
      if (value) focusBox(i + 1);
      return;
    }
    // More than one character at once — a keyboard's suggestion or an autofill: treated as a paste.
    fill(i, value.slice(0, length - i));
  }

  function onKeyDown(i: number, event: KeyboardEvent<HTMLInputElement>) {
    // The group is `dir="ltr"`, so the arrow that points left goes to the box on the left.
    if (event.key === "ArrowLeft") {
      event.preventDefault();
      focusBox(i - 1);
    } else if (event.key === "ArrowRight") {
      event.preventDefault();
      focusBox(i + 1);
    } else if (event.key === "Home") {
      event.preventDefault();
      focusBox(0);
    } else if (event.key === "End") {
      event.preventDefault();
      focusBox(length - 1);
    } else if (event.key === "Backspace" && !chars[i] && i > 0) {
      event.preventDefault();
      focusBox(i - 1);
    }
  }

  function onPaste(i: number, event: ClipboardEvent<HTMLInputElement>) {
    const pasted = normalise(event.clipboardData.getData("text"));
    if (!pasted) return;
    event.preventDefault();
    // A whole code fills from the first box wherever it lands; a fragment fills from here.
    if (pasted.length >= length) fill(0, pasted.slice(0, length));
    else fill(i, pasted.slice(0, length - i));
  }

  return (
    <div className={className}>
      <label id={labelId} htmlFor={firstId} className="text-label text-fg-heading">
        {label}
      </label>
      {/* The hidden field is what posts. A disabled control posts nothing, and neither does this. */}
      <input type="hidden" name={name} value={chars.join("")} disabled={disabled} />
      <div
        role="group"
        dir="ltr"
        aria-labelledby={labelId}
        aria-describedby={describedIds(error ? errorId : undefined, describedBy)}
        data-complete={complete || undefined}
        className="mt-2 flex gap-2"
      >
        {chars.map((char, i) => (
          // ui-lint-disable-next-line field — one box of six; the group is the control, named by its label
          <input
            key={i}
            ref={(node) => {
              boxes.current[i] = node;
            }}
            id={i === 0 ? firstId : `${firstId}-${i + 1}`}
            aria-label={positionLabels[i] ?? String(i + 1)}
            aria-invalid={isInvalid || undefined}
            value={char}
            onChange={(event) => onChange(i, event.currentTarget.value)}
            onKeyDown={(event) => onKeyDown(i, event)}
            onPaste={(event) => onPaste(i, event)}
            // Typing into a filled box replaces its character.
            onFocus={(event) => event.currentTarget.select()}
            disabled={disabled}
            inputMode="text"
            autoComplete="off"
            autoCorrect="off"
            autoCapitalize="off"
            spellCheck={false}
            maxLength={1}
            className={`h-14 min-w-11 flex-1 rounded-field border bg-canvas text-center text-h2 text-fg-heading disabled:cursor-not-allowed disabled:opacity-60 pg:h-15 pg:w-12 pg:flex-none pg:rounded-input pg:bg-raised pg:font-display ${
              isInvalid ? "border-error-border pg-dark:border-error-on-dark" : complete ? "border-edge-strong pg:border-accent" : "border-edge-strong"
            }`}
          />
        ))}
      </div>
      {/* The same shape as `<Field>`'s error, and for the same reason no `role="alert"`: the page's
          banner or summary is the announcement; this is what is read on arriving in the group. */}
      {error ? (
        <p id={errorId} className="mt-2 flex items-start gap-2 text-caption text-error pg-dark:text-error-on-dark">
          <AlertCircleIcon className="mt-[0.2em]" />
          <span>{error}</span>
        </p>
      ) : null}
    </div>
  );
}
